### ISSUE TITLE
Full planet build

### ISSUE THREAD

**Issue by hannojg** [mediagis/nominatim-docker#101]
Hey, 
how to do a full planet installation? I see that geofabrik offers pbfs for continents, but I don't see a file for the whole planet.

I would highly appreciate any guidance on how to achieve that. 
Thank you so much in advance!

**Comment by mtmail** [comment]
There's a copy of mirrors for the planet file https://wiki.openstreetmap.org/wiki/Planet.osm

**Comment by mtmail** [comment]
Almost forgot: on the FTP servers of the mirrors the file is usually in the `pbf` subdirectory named *.latest.pbf
