### ISSUE TITLE
run without volume

### ISSUE THREAD

**Issue by johemst** [mediagis/nominatim-docker#104]
Hey. I would like to build and run the image with the postgres data inside the container, without creating a volume to the host.

I have tried to build the image with a .osm.pbf and run init.sh but cant make it work when the data is imported. Any suggestion?

**Comment by boginw** [comment]
Your issue seems related to my issue #117. Can you confirm?

**Comment by philipkozeny** [comment]
The latest changes in 3.6 allow this now, more details in the Readme: https://github.com/mediagis/nominatim-docker/blob/master/3.6/README.md
