### ISSUE TITLE
Add external data source paths to local.php

### ISSUE THREAD

**Issue by buildscientist** [mediagis/nominatim-docker#107]
Hello mediagis - thanks for putting these Dockerfiles together. Great resource. 

The current steps to load/install the base OSM data using this Docker image work correctly as instructed in the current README.md. 

Using the same Docker volume/bind mount users are led to expect that the /data directory that contains the postgresdata directory as specified in nominatim 3.4 docs should also contain data for TIGER/wikipedia imports. 

```shell
docker run -t -v /home/me/nominatimdata:/data nominatim  sh /app/init.sh data/<your_country>.osm.pbf postgresdata 4
```  

Issue #89  presents an example of this confusion. In an effort to make this less confusing for future/existing users I recommend we add the following PHP constants in the local.php to override the ones in [nominatim-src/settings/defaults.php](https://github.com/openstreetmap/Nominatim/blob/master/settings/defaults.php#L48-L49)

```php
 @define('CONST_Tiger_Data_Path','/data/tiger')
 @define('CONST_Wikipedia_Data_Path','/data/wikipedia')
```
We can also instruct future users wanting to import TIGER/wikipedia to unpack the respective data sets into the local directory bound to /data.

**Comment by buildscientist** [comment]
The issue is systemic to a bug in the way Nominatim's SetupClass.php handles a call to the [glob method](https://github.com/openstreetmap/Nominatim/blob/3.4.x/lib/setup/SetupClass.php#L495). 

When SetupFunctions.importTigerData() is called if the data directory doesn't contain any files that match the *.sql the import process silently fails. 

The array that glob() returns should be checked if it's populated before iterating over it. The other alternative is to call is_countable() on value returned from glob() - something like 

``` php
if is_countable(glob()) {
//iterate over the array
}
```

**Comment by mtmail** [comment]
Feel free to add an issue to the Nominatim repository or even a PR about the ‘glob’. nominatim-docker is separate from Nominatim.

**Comment by buildscientist** [comment]
@mtmail - agree but I decided to mention this after digging into the code further. 

I still think the tiger/wikipedia constants should be overridden and the docs updated accordingly. I'll see about putting a PR through.

**Comment by philipkozeny** [comment]
Thanks, Tiger import and local file imports are now supported.
