### ISSUE TITLE
Places not found, can't use reverse geocoding API

### ISSUE THREAD

**Issue by UntitleDude** [mediagis/nominatim-docker#110]
Hi !

I've tried to setup my own Nominatim reverse geocoding server and I've come into some issues. I've resolved some of them myself but I'm stuck at the API fetching in reverse geocoding. Apparently, the database is incomplete because it throws me an error at my root access (localhost/) and reverse geocoding isn't working as it's throwing that the place couldn't be found.

I've poked around the databse and places hasn't been found in the tables. Here is the logs :

```
root@ns39147:/home/nominatim-docker# curl "http://localhost:7070/"
<!DOCTYPE html> <html lang="en"> <head> <style> em { font-weight: bold; font-family: monospace; color: #e00404; background-color: #ffeaea; } </style> </head> <body>

Internal Server Error
    <p>Nominatim has encountered an internal error while accessing the database.
       This may happen because the database is broken or because of a bug in
       the software.</p>



<h3>Details</h3>

Database query failed

<p>
    If you feel this error is incorrect feel file an issue on
    <a href="https://github.com/openstreetmap/Nominatim/issues">Github</a>.

    Please include the error message above and the URL you used.
</p>
</body> </html>
```

In the docker :

```
postgres=# \c nominatim
You are now connected to database "nominatim" as user "postgres".
nominatim=# \dt
               List of relations
 Schema |       Name        | Type  |   Owner
--------+-------------------+-------+-----------
 public | country_name      | table | nominatim
 public | country_osm_grid  | table | nominatim
 public | gb_postcode       | table | nominatim
 public | place_boundingbox | table | nominatim
 public | spatial_ref_sys   | table | nominatim
 public | us_postcode       | table | nominatim
(6 rows)

```

For info I'm using nominatim-docker  3.4 which uses postgres 11 and postgis 2.5. The OSM files I've used are from geofabrik : Nord-pas-de-calais (a region of France), Monaco, and Finland. All don't work. The only modifications I've done can be found there : 
https://github.com/mediagis/nominatim-docker/pull/108
https://github.com/mediagis/nominatim-docker/pull/109

My question is : what am I missing to get the reverse geocoding API to work ?

Thanks for your help :)

**Comment by UntitleDude** [comment]
Removing my change in #108 still gives me incomplete database. It looks like the functions and first tables (before the Load data in init.sh) are not created (they're not logged on my screen).

However 3.0 works fine, the database is complete with Monaco, I'll try with other regions.

**Comment by mtmail** [comment]
@UntitleDude Also have a look at the new https://github.com/mediagis/nominatim-docker/pull/103 script if you're unsure the import and table setup finished.

**Comment by UntitleDude** [comment]
@mtmail Thanks a lot, I'll check this out :)
