### ISSUE TITLE
Licence information is not available.

### ISSUE THREAD

**Issue by KALLUNA1** [mediagis/nominatim-docker#111]
I want to use this Docker image in one of my projects, but licence information is not available.
Kindly add the licence information.

**Comment by winsento** [comment]
I think Beerware license. So, what do you think? https://en.m.wikipedia.org/wiki/Beerware

Re #85

**Comment by mtmail** [comment]
It's a good license, but I can't create a PR for it. By the reading of the licence text @winsento would need to write it, provide email and full name. If that's not an option I'd chose CC-0 https://en.m.wikipedia.org/wiki/Public-domain-equivalent_license

**Comment by philipkozeny** [comment]
@winsento CC-0 also sounds good. Can you either write the license file for the Beerware license yourself and add it to the repo or we create the CC-0 license, if that's OK for you?

**Comment by winsento** [comment]
@philipkozeny Hi and thanks for your help. I am hiking in the mountains now and cannot add  license. Let's add CC-0. I agree)

**Comment by philipkozeny** [comment]
Thanks, added the license!
