### ISSUE TITLE
Estimating required disk space

### ISSUE THREAD

**Issue by ballcue** [mediagis/nominatim-docker#114]
Hi,
Is there a way to estimate how much disk space is needed for setting up the database for a given `.osm.pbf` as a function of its size? If so, it would be useful to document in the README. I suspect my DB initialization for `north-america-latest.osm.pbf` fails due to lack of space, but I haven't found a way to know how much space I'll need for it to complete.

Thanks.

**Comment by mtmail** [comment]
The whole world needs 600-700GB so that would be a factor of roughly 10x the (binary) PBF file.
