### ISSUE TITLE
External Postgres

### ISSUE THREAD

**Issue by fjbardelli** [mediagis/nominatim-docker#116]
It is possible to run the server using an external postgres.

**Comment by mtmail** [comment]
The installation creates an extension `nominatim.so`. If you can copy that to the external postgresql server then it should work. Most managed postgresql services (e.g. AWS and such) don't allow custom extension or file system access so it wouldn't be possible there. It's quite a quite advanced setup, finding the correct paths and file permissions on a remote servers (often different between postgresql versions) and I don't think I've seen that packaged in e.g. a docker/docker-compose configuration yet.

**Comment by fjbardelli** [comment]
Thanks I'm going to try this
