### ISSUE TITLE
Cannot Extend Dockerfile with Postgres 

### ISSUE THREAD

**Issue by boginw** [mediagis/nominatim-docker#117]
This might not be the correct forum to ask, and if so, I'll understand if the issue gets closed right away.

I'm currently constructing a Dockerfile which requires a connection to Postgres while building. This is because I will require Photon to later import from the Postgres database.

I extend this repository (that is, the latest version), and manually perform the steps as listed in the README.md of the respective folder. 

```docker
FROM mediagis/nominatim:3.4 as build-nominatim
MAINTAINER Bogi Napoleon Wennerstrøm <bogi.wennerstrom@gmail.com>

RUN mkdir -p /data

# Download Faroe Islands
RUN curl https://download.geofabrik.de/europe/faroe-islands-latest.osm.pbf \
    -o /data/faroe-islands-latest.osm.pbf

# Initialize database and start
RUN cd /app && sh /app/init.sh /data/faroe-islands-latest.osm.pbf postgresdata 4

EXPOSE 5432

# Move generated bins to correct place
RUN rm -rf /var/lib/postgresql/11/main && ln -s /data/postgresdata /var/lib/postgresql/11/main

# start.sh says `service postgresql start` but postgres says:
RUN sudo -u postgres /usr/lib/postgresql/11/bin/pg_ctl -D /var/lib/postgresql/11/main start
RUN psql -U nominatim -h 127.0.0.1 -p 5432 nominatim -c "SELECT 1;"
```

Building the file with `docker build -t test .` produced the following error: 

```bash
psql: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
```

But, if you cut the last two lines of the Dockerfile, and manually run them by first `docker run -it test bash` and then running the lines, then it outputs what is expected: 

```sql
?column? 
----------
        1
(1 row)

```

I don't understand why there's a discrepancy between connecting at build- and run-time. Shouldn't be the same? Is there something I'm missing?

Also, if instead of the second to last line of the Dockerfile you run `service postgresql start` then you'll get a password prompt followed by `psql: FATAL:  password authentication failed for user "nominatim`.

Any help is appreciated.

**Comment by philipkozeny** [comment]
Sorry for the late reply, you could try it again with the latest version 3.6, we have done a lot of changes there which could help!
