### ISSUE TITLE
errorcode 500 via url access

### ISSUE THREAD

**Issue by conect** [mediagis/nominatim-docker#120]
After executing steps 1 to 4 @ https://github.com/mediagis/nominatim-docker/tree/master/3.4
and calling: curl "http://localhost:7070/reverse?format=geojson&lat=somenumber&lon=anothernumber&addressdetails=1"
I receive: 
```
{
   "error" : {
      "code" : 500,
      "message" : "Failed to establish database connection:SQLSTATE[08006] [7] could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?"
   }
}
```
Could anyone help thanks very much

**Comment by philipkozeny** [comment]
- What environment are you using?
- Whats the output of docker ps after 4
- What data did you import?
- Did the log output after step 3 look OK to you?
