### ISSUE TITLE
Cannot build Image because Temporary failure resolving 

### ISSUE THREAD

**Issue by setooc** [mediagis/nominatim-docker#127]
Hi!
We trying to build this image with "docker build -t nominatim .", in any version

Step 5/20 : RUN apt-get -y update -qq &&     apt-get -y upgrade -qq &&     apt-get -y install locales &&     locale-gen en_US.UTF-8 &&     update-locale LANG=en_US.UTF-8 &&     apt-get install -y build-essential cmake g++ libboost-dev libboost-system-dev     libboost-filesystem-dev libexpat1-dev zlib1g-dev libxml2-dev    libbz2-dev libpq-dev libgeos-dev libgeos++-dev libproj-dev     postgresql-server-dev-10 postgresql-10-postgis-2.4 postgresql-contrib-10     apache2 php php-pgsql libapache2-mod-php php-pear php-db     php-intl git curl sudo     python3-pip libboost-python-dev &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* &&     rm -rf /tmp/* /var/tmp/*
 ---> Running in 14983d437ce2

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/cosmic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/cosmic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/cosmic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/cosmic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'locales' has no installation candidate

Cannot find any packeges requirement. I try to change de net with --network=host and i copy my file with DNS configuraton but its not work...

Pls help?

Regards,
IB

**Comment by mtmail** [comment]
This looks like a generic docker issue, not specific to Nominatim etup. Have a look at https://stackoverflow.com/questions/24991136/docker-build-could-not-resolve-archive-ubuntu-com-apt-get-fails-to-install-a

**Comment by setooc** [comment]
but with another containers dont happend, and the docker pull is work. The packages requeriments is correct? in a clean instalation in ubuntu, and i run apt install locales its the same

**Comment by mtmail** [comment]
Please test inside the docker container if the DNS resolution, e.g. to www.example.com works. The stackoverflow page has examples of tools you can use.

Which image or Dockerfile exactly are you trying to build? I see the error message says "cosmic" as Ubunto release and I only see that in the old https://github.com/mediagis/nominatim-docker/blob/master/3.2/Dockerfile Try building the latest version of Nominatim (3.5).

**Comment by mtmail** [comment]
http://archive.ubuntu.com/ubuntu/dists/cosmic/InRelease No longer exists. I think that's because cosmic (Ubuntu 18.10) is no longer supported https://ubuntu.com/about/release-cycle Not sure if that would cause a 'temporary resolving' error, I would expect a page-not-found or such.

**Comment by setooc** [comment]
In this case is  missin this packages. It is correct this apt install ??

root@slnxdock01 3.5]# docker build -t nominatim .
Sending build context to Docker daemon 17.41 kB

Step 1/21 : FROM ubuntu:focal
 ---> 74435f89ab78
Step 2/21 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 2e349a53c9ee
Step 3/21 : ENV LANG C.UTF-8
 ---> Using cache
 ---> f7182a9f3347
Step 4/21 : COPY 80proxy /etc/apt/apt.conf.d/
 ---> Using cache
 ---> 5766b48ddbe7
Step 5/21 : RUN apt-get -y update -qq &&     locale-gen en_US.UTF-8 &&     update-locale LANG=en_US.UTF-8 &&     apt-get install -o APT::Install-Recommends="false" -o APT::Install-Suggests="false" -y     build-essential cmake g++ libboost-dev libboost-system-dev     libboost-filesystem-dev libexpat1-dev zlib1g-dev     libbz2-dev libpq-dev libproj-dev     postgresql-server-dev-12 postgresql-12-postgis-3     postgresql-contrib postgresql-12-postgis-3-scripts     apache2 php php-pgsql libapache2-mod-php     php-intl python3-setuptools python3-dev python3-pip     python3-psycopg2 python3-tidylib git curl sudo &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* &&     rm -rf /tmp/* /var/tmp/*
 ---> Running in 34fc9668bb57

/bin/sh: 1: locale-gen: not found
The command '/bin/sh -c apt-get -y update -qq &&     locale-gen en_US.UTF-8 &&     update-locale LANG=en_US.UTF-8 &&     apt-get install -o APT::Install-Recommends="false" -o APT::Install-Suggests="false" -y     build-essential cmake g++ libboost-dev libboost-system-dev     libboost-filesystem-dev libexpat1-dev zlib1g-dev     libbz2-dev libpq-dev libproj-dev     postgresql-server-dev-12 postgresql-12-postgis-3     postgresql-contrib postgresql-12-postgis-3-scripts     apache2 php php-pgsql libapache2-mod-php     php-intl python3-setuptools python3-dev python3-pip     python3-psycopg2 python3-tidylib git curl sudo &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* &&     rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 127

**Comment by mtmail** [comment]
The output looks different from https://github.com/mediagis/nominatim-docker/blob/master/3.5/Dockerfile

In the Dockerfile there is `apt-get -y install locales && ` already as part of the installation. In our output I don't see that line.

**Comment by philipkozeny** [comment]
Closing the issue for now, please try the latest version (3.6 at the moment), there have been a lot of changes / fixes, thanks!
