### ISSUE TITLE
Error with apache web in docker 

### ISSUE THREAD

**Issue by setooc** [mediagis/nominatim-docker#129]
Hi !

I followed the steps for docker installation, and i have this error

In docker logs

2020-06-30 14:08:04.724 UTC [21] LOG: aborting any active transactions
2020-06-30 14:08:04.741 UTC [21] LOG: background worker "logical replication launcher" (PID 28) exited with exit code 1
2020-06-30 14:08:04.744 UTC [23] LOG: shutting down
2020-06-30 14:08:04.817 UTC [21] LOG: database system is shut down
2020-06-30 14:18:07.807 UTC [21] LOG: starting PostgreSQL 12.2 (Ubuntu 12.2-4) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-8ubuntu1) 9.3.0, 64-bit
2020-06-30 14:18:07.815 UTC [21] LOG: listening on IPv4 address "0.0.0.0", port 5432
2020-06-30 14:18:07.816 UTC [21] LOG: listening on IPv6 address "::", port 5432
2020-06-30 14:18:07.860 UTC [21] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-06-30 14:18:08.016 UTC [22] LOG: database system was shut down at 2020-06-30 14:08:04 UTC
2020-06-30 14:18:08.152 UTC [21] LOG: database system is ready to accept connections
2020-06-30 14:25:23.583 UTC [74] www-data@nominatim FATAL: role "www-data" does not exist
2020-06-30 14:25:45.118 UTC [75] www-data@nominatim FATAL: role "www-data" does not exist

In browser

Failed to establish database connection:SQLSTATE[08006] [7] FATAL: role "www-data" does not exist
If you feel this error is incorrect feel file an issue on Github. Please include the error message above and the URL you used.

I run this commands:

docker run -t -v $PWD:/data nominatim sh /app/init.sh /data/argentina-latest.osm.pbf postgresdata 4
and then
docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim -v $PWD/postgresdata:/var/libpostgresql/12/main nominatim bash /app/start.sh

Pls help!

Regards
IB

**Comment by mtmail** [comment]
https://github.com/mediagis/nominatim-docker/blob/master/3.5/init.sh contains `createuser -SDR www-data` so the user should've been created in the database.

It the /app/init.sh print any errors? 

Can you run to check if the import finished?
```
docker exec -it nominatim sudo -u postgres ./src/build/utils/check_import_finished.php
```

**Comment by lhopki01** [comment]
I encountered this error too.  The issue seems to be a that the init script starts postgres with these lines

```
sudo -u postgres /usr/lib/postgresql/12/bin/initdb -D /data/$PGDIR && \
sudo -u postgres /usr/lib/postgresql/12/bin/pg_ctl -D /data/$PGDIR start && \
```
But the start script starts postgres with this line
```
service postgresql start
```
Which uses the default data dir from `/etc/postgresql/12/main/postgresql.conf` of `/var/lib/postgresql/12/main`.

I think the config file needs to be edited as part of the setup or the start command changed.

**Comment by Bdthomson** [comment]
Unsure why this is happening but I was running into the exact same issue. Downgrading to 3.4 works flawlessly.

**Comment by buchmui** [comment]
Same here (with 3.5), build is ok, runtime not:

```
root@postgres:~/nominatim-docker/3.5# docker logs nominatim
 * Starting PostgreSQL 12 database server
 * Error: Config owner (postgres:101) and data owner (root:0) do not match, and config owner is not root
   ...fail!
 * Starting Apache httpd web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
 *
```

Starting Postgres within the container, is working:
```
root@710ea0d5a8cc:/app# service postgresql start
 * Starting PostgreSQL 12 database server

root@710ea0d5a8cc:/app# netstat -antlp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      -
tcp        0      0 172.17.0.3:46004        91.189.88.142:80        TIME_WAIT   -
tcp        0      0 172.17.0.3:38724        91.189.88.152:80        TIME_WAIT   -
tcp        0      0 172.17.0.3:38728        91.189.88.152:80        TIME_WAIT   -
tcp6       0      0 :::5432                 :::*                    LISTEN      -


root@710ea0d5a8cc:/app# service postgresql status
12/main (port 5432): online


```

**Comment by UntitleDude** [comment]
I have dug [this similar issue with a working solution](https://stackoverflow.com/a/50344823) on this case. After (re- ?) assigning postgres to the database I could use it.

**Comment by philipkozeny** [comment]
We've changed quite a lot with the latest releases (3.6 & 3.7). You can check the latest version out and give us feedback, the problem should be fixed.
