### ISSUE TITLE
3.1 build failed

### ISSUE THREAD

**Issue by sromano1992** [mediagis/nominatim-docker#132]
Hi to all,
I was not able to build the 3.1 nominatim version because of the following issue:

"RuntimeError: Python 3.3 or larger required."

I was able to find the solution and I would like to contribute with my updates.

Can you add me as a contributor?

Thanks in advance

**Comment by mtmail** [comment]
Can you fork and create a pull-request? Any reason you use Nominatim version 3.1, not the recent 3.5?

**Comment by sromano1992** [comment]
Hi,
I forked/fixed and created the pull-request.

I used the 3.1 in the past and I needed to reinstall the same version because of application requirements.

**Comment by philipkozeny** [comment]
Thanks, this was closed with the merge of https://github.com/mediagis/nominatim-docker/pull/134
