### ISSUE TITLE
FATAL: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by soyfrien** [mediagis/nominatim-docker#136]
```
Internal Server Error
Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software.

Details
Failed to establish database connection:SQLSTATE[08006] [7] FATAL: remaining connection slots are reserved for non-replication superuser connections
If you feel this error is incorrect feel file an issue on Github. Please include the error message above and the URL you used.
```

Is there a .conf file I can edit to increase this? Or is there anyway to increase it? Trying to help @bensilver95 crunch a large dataset with your project and keep overwhelming the container, even though it has 32 cores and 192 GB of RAM. Disk IO is non-factor.

**Comment by mtmail** [comment]
You can set a higher `max_connections` in the postgresql configuration, on Ubuntu located in `/etc/postgresql/12/main/postgresql.conf`, default is 100.

**Comment by ppdac** [comment]
Sorry to leave open. I am not tester, but have made the change to `10000` . Too high?
