### ISSUE TITLE
Git Repo no longer exists

### ISSUE THREAD

**Issue by hiasel** [mediagis/nominatim-docker#14]
I just tried to build this via docker.
This command `RUN git clone --recursive git://github.com/twain47/Nominatim.git ./src` is failing with:

> fatal: unable to connect to github.com:
> github.com[0: 192.30.253.112]: errno=Connection refused
> github.com[1: 192.30.253.113]: errno=Connection refused

I've just found out that the repository was moved.
See: https://github.com/openstreetmap/Nominatim/commit/a52455f1604e5d3233315603da4a14f5b2608319

**Comment by timnon** [comment]
had the same problem, this fixed it for me: 2e003820aec010a23df6a6eb455693e554bc3591
already in the actual Dockerfile

**Comment by hiasel** [comment]
@timnon thanks, I've just successfully built nominatim with the updated URL.
Everything works.
