### ISSUE TITLE
Incorrect postcode attribution for roads

### ISSUE THREAD

**Issue by DuncanMackintosh** [mediagis/nominatim-docker#140]
Running a clean docker image from 3.5 and importing UK OSM data produces some roads with incorrectly assigned Computed Postcode values compared to the publicly available OSM nominatim instance.

For a quick example, lincolnshire-latest from geofabrik includes OSM Way ID 22763472. From nominatim.openstreetmap.org this has a computed postcode of LN6 9HU (google and OSM both believe this to be the correct postcode); a local instance assigns it the postcode LN6 9LU which is approximately a kilometre away.

The selected address data is the same, but the nominatim database also has extra rows not present in the local instance.

Nomimatim.openstreetmap.org:
![image](https://user-images.githubusercontent.com/4966417/93201329-f185b880-f748-11ea-8ce5-4a5b05604edd.png)
![image](https://user-images.githubusercontent.com/4966417/93201344-f5b1d600-f748-11ea-80ee-c6741d423ba8.png)

Local instance:
![image](https://user-images.githubusercontent.com/4966417/93201363-fc404d80-f748-11ea-9856-3cf1e968e01f.png)
![image](https://user-images.githubusercontent.com/4966417/93201373-ffd3d480-f748-11ea-9738-5de3e4a4e149.png)

Note that a full UK import produces the same output, using the smaller lincolnshire PBF is just a quicker import to reproduce the issue.

Obviously this could be an upstream nominatim issue, but I'm starting here as this is where I can reproduce it consistently. I've also seen similar errors on other roads from trying to manually install a local nominatim server and switching to the docker instance fixed those, so there's definitely some weirdness in local environments that can cause this kind of problem.

**Comment by mtmail** [comment]
Nominatim install instructions have a step importing for US and GB postcodes (1.7 million records, but Northern Ireland is not in the dataset) http://nominatim.org/release-docs/latest/admin/Import-and-Update/#downloading-additional-data

The Docker image doesn't do the step during the installation.

"Importing separately after the initial import" on http://nominatim.org/release-docs/latest/data-sources/GB-Postcodes/ might help or adding the step into your local Dockerfile.

**Comment by DuncanMackintosh** [comment]
Ahh! That explains an awful lot. Thanks for the pointers.

I couldn't get the post-install import working but adding a wget line to the dockerfile worked a treat.

Would it be worthwhile me adding a pull request to mention this in the installation instructions and/or add some commented-out lines to the Dockerfile to make it easier?
