### ISSUE TITLE
Json format for great britain ( looking manchester coordinates) error

### ISSUE THREAD

**Issue by s0240917** [mediagis/nominatim-docker#145]
Hi 
Thanks 
for me using this 
curl http://localhost:7070/reverse?lon=-2.1597&lat=53.4077891&format=json
[1] 4032
[2] 4033
ubuntu@ip~$ <?xml version="1.0" encoding="UTF-8" ?>
<error>
    <code>400</code>
    <message>Need coordinates or OSM object to lookup.</message>
    </error>

But in Nominatim
https://nominatim.openstreetmap.org/reverse?lon=-2.160243&lat=53.407901&format=json

Output:
{"place_id":66009768,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"node","osm_id":5709815268,"lat":"53.4077891","lon":"-2.1597388","display_name":"Premier, Wellington Street, Grand Central, Portwood, Stockport, Greater Manchester, North West England, England, SK1 3RP, United Kingdom","address":{"shop":"Premier","road":"Wellington Street","retail":"Grand Central","suburb":"Portwood","town":"Stockport","county":"Greater Manchester","state_district":"North West England","state":"England","postcode":"SK1 3RP","country":"United Kingdom","country_code":"gb"},"boundingbox":["53.4077391","53.4078391","-2.1597888","-2.1596888"]}

why i am getting this error

**Comment by mtmail** [comment]
`&` is a special character on the command line.

Try putting quotes around the URL
`curl "http://localhost:7070/reverse?lon=-2.1597&lat=53.4077891&format=json"`

**Comment by s0240917** [comment]
> `&` is a special character on the command line.
> 
> Try putting quotes around the URL
> `curl "http://localhost:7070/reverse?lon=-2.1597&lat=53.4077891&format=json"`

Thanks @mtmail 
i missed the quotes
