### ISSUE TITLE
Provide a smart entrypoint to automatize most operations

### ISSUE THREAD

**Issue by madmath03** [mediagis/nominatim-docker#147]
In order to easily use this docker image in a production environment, it would need to have generic entrypoint that could manage the most (if not all) the operations of the README automatically.

I might be able to provide a PR for that.

**Comment by philipkozeny** [comment]
Sounds great, a PR for that would be nice!

**Comment by madmath03** [comment]
For info, I developed a docker image for my company that provide this feature: https://github.com/Monogramm/docker-nominatim

We've been testing it for some weeks now and it works pretty well.
As soon as I find the time.... I will try to send a PR that match this official image.

**Comment by philipkozeny** [comment]
We've managed to provide that now with https://github.com/mediagis/nominatim-docker/pull/183, see https://github.com/mediagis/nominatim-docker/blob/master/3.6/README.md. Thanks for your input
