### ISSUE TITLE
Initializing error

### ISSUE THREAD

**Issue by cmaraisEA** [mediagis/nominatim-docker#149]
![image](https://user-images.githubusercontent.com/59736282/95561951-c0349b80-0a1b-11eb-8821-dd09be81fa93.png)

I have the following issue when trying to initialize the database

**Comment by philipkozeny** [comment]
It seems like the path to your local directory is broken. 

Windows is using backslashes instead of a slash when referencing folders, so try:

```-v C:\docker\:/data```

**Comment by philipkozeny** [comment]
Closing the issue now since it's stale. If this doesn't fix you problem just reopen the issue, happy to help!
