### ISSUE TITLE
database get erased (?) when importing more than 1 file

### ISSUE THREAD

**Issue by kaplandani** [mediagis/nominatim-docker#155]
I've created the container using this command:
docker build --pull --rm -t nominatim --build-arg with_postcodes_us=1 --build-arg with_postcodes_gb=1 .

imported NA db:
docker run -t -v /home/osm/data/:/data nominatim  sh /app/init.sh /data/north-america-latest.osm.pbf postgresdata 48

run the continaer: 
docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim -v /home/osm/data/postgresdata:/var/lib/postgresql/12/main nominatim bash /app/start.sh

checked a NY address --> Good.

stopped the container: 
docker stop nominatim
run another import:

docker run -t -v /home/osm/data/:/data nominatim  sh /app/init.sh /data/south-america-latest.osm.pbf postgresdata 36

start the container:
docker start nominatim

/ 20201028160316
// http://XX.XX.XX.XX:7070/reverse.php?format=json&lat=40.706005&lon=-74.008827

{
  "error": "Unable to geocode"
}

but now South America works:

// 20201028160959
// http://51.222.82.79:7070/reverse.php?format=json&lat=-33.45694&lon=-70.64827

{
  "place_id": 1794712,
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "way",
  "osm_id": 112584232,
  "lat": "-33.4567821",
  "lon": "-70.6482563",
  "display_name": "1030, Coquimbo, Barrio Franklin, Santiago, Provincia de Santiago, Santiago Metropolitan Region, 8330843, Chile",
  "address": {
    "house_number": "1030",
    "road": "Coquimbo",
    "neighbourhood": "Barrio Franklin",
    "city": "Santiago",
    "county": "Provincia de Santiago",
    "state": "Santiago Metropolitan Region",
    "postcode": "8330843",
    "country": "Chile",
    "country_code": "cl"
  },
  "boundingbox": [
    "-33.4568321",
    "-33.4567321",
    "-70.6483063",
    "-70.6482063"
  ]
}

**Comment by philipkozeny** [comment]
This is the intended behaviour. Nominatim does not support "just" adding more than one import file to add more countries. To import multiple countries you would have to follow the official docs: https://nominatim.org/release-docs/latest/admin/Advanced-Installations/#importing-multiple-regions
