### ISSUE TITLE
Https Support for Nominatim

### ISSUE THREAD

**Issue by AnithaVedhan** [mediagis/nominatim-docker#159]
Hi,

Can you please provide with steps to make this API available over https?

**Comment by AnithaVedhan** [comment]
Hi Team,
CAn you please share updated docker file to add SSL certificates and enable Https for nonminatim?

**Comment by philipkozeny** [comment]
You would need to place a Webserver as a reverse proxy in front of the nomination installation. 

This could be a nginx, apache, whatever server setup to your specific needs with SSL certificates etc. If you don't have experience with that I would recommend caddy (https://caddyserver.com) as a Webserver on your system. The caddyconfig file therefore would be something super simple like

```
{
    email your@email.com
}

your.public-domain.com {
    reverse_proxy 127.0.0.1:7070
}

```
