### ISSUE TITLE
Postgresql.conf can it be set before database import in docker. 

### ISSUE THREAD

**Issue by xfasterx** [mediagis/nominatim-docker#163]
I was able to import smaller countries without any problem. But now im trying to install  europe-latest.osm.pbf nominatim for reverse geo-coding only.

From this manual i read about setting Postgresql.conf before the import process starts to adjust it to the system specifications.

https://nominatim.org/release-docs/latest/admin/Installation/#tuning-the-postgresql-database

Tuning the PostgreSQL database
You might want to tune your PostgreSQL installation so that the later steps make best use of your hardware. You should tune the following parameters in your postgresql.conf file.

shared_buffers = 2GB
maintenance_work_mem = (10GB)
autovacuum_work_mem = 2GB
work_mem = (50MB)
effective_cache_size = (24GB)
synchronous_commit = off
checkpoint_segments = 100 # only for postgresql <= 9.4
max_wal_size = 1GB # postgresql > 9.4
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9

I would like to configure Postgresql.conf but i see that the below install process automaticly creates the Postgresql.conf in the postgresdata/ dir with much lower values when the import starts. 

I start the import with docker run -t -v /home/myhome/nominatimdata:/data nominatim  sh /app/init.sh /data/europe-latest.osm.pbf postgresdata 16

The process starts / creates the default Postgresql.conf, which i can see afterwards in the /home/myhome/nominatimdata/postgresdata/ directory. 

Unfortunately on my virtualbox where i run the import process, crashes. Possibly not enough RAM (50 gb assigned). Ordered 64 gb extra to see if that will help. I can only restart the process to import europe-latest.osm.pbf when i remove the /nominatimdata/postgresdata/ directory and start the process again with docker run -t -v /home/myhome/nominatimdata:/data nominatim  sh /app/init.sh /data/europe-latest.osm.pbf postgresdata 16

So i am confused. could i configure the Postgresql.conf before the process starts and that the docker process uses that edited Postgresql.conf instead of the Postgresql.conf that it creates automaticly in  /nominatimdata/postgresdata/ ?

Could the fact that Postgresql.conf is not configured also be a reason for crashing ?

Expect to receive the extra RAM tomorrow and will post my findings. 

Thanks for helping out!

**Comment by xfasterx** [comment]
After installing 64 GB extra the server has 128 GB and the import installed without any issue. it took a bit longer then expected (about 21 hours for the europe-latest.osm.pbf). But i expect the reason for this is the unoptimized postgresql.conf

**Comment by philipkozeny** [comment]
https://github.com/mediagis/nominatim-docker/pull/196 allows to config the PostgreSQL settings now with the latest 3.6 - thanks for your input!
