### ISSUE TITLE
Space implosion and still not prepared - Europe import

### ISSUE THREAD

**Issue by Azbesciak** [mediagis/nominatim-docker#164]
Hello, I made an Europe import... or at least tried to.
I reserved 512 GB on Azure for it.
Unfortunately, it took above 4 days, and after stage 30, which required 483 GB (to remind - Europe OSM takes ~23 GB...) It failed some hours later because of no more space available for import.
And it is quite strange because as you wrote in https://github.com/mediagis/nominatim-docker/issues/114 whole planet takes 600-700 GB.
To say more, I fired off that what it produced... and the result is very unsatisfactory (reverse; red - clicked, blue - returned. Search does not work at all)
![image](https://user-images.githubusercontent.com/17334466/102744322-dd5de280-4359-11eb-8eb5-03a527448446.png).
And my question is - what the hell? Even in [the Nominatim docs](https://nominatim.org/release-docs/latest/admin/Installation/) it is written that the whole planet required >900 GB (I know that 2TB is also >900gb) but it is a big difference.

I am using the latest 3.5 image (mediagis/nominatim:3.5)

**Comment by philipkozeny** [comment]
This repo is to provide a way to run nominatim in a docker container, if you want to report bugs concerning the search results etc. you have to do that in the Nominatim project itself (https://github.com/osm-search/Nominatim). I would try to reimport the data just for the country you have been testing and try to take a look if the results still fail.

Taking several days + hundreds of GB of data for Europe is normal. The latest estimations are in the official Nominatim doc.
