### ISSUE TITLE
Nominatim Database Initialization fails Error: "logical replication launcher" (PID 34) exited with exit code 1

### ISSUE THREAD

**Issue by BeamerIsHere** [mediagis/nominatim-docker#166]
I'm trying to run 3.5 in docker by following the README instructions but unable to complete step 3 ( Initialize Nominatim Database)
It fails each time when I run `docker run -t -v /opt/nfs01/admin/osm:/data nominatim  sh /app/init.sh /data/utah-latest.osm.pbf postgresdata 3`. In the error I can see it says ` received fast shutdown request`.
 

- Error : 
```Checking search indices are valid ... OK
waiting for server to shut down...2021-01-11 13:41:30.922 UTC [27] LOG:  received fast shutdown request
.2021-01-11 13:41:30.925 UTC [27] LOG:  aborting any active transactions
2021-01-11 13:41:30.929 UTC [27] LOG:  background worker "logical replication launcher" (PID 34) exited with exit code 1
2021-01-11 13:41:31.040 UTC [29] LOG:  shutting down
2021-01-11 13:41:31.706 UTC [27] LOG:  database system is shut down
 done```

- I can still start the Nominatim container but localhost:7070 says internal server error ( see the image below). What could be the reason behind this Postgress error? 
@philipkozeny any thoughts?




![Capture](https://user-images.githubusercontent.com/42833377/104200757-09e3b680-544f-11eb-9361-987bd07f2850.JPG)

**Comment by DanwithArduino** [comment]
Looks like this is the same as https://github.com/mediagis/nominatim-docker/issues/169

**Comment by philipkozeny** [comment]
Whats the output above the error? This seems like its just how the container is stopped after the import is finished. After that you have to start the container again with

`docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim -v /home/me/nominatimdata/postgresdata:/var/lib/postgresql/12/main nominatim bash /app/start.sh
`

Also please try the version 3.6, we did some huge upgrades there and you can do the import / running of the container with a single command, way easier!

**Comment by philipkozeny** [comment]
We've changed quite a lot with the latest releases (3.6 & 3.7). You can check the latest version out and give us feedback, the problem should be fixed.
