### ISSUE TITLE
GeoFabrik Country Updates

### ISSUE THREAD

**Issue by AnithaVedhan** [mediagis/nominatim-docker#167]
How to do country updates if incase there is no internet connection at actual site? Should we download the .pdf manually and repeat the installation again with new container?

**Comment by mtmail** [comment]
Regular full installation are the easiest approach.

If you want to update the data it's more complex and I'm not aware anybody had reported this use-case:

Let's say you downloaded the http://download.geofabrik.de/europe/monaco-latest.osm.pbf and your `settings/local.php` contains `@define('CONST_Replication_Url', 'http://download.geofabrik.de/europe/monaco-updates');`

The script `utils/update.php --check-for-updates` can tell you the latest sequence number in the database, e.g. 2830. The also tries to find the latest sequence on the geofabrik server, that might fail without internet connection. You can see the latest sequence number at http://download.geofabrik.de/europe/monaco-updates/state.txt It gets updated once per day.

The script for updating
https://nominatim.org/release-docs/3.5.0/admin/Import-and-Update/#updates
also expect a working internet connection.

What you could do is download all files with same directory structure and with the `state.txt` from http://download.geofabrik.de/europe/monaco-updates/ and serve with a webserver on a local HTTP port, then set `settings/local.php` to point to the local webserver.

geofabrik server has daily update data for the last 3 months. If the data in your database is older than this approach doesn't work. For large countries or whole continents a full reinstall/reimport will be faster than trying to applying 100 daily updates.
