### ISSUE TITLE
Error: The cluster is owned by user id 1000 which does not exist

### ISSUE THREAD

**Issue by wjossowski** [mediagis/nominatim-docker#168]
Hiho

I'm trying to run Nominatim v3.5 with `postgresdata` from backup and I am facing following Postgres problem on startup:

Command
```
docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim -v /home/myuser/mydir/postgresdata:/var/lib/postgresql/12/main mediagis/nominatim:3.5 bash /app/start.sh
```

Output:
```
Missing argument in printf at /usr/bin/pg_lsclusters line 130.
 * Starting PostgreSQL 12 database server
 * Error: The cluster is owned by user id 1000 which does not exist
   ...fail!
 * Starting Apache httpd web server apache2
```

Service status on container:
```
root@480dee927080:/app# service postgresql status
Missing argument in printf at /usr/bin/pg_lsclusters line 130.
12/main (port 5432): down
```

Seems that there's an error with user management on Postgres service startup, so Postgres is down.

**Comment by wjossowski** [comment]
Okay, I've found that `init.sh` is running chown on entire `postgresdata` directory for `postgres` user:

`chown postgres:postgres /data/$PGDIR && \`

I applied  that changes on running container and re-started postgres service:
```
docker exec -it nominatim /bin/bash
sudo chown -R postgres:postgres /var/lib/postgresql/12/main # on container
service postgresql start
```

But I suggest that that `chown` should be called in `start.sh` or at least enabled by flags.
That would ease the migration process of dumped `postgresql` data.

**Comment by philipkozeny** [comment]
We've changed quite a lot with the latest releases (3.6 & 3.7). You can check the latest version out and give us feedback, the problem should be fixed.

**Comment by novotnej** [comment]
@philipkozeny I am not sure it has been fixed - I ran into the same issue in an EC2 instance on AWS...

**Comment by philipkozeny** [comment]
> @philipkozeny I am not sure it has been fixed - I ran into the same issue in an EC2 instance on AWS...

Do you have more details? What Nominatim Version, image, etc.? Thanks!

**Comment by novotnej** [comment]
`docker run -it --shm-size=1g   -e PBF_PATH=/nominatim/pbf/planet-latest.osm.pbf   -e REPLICATION_URL=https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/replication/day/   -e IMPORT_WIKIPEDIA=true   -e NOMINATIM_PASSWORD=XXXXXXXX -v /mnt/efs/nominatim-pbf:/nominatim/pbf -v /mnt/efs/nominatim-data:/var/lib/postgresql/12/main -p 8080:8080  --name nominatim  mediagis/nominatim:3.7`


Docker version 20.10.4, build d3cb89e


`+ trap stopServices TERM
+ /app/config.sh
+ id nominatim
+ useradd -m -p XXXXXXX nominatim
+ IMPORT_FINISHED=/var/lib/postgresql/12/main/import-finished
+ '[' '!' -f /var/lib/postgresql/12/main/import-finished ']'
+ /app/init.sh
+ OSMFILE=/nominatim/data.osm.pbf
+ '[' true = true ']'
+ echo 'Downloading Wikipedia importance dump'
Downloading Wikipedia importance dump
+ curl https://www.nominatim.org/data/wikimedia-importance.sql.gz -o /nominatim/wikimedia-importance.sql.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  375M  100  375M    0     0  49.6M      0  0:00:07  0:00:07 --:--:-- 52.0M
+ '[' '' = true ']'
+ echo 'Skipping optional GB postcode import'
Skipping optional GB postcode import
+ '[' '' = true ']'
+ echo 'Skipping optional US postcode import'
Skipping optional US postcode import
+ '[' '' '!=' '' ']'
+ '[' /nominatim/pbf/planet-latest.osm.pbf '!=' '' ']'
+ echo Reading OSM extract from /nominatim/pbf/planet-latest.osm.pbf
Reading OSM extract from /nominatim/pbf/planet-latest.osm.pbf
+ OSMFILE=/nominatim/pbf/planet-latest.osm.pbf
+ '[' '!' -f /var/lib/postgresql/12/main/PG_VERSION ']'
+ sudo service postgresql start
 * Starting PostgreSQL 12 database server * Error: The cluster is owned by group id 1001 which does not exist
                                                                                                                                                                    [fail]
+ sudo -u postgres createuser -s nominatim
createuser: error: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ sudo -u postgres createuser -SDR www-data
createuser: error: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ chown -R nominatim:nominatim /nominatim
+ cd /nominatim
+ sudo -E -u nominatim nominatim import --osm-file /nominatim/pbf/planet-latest.osm.pbf --threads 16
2021-07-22 12:16:46: Using project directory: /nominatim
2021-07-22 12:16:46: Creating database
createdb: error: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2021-07-22 12:16:46: FATAL: Creating new database failed.`

**Comment by philipkozeny** [comment]
Thanks will look into it, also @leonardehrenfried any ideas?

**Comment by leonardehrenfried** [comment]
What are the contents of `/mnt/efs/nominatim-data` on the host?

It seems that it already contains a file called PG_VERSION. If this file already exists we don't change the ownership of the postgres folder: https://github.com/mediagis/nominatim-docker/blob/master/3.7/init.sh#L36-L40

Does it perhaps contain the remains of a failed import attempt?

**Comment by leonardehrenfried** [comment]
And what happens when you use a named mount `-v nominatim-data:/var/lib/postgresql/12/main` rather than a bind mount?

**Comment by leonardehrenfried** [comment]
It appears that you don't have problem anymore, @novotnej, therefore I'm closing this.

Please reopen if it still persists.
