### ISSUE TITLE
How do you guys make HTTPS/TLS available for the Docker solution?

### ISSUE THREAD

**Issue by herculan0** [mediagis/nominatim-docker#172]
We are using the nominatim 3.5
Trying to make a new container with nginx to listen on 443 and redirect to the port 80 on the host but without success until now.

Can someone give me some tips to look for while trying to do this works?

**Comment by philipkozeny** [comment]
Do you have any specific errors?

I am using nginx and this is the `.conf` file I am using as an example:

```
server {
    listen 80;
    server_name my.domain.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name my.domain.com;

    ssl_certificate /etc/letsencrypt/live/my.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my.domain.com/privkey.pem;

    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=63072000" always;

    # logging
    access_log /var/log/nginx/my.domain.com.access.log;
    error_log /var/log/nginx/my.domain.com.error.log warn;

    location / {
	include /etc/nginx/conf.d/private-ips.conf;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
        proxy_pass http://10.0.1.251:7070;
    }
}
```

You're writing that you are redirecting to the port 80. Do you run the image also with the adapted command to expose it to the port 80 or did you copy/paste the run command from the Docs? In that case we expose the port to 7070 on the host (see my example above).
