### ISSUE TITLE
Question: Help with creating a slimmed down version

### ISSUE THREAD

**Issue by Vicharian** [mediagis/nominatim-docker#173]
I need some config help. The documentation here is so well organized that I am sure it is already covered somewhere. My lack of knowledge of docker and linux is playing into it, but have some questions.

I am trying to create a planet database for reverse geocoding in docker running on Windows. Have just over 500G left on my computer after downloading the planet.osm.pbf file

On nominatim.org [https://nominatim.org/release-docs/develop/admin/Import/] they say I need a setting '--reverse-only' 
More importantly, I want to '--drop' full and extratags

style | Import time | DB size | after drop
-- | -- | -- | --
admin | 4h | 215 GB | 20 GB
street | 22h | 440 GB | 185 GB
address | 36h | 545 GB | 260 GB
full | 54h | 640 GB | 330 GB
extratags | 54h | 650 GB | 340 GB

I have looked at all the files in the nominatim-docker/version folder and none seems to be this file. 

Any pointers will be appreciated.

**Comment by mtmail** [comment]
The link on nominatim.org points to the /develop (git master) documentation. Recently the names of the `setup.php` script changed to `nominatim import`, that is not the stable version.

Make sure what you read is the documentation for the version you're installing, e.g. https://nominatim.org/release-docs/3.5.0/admin/Import-and-Update/ That lists `utils/setup.php` and you will find the same command in the `init.sh` script in this repository.

**Comment by Vicharian** [comment]
Thanks mtmail,

I have this update
`sudo -u nominatim ./src/build/utils/setup.php --drop --reverse-only --osm-file $OSMFILE --all --threads $THREADS && \`

The link you shared asks for setting the `CONST_Import_Style`. In your answer https://github.com/osm-search/Nominatim/issues/1339 you recommend 'In you local build/settings/local.php add a line to overwrite CONST_Import_Style value (default is in settings/default.php).' I assume for nominatim-docker it is the local.php (the one in the same folder as DockerFile). 

I have searched for trying to look for sample / examples of this file but still do not know how to set the value.

Is is something like
` @define('CONST_Import_Style.extratags', 'drop');  `

**Comment by mtmail** [comment]
The `setup.php` line in your last comment looks alright.

Configuration setting also changed recently (https://github.com/osm-search/Nominatim/pull/2115). If you browse the source for the stable version 3.5 https://github.com/osm-search/Nominatim/tree/3.5.x/settings it will be more clear.

In your `local.php` set or add `@define('CONST_Import_Style', CONST_BasePath.'/settings/ import-extratags.style');`

**Comment by mtmail** [comment]
In the docker `init.sh` file the `check_import_finished.php` line will likely fail. The script didn't handle imports that used `--drop` correctly. Fixed in https://github.com/osm-search/Nominatim/pull/2119 which wasn't part of Nominatim 3.5 yet. It's best if you comment that line out and run the command manually later. Also better to test the import with a smaller country first.

**Comment by Vicharian** [comment]
I appreciate you continued help but will `@define('CONST_Import_Style', CONST_BasePath.'/settings/ import-extratags.style');` add the extratags to the database or remove / drop it. I want to exclude that data in order to conserve disk space.

**Comment by mtmail** [comment]
Using `extratags.style` will import more data than the default (full) installation, so you don't want to do that then.

`--drop` will skip creating database tables and indices needed for forward search only, that can save 200GB or more on a planet installation.

**Comment by Vicharian** [comment]
My assumption was that the default import of the planet file would have full and extratags. If so, what should I do to exclude extratags and full styles (or even address style).

**Comment by mtmail** [comment]
nominatim.openstreetmap.org uses `import-extratags.style` which imports more data than needed for geocoding. You can see many extra tags on https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=62782&class=boundary 

Default is `@define('CONST_Import_Style', CONST_BasePath.'/settings/import-full.style');` which is enough for housenumber level geocoding and includes names of railways lines, waterways, point-of-interest (bank, restaurant etc).

For you usecase `import-address.style` could be enough. `import-street.style` doesn't import house-numbers. `import-admin.style` doesn't import streets or housenumbers.

**Comment by Vicharian** [comment]
Thanks for your patient and very helpful comments. So, what you're saying is that these settings are ordinal and I do not have to turn them on or off independently but instead just pick the highest level of detail. In other words, I just need to add the following to `local.php` - `@define('CONST_Import_Style', CONST_BasePath.'/settings/ import-address.style');`. In doing so, I will select that style which subsumes admin & street but excludes full and extratags.

**Comment by DanJamesMills** [comment]
@Vicharian Hi can I ask what spec your server is we are thinking of doing the same.
