### ISSUE TITLE
Version 3.5 issue

### ISSUE THREAD

**Issue by unseenmagik** [mediagis/nominatim-docker#175]
Hi. 
I had the nomination docker all set up and running perfectly.
My server crashed/froze and I needed to reboot the VPS. 
The docker container is still running but I can no longer access anything on localhost:7070
Is there something that needs to be done after a server reboot to get it working again. 
I tried `docker restart nomination` to no avail

**Comment by philipkozeny** [comment]
I would try to stop & rm the running container (`docker stop nominated && docker rm nominatim`) and restart (as you have started it the first time) it after that.

**Comment by unseenmagik** [comment]
I ended up removing the container and re built 3.6. Front end webpage loads but no map now :-(
Only shows `[ ]` on the page in the top left corner. 
Maybe I done something wrong

**Comment by philipkozeny** [comment]
Thats intended, the Nomination team moved the frontend part in 3.6 to a different project, see: https://github.com/mediagis/nominatim-docker/tree/master/3.6#upgrade-from-350-to--360
