### ISSUE TITLE
Importing Wikidata Rankings

### ISSUE THREAD

**Issue by brahica** [mediagis/nominatim-docker#176]
Hi, 

I would like to import wikidata ranking and update my nomination database.
How should I process? 

I find this doc : https://nominatim.org/release-docs/3.5.0/admin/Import-and-Update/#wikipediawikidata-rankings
But when I launch : 

```
sudo docker exec -it nominatim bash
cd /app/src/data
curl  https://www.nominatim.org/data/wikimedia-importance.sql.gz --output wikimedia-importance.sql.gz
php /app/src/utils/setup.php --import-wikipedia-articles
```

I got : 

```
PHP Warning:  Use of undefined constant CONST_BasePath - assumed 'CONST_BasePath' (this will throw an Error in a future version of PHP) in /app/src/utils/setup.php on line 3
PHP Warning:  require_once(CONST_BasePath/lib/init-cmd.php): failed to open stream: No such file or directory in /app/src/utils/setup.php on line 3
PHP Fatal error:  require_once(): Failed opening required 'CONST_BasePath/lib/init-cmd.php' (include_path='.:/usr/share/php') in /app/src/utils/setup.php on line 3
```

I understand it's missing CONST_BasePath but can't found how to process it, help me, thx a lot ;)

**Comment by mtmail** [comment]
The script exists twice, you need `/app/src/build/utils/setup.php` (it's actually a tiny wrapper that set those configuration values and calls `/app/src/utils/setup.php`).

**Comment by brahica** [comment]
@mtmail Thx a lot !

I can launch script after that : 

```
useradd -m -p password1234 nominatim
sudo -u nominatim php /app/src/build/utils/setup.php --import-wikipedia-articles
sudo -u nominatim php /app/src/build/utils/update.php --recompute-importance

```

I am now waiting to see if my results will be updates :)

**Comment by philipkozeny** [comment]
Hope everything worked out, otherwise please reopen the issue! Thanks
