### ISSUE TITLE
Configuration file for database access using separate database and application containers

### ISSUE THREAD

**Issue by rebos** [mediagis/nominatim-docker#177]
I wanted to split my installation of nominatim-docker version 3.6 into two containers: One container for the database and one container for the application. To achieve that I followed [the guide for the version I am using](https://github.com/mediagis/nominatim-docker/tree/master/3.6).

Unfortunately after completing the necessary steps I got this error trying to geocode a place:
`Failed to establish database connection:SQLSTATE[08006] [7] could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?"`

It seems to me that the file "local.php" is not the right place to customize "CONST_Database_DSN" anymore: If I change it in "local.php" it does not have an effect (in my installation). But if I change it within the file "settings-frontend.php" it works!

Can anybody confirm this or might give me a hint what I could have done wrong?

**Comment by mtmail** [comment]
The last step of `setup.php ... -all ...` is `--setup-website` https://nominatim.org/release-docs/3.6.0/appendix/Install-on-Ubuntu-20/#setting-up-a-webserver
That takes the settings and writes the `settings-frontend.php` file (source code at https://github.com/osm-search/Nominatim/blob/v3.6.0/lib/setup/SetupClass.php#L705)

So after changing the `settings/local.php` you need to run `build/utils/setup.php --setup-website` again. Or, as you discovered, manually edit the `setings-frontend.php` file.

This is specific to Nominatim 3.6. Prior versions didn't have that configuration file and configuration filenames and path in future versions are different, too.

**Comment by rebos** [comment]
Thank you for the explanation and the background information!

I edited the script `startapache.sh` in the container and added a call to `setup.php --setup-website`. After restarting my app-only container the settings from my `local.php` were applied to `settings-frontend.php`. Nice!

I will create a pull request as a propsal to get this merged.
