### ISSUE TITLE
PostgresSQL server failed to start

### ISSUE THREAD

**Issue by datasep** [mediagis/nominatim-docker#18]
Hi all, has anyone ran into this issue before? Ideas for workaround?

* Starting PostgreSQL 9.3 database server
 * The PostgreSQL server failed to start. Please check the log output.
   ...fail!
createuser: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
createuser: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
The command '/bin/sh -c service postgresql start &&     sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='nominatim'" | grep -q 1 || sudo -u postgres createuser -s nominatim &&     sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='www-data'" | grep -q 1 || sudo -u postgres createuser -SDR www-data &&     sudo -u postgres psql postgres -c "DROP DATABASE IF EXISTS nominatim" &&     useradd -m -p password1234 nominatim &&     chown -R nominatim:nominatim ./src &&     sudo -u nominatim ./src/utils/setup.php --osm-file /app/src/data.osm.pbf --all --threads 2 &&     service postgresql stop' returned a non-zero code: 1

**Comment by Ericson90** [comment]
Me too having a similar issue at the PostgreSQL.
Anyone know how to fix this ?

Step 18/22 : RUN service postgresql start &&     sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='nominatim'" | grep -q 1 || sudo -u postgres createuser -s nominatim &&     sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='www-data'" | grep -q 1 || sudo -u postgres createuser -SDR www-data &&     sudo -u postgres psql postgres -c "DROP DATABASE IF EXISTS nominatim" &&     useradd -m -p password1234 nominatim &&     chown -R nominatim:nominatim ./src &&     sudo -u nominatim ./src/utils/setup.php --osm-file /app/src/data.osm.pbf --all --threads 2 &&     service postgresql stop
 ---> Running in 3fa191b76163
 * Starting PostgreSQL 9.3 database server
   ...done.
NOTICE:  database "nominatim" does not exist, skipping
DROP DATABASE
Create DB
createdb: database creation failed: ERROR:  could not stat file "base/1/pg_internal.init": No such file or directory
ERROR: Error executing external command: createdb -E UTF-8 -p 5432 nominatim
Error executing external command: createdb -E UTF-8 -p 5432 nominatim
The command '/bin/sh -c service postgresql start &&     sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='nominatim'" | grep -q 1 || sudo -u postgres createuser -s nominatim &&     sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='www-data'" | grep -q 1 || sudo -u postgres createuser -SDR www-data &&     sudo -u postgres psql postgres -c "DROP DATABASE IF EXISTS nominatim" &&     useradd -m -p password1234 nominatim &&     chown -R nominatim:nominatim ./src &&     sudo -u nominatim ./src/utils/setup.php --osm-file /app/src/data.osm.pbf --all --threads 2 &&     service postgresql stop' returned a non-zero code: 255

**Comment by sfranchois** [comment]
Any follow-up on this? I get the same error as Ericson90. Not sure if this is the same issue as OP, Because there are many commands here in one line, it's hard to say which one is causing.
I get the 255 exit-code. PBF is Planet. Running on a 32GB RAM machine, 8 vcpus. 900GB disk space.

**Comment by devendrasr** [comment]
Do we have any fix for this? What's wrong here?

**Comment by toregua** [comment]
I have the same problem with the 3.1 and i fix this by adding : 

`service postgresql start`

under `chown postgres:postgres /data/$PGDIR && \`

in the init.sh then rebuild etc

**Comment by philipkozeny** [comment]
We've changed quite a lot with the latest releases (3.6 & 3.7). You can check the latest version out and give us feedback, the problem should be fixed.
