### ISSUE TITLE
Question: Are you interested in a PR that adds automatic import of OSM and Wikipedia?

### ISSUE THREAD

**Issue by leonardehrenfried** [mediagis/nominatim-docker#181]
We at stadtnavi, a public transport platform, have been using your Docker image for a while now.

We have made modifications that allow us to start the container and automatically import the OSM and Wikipedia dumps and configure the replication URL.

The command line looks like the following:

```
  docker run -it --rm \
    -e PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf \
    -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
    -e IMPORT_WIKIPEDIA=true
    -p 5432:5432
    -p 8080:8080
    --name nominatim 
    nominatim
```
After running this command, you have a working installation of nominatim - with data!

A little more documentation and code is available at https://github.com/stadtnavi/nominatim-docker/tree/master/latest

Right now I'm in the process of backporting these changes to 3.6 and we are wondering if there would be interest in us upstreaming these changes.

Would you be interested in a PR?

**Comment by philipkozeny** [comment]
Sounds super interesting, would look forward to receive a PR for that!

**Comment by leonardehrenfried** [comment]
Ok, great to hear.

I think I have finished the backport and you can try it out with the following command:

```
  docker run -it --rm \
    -e PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf \
    -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
    -e IMPORT_WIKIPEDIA=false \
    -p 5432:5432 \
    -p 8080:8080 \
    --name nominatim \
    stadtnavi/nominatim:3.6
 ```
 
After the import you can use the search at http://localhost:8080/search.php?q=avenue%20pasteur

Code and some more documentation is available at https://github.com/stadtnavi/nominatim-docker/tree/master/3.6

Before I prepare a PR, I have a few questions:

- You're using a custom Postgres storage location at `/data/`. What is the reason for this?
- How important is it to keep the backwards compatibility with the current way of doing things?
