### ISSUE TITLE
Correct docker command for starting single mode Nominatim container with updated local.php for Nominatim update

### ISSUE THREAD

**Issue by NGeb1** [mediagis/nominatim-docker#182]
Hi,

To use the update commands as per the readme of version [3.6](https://github.com/mediagis/nominatim-docker/tree/master/3.6) with updated local.php file as per the explanation in step 6 of the readme, the correct docker command to start the single node container with the local.php in the conf folder below the nominatimdata folder should be:
_docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim \ 
-v /home/me/nominatimdata/conf/local.php:/app/src/build/settings/local.php \ 
-v /home/me/nominatimdata/postgresdata:/var/lib/postgresql/12/main nominatim bash /app/start.sh_

When starting the single mode Nominatim container with the above command, the following update command work as expected:
_docker exec -it nominatim sudo -u postgres ./src/build/utils/update.php --init-updates
docker exec -it nominatim sudo -u postgres ./src/build/utils/update.php --import-osmosis-all_

Hope this helps anyone........

NG

**Comment by Stefanic** [comment]
It did help at least one person, thanks!

**Comment by rorosan** [comment]
It also helped me, but i do have a problem when running 
__docker exec -it nominatim sudo -u postgres ./src/build/utils/update.php --init-updates__

with the erro 

PHP Warning:  require_once(/app/src/build/settings/settings.php): failed to open stream: No such file or directory in /app/src/build/utils/update.php on line 3
PHP Fatal error:  require_once(): Failed opening required '/app/src/build/settings/settings.php' (include_path='.:/usr/share/php') in /app/src/build/utils/update.php on line 3
could anyone help me ? @NGeb1 @Stefanic

**Comment by Stefanic** [comment]
Looks like either the image itself or the volume mount is incorrect.
When I run:

`docker exec nominatim ls -lha /app/src/build/settings`

I get this output:

`total 28K
drwxr-xr-x 1 root root 4.0K Mar 18 11:01 .
drwxr-xrwx 1 root root 4.0K Mar 18 08:26 ..
-rw-r--r-- 1 root root  861 Mar 18 08:13 local.php
-rw-r--r-- 1 root root  943 Mar 18 11:01 settings-frontend.php
-rw-r--r-- 1 root root 5.3K Mar 18 08:26 settings.php`

If you only see a local.php file there I think you made a mistake in the volume mount.
If that is not the case try rebuilding the image and recreate the container.

**Comment by rorosan** [comment]
Hello @Stefanic , thanks so much for your feedback, 

i cloned the repo locally instead on copying only the 3.6 files which i am using for my project, and the command seems to be executed fine !
I do now have to check that the postgis database is effectively updated.
Have a nice day !

**Comment by philipkozeny** [comment]
We've also refactored how 3.6 and the REPLICATION_URL etc. works. You can set those now with environment variables. I am going to close the issue for now, feel free to reopen or create a new one if this still happens, thanks!
