### ISSUE TITLE
Server fails to startup (V 3.6)

### ISSUE THREAD

**Issue by TheCodeN00b** [mediagis/nominatim-docker#184]
Hi everyone, I'm trying to set up this server but I can't understand why it won't start. I am a noob with docker stuff so please be patient...

What is failing is:
`2021-03-21 21:56:07.795 UTC [514] FATAL:  terminating autovacuum process due to administrator command`
`2021-03-21 21:56:07.797 UTC [29] LOG:  background worker "logical replication launcher" (PID 36) exited with exit code 1`
`2021-03-21 21:56:07.839 UTC [31] LOG:  shutting down...`
`2021-03-21 21:56:11.611 UTC [29] LOG:  database system is shut down`
` done`
`server stopped`

Here's the whole console log of the whole process. I'm following the README guide step by step. 
PS: I know you don't officially support Windows but any help is appreciated.

[nominatim 3.6 install log.txt](https://github.com/mediagis/nominatim-docker/files/6182471/nominatim.3.6.install.log.txt)

**Comment by philipkozeny** [comment]
It seems like the data got imported. How do you start the image after the import?

**Comment by TheCodeN00b** [comment]
I'm using the command on step 4 of the documentation
`docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim -v /home/me/nominatimdata/postgresdata:/var/lib/postgresql/12/main nominatim bash /app/start.sh`

**Comment by philipkozeny** [comment]
Ok, any errors here or is that the error you have posted above?

**Comment by TheCodeN00b** [comment]
Sorry for the late reply. The console prints a hash of some sort
`24152b1d8c15471dd942e43d2dedd194d4ba790d3d6ce6fcaf5c0a08e09a639e`


but trying a request with url `http://localhost:7070/reverse?format=json&lat=53.95090&lon=-6.37792` yields:

> {"error":{"code":500,"message":"Failed to establish database connection:SQLSTATE[08006] [7] could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?"}}

**Comment by philipkozeny** [comment]
We've released a huge upgrade with the 3.6 version. Can you try it again with the new one please and report back? Make sure to read the new Readme! 

https://github.com/mediagis/nominatim-docker/blob/master/3.6/README.md

**Comment by TheCodeN00b** [comment]
Hi! I'll be able to try again this weekend, and I'll make sure to be back and report on how it will go. Thanks again for the support
