### ISSUE TITLE
Error installing nominatim-docker on DigitalOcean Docket

### ISSUE THREAD

**Issue by himsashu** [mediagis/nominatim-docker#185]
I am trying to install nominatim-docker on DigitalOcean Docket. I am running git clone command but getting below error:

root@docker-ubuntu-s-2vcpu-4gb-blr1-01:~# git clone git@github.com:mediagis/nominatim-docker.git
Cloning into 'nominatim-docker'...
The authenticity of host 'github.com (13.234.176.102)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,13.234.176.102' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mtmail** [comment]
Try the https URL https://docs.github.com/en/github/using-git/which-remote-url-should-i-use
