### ISSUE TITLE
Info: 3.6 Breaking Change

### ISSUE THREAD

**Issue by philipkozeny** [mediagis/nominatim-docker#188]
With the PR https://github.com/mediagis/nominatim-docker/pull/183 we've decided to make a change in how the images work.

The benefits:

- you can finally use the images we provide on https://hub.docker.com/r/mediagis/nominatim (>=3.6) and don't have to build / setup them on your own
- one command to setup, import the data & run Nominatim 
- use environment variables to change the config
- reducing complexity and therefore making it easier to support you
- automated tests und building / pushing of new images to https://hub.docker.com/r/mediagis/nominatim

Please be aware, that there are breaking changes if you previously used the 3.6 images.

**Comment by jpylypiw** [comment]
Hi there 😄 
I recently started using the image and I like these changes!
It was kinda frustryting to see a completely changed documentation this morning and I need to rebuild my whole database after that, but it is worth it.
Working with environment variables is much easier than working with config files.
Great work in my opinion.

**Comment by leonardehrenfried** [comment]
:heart:
