### ISSUE TITLE
Add support for nominatim 3.0.0

### ISSUE THREAD

**Issue by alaminopu** [mediagis/nominatim-docker#19]
Please update the docker to support nominatim 3.0.0

**Comment by winsento** [comment]
@alaminopu I'll look at the weekend

**Comment by dorukozturk** [comment]
@winsento I am working on porting 3.0.1. I will create a PR once it is done.

**Comment by winsento** [comment]
@dorukozturk good news.

**Comment by winsento** [comment]
Thank you @dorukozturk 
Im add your Dockerfile on https://hub.docker.com  with tags:
- `3.0`
- `3.0.1`

https://hub.docker.com/r/mediagis/nominatim/tags/
