### ISSUE TITLE
Documentation 3.6 Readme 404 URL

### ISSUE THREAD

**Issue by thomleysens** [mediagis/nominatim-docker#190]
Hi, 

First, thanks for your dockers and your work. 

I think there is a wrong url, line 55 in  the 3.6 [Readme](https://github.com/mediagis/nominatim-docker/blob/master/3.6/README.md):
```Full documentation for Nominatim update available [here](https://github.com/openstreetmap/Nominatim/blob/master/docs/admin/Import-and-Update.md#updates)```. 
It leads to a 404.  The correct URLs seem to be: https://github.com/osm-search/Nominatim/blob/master/docs/admin/Update.md for update and https://github.com/osm-search/Nominatim/blob/master/docs/admin/Import.md for import.

**Comment by mtmail** [comment]
Might be better to link to the specific version on https://nominatim.org/release-docs/3.6.0/admin/Import/ instead of the github master branch (which currently represents Nominatim 3.7)

**Comment by philipkozeny** [comment]
Nice catch, thanks @thomleysens. 

@mtmail I have seen your commit, I'll create a PR out of that, ok?

**Comment by thomleysens** [comment]
@philipkozeny you're welcome. 😉 Thank you all for this repo. It makes the build and deployment of a Nominatim server a lot easier.
