### ISSUE TITLE
Postgres Tuning

### ISSUE THREAD

**Issue by philipkozeny** [mediagis/nominatim-docker#195]
As of now our images do little things to tune PostgreSQL, tuning suggestions from https://nominatim.org/release-docs/3.7.0/admin/Installation/#tuning-the-postgresql-database are ignored.

We could add those suggestion as default settings to our ```postgresql.auto.conf``` and allow the user to override those with environment variables. 

This should be done in ```start.sh``` to reflect changes on every startup. In addition we need to revert ```fsync``` & ```full_page_writes``` instead of deleting the config file after the import.

We could also place two ```.conf``` files into the ```conf.d``` folder (e.g. ```import.conf, tuning.conf``` and remove ```import.conf``` after the initial import.

**Comment by leonardehrenfried** [comment]
I like @mtmail's approach of putting files into the conf.d folder.

**Comment by Bakaniko** [comment]
Thanks @philipkozeny I'll try that tomorrow !
I have a couple runs with France data to benchmark against (sort of).

**Comment by Bakaniko** [comment]
Hi, did a test today with France.
It went pretty well, everything is working fine.
Duration was 402 minutes, previous deployments took 405 and 409 minutes so I don't see a big increase in performance.
But environment variables are a big plus so I was able to increase easily the max_wal_size easily. 
Thanks for that @philipkozeny  and @leonardehrenfried .

For the record, I used that config:

```bash
docker run -it --rm \
  -e PBF_URL=https://download.geofabrik.de/europe/france-latest.osm.pbf \
  -e REPLICATION_URL=https://download.geofabrik.de/europe/france-updates/ \
  -e IMPORT_WIKIPEDIA=false \
  -e NOMINATIM_PASSWORD=very_secure_password \
  -v nominatim-data:/var/lib/postgresql/12/main \
  -e THREADS=6 \
  -e POSTGRES_MAX_WAL_SIZE=3GB \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:3.6
```

The machine was a 1 TB HDD, 8 threads, 32 GB of RAM.

You can notice that I changed the urls to https because the firewall blocks http requests here.

**Comment by leonardehrenfried** [comment]
Perhaps the tuning isn't so effective when you're not using a SSD.

Good catch with the http url. If you want to send a PR to update the documentation, we'd welcome that.

**Comment by Bakaniko** [comment]
@leonardehrenfried I was not sure that http/https in urls was a bug or a feature ;)

I'll do that today or tomorrow.

**Comment by james-tisato** [comment]
I'm not sure the current approach of removing `postgres-import.conf` after successful import is working as intended. The file is removed at the end of `init.sh`, but this only removes it from the local filesystem of the container that did the import. If / when the container is restarted then the file is present again when the postgres service is started again.

I've just completed an import, restarted the container sometime later and have noitced that both `fsync` and `full_page_writes` are both off.

**Comment by leonardehrenfried** [comment]
You're right. This is addressed in https://github.com/mediagis/nominatim-docker/pull/373#discussion_r967670285
