### ISSUE TITLE
Nominatim 3.7 Implementation

### ISSUE THREAD

**Issue by jpylypiw** [mediagis/nominatim-docker#197]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Nominatim 3.7 was released days ago. There are some braking changes you can see in the migration documentation:
https://nominatim.org/release-docs/latest/admin/Migration/#360-370
I would like to upgrade my existing Nominatim 3.6 server to 3.7 without destroying the database.

**Describe alternatives you've considered**
If upgrading is not possible a clean 3.7 installation would also be nice.

**Additional context**
No additional context

**Comment by philipkozeny** [comment]
We're already working to support the latest Nominatim release. Since there are some bigger changes as you've described this will still take some time.

**Comment by leonardehrenfried** [comment]
We also would love pull requests for this.

**Comment by bruno-hl** [comment]
Great work guys! I'm working from a Macbook with M1. Can you check M1 support? I'm getting the following warning:
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by mtmail** [comment]
@bruno-hl Please create a new issue, it's unrelated to the request to support Nominatim version 3.7

**Comment by manusoftar** [comment]
Are you considering to add support for docker compose???
