### ISSUE TITLE
403 Forbidden error when opening localhost

### ISSUE THREAD

**Issue by jans25** [mediagis/nominatim-docker#2]
Hello together,

I've cloned your github repository and have built it locally on my Windows 10 machine. After that, I've started running the container. The container was created successfully and runs on port 
5432/tcp, 0.0.0.0:8080->8080/tcp.  

If I try to open http://localhost:8080/ in a webbrowser, the error message "You don't have permission to access / on this server." appears.

Hopefully you know what is going on,

Jan

**Comment by stavskal** [comment]
I have the same problem

**Comment by winsento** [comment]
I can fix it on weekend.

11 авг. 2016 г. 10:25 AM пользователь "Stavrianos Skalidis" <
notifications@github.com> написал:

**Comment by bosonix** [comment]
I also have the same problem.

**Comment by winsento** [comment]
Good news. Im fix it.

**Comment by bosonix** [comment]
I tried it and it works. Thanks.
