### ISSUE TITLE
OSM Import into postgreSQL fails

### ISSUE THREAD

**Issue by rarspace01** [mediagis/nominatim-docker#207]
**Describe the bug**
On the initial run the OSM Import fails 

**To Reproduce**
Steps to reproduce the behavior (only one):
```
docker run -it --rm \
-e PBF_URL=https://download.geofabrik.de/europe/italy-latest.osm.pbf \
-e REPLICATION_URL=https://download.geofabrik.de/europe/italy-updates/ \
-e IMPORT_WIKIPEDIA=false \
-p 8080:8080 \
-p 5432:5432 \
--name nominatim \
mediagis/nominatim:3.6
```

**Expected behavior**
Doesn't fail :)

**Screenshots & Logs**
```2021-04-22 06:36:45  Parsing gazetteer style file '/app/src/settings/import-full.style'.
NOTICE:  table "place" does not exist, skipping
Processing: Node(51100k 288.7k/s) Way(0k 0.00k/s) Relation(0 0.0/s)2021-04-22 06:39:45  ERROR: planet_osm_nodes - error on COPY: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2021-04-22 06:39:45  ERROR: Data: 1795711761	458829528	76226291
1795711764	458829551	76240732
1795711782	458829595	76242058
1795711783	458829666	76225364
1795711784	458829670	76244629
1795711785	458829766	76232428
1795711787	458829787	76221057
1795711789	458829882	76240732
1795711791	458830084	76210765
1795711793	458830160	76240191
1795711795	458830187	76238711
1795711797	458830366	76242831
1795711799	458830393	76245586
1795711802	458830406	76224021
1795711804	458830461	76247186
1795711806	458830492	76242136
1795711808	458830510
...
	404253360	87334959
1798389343	404254232	86481941
1798389344	404254513	86485241
1798389345	404254671	86723013
1798389346	404254934	86137125
1798389347	404255674	86489287
1798389348	404255694	87370433
1798389349	404255804	85743738
1798389350	404256437	91202650
1798389351	404257541	86135459
1798389352	404257742	86725828
1798389353	404258578	87371129
1798389354	404259805	86722753
1798389355	404260742	86489688
1798389356	404261125	91199121
1798389357	404261564	85741933
1798389358	404261870	86137085

2021-04-22 06:39:45  ERROR: DB copy thread failed: COPYing data to Postgresql.
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database query failed

  thrown in /app/src/lib/DB.php on line 187```

**Desktop / Server (please complete the following information):**
 - OS & Version: Mac OSX 
 - Docker Version: Docker version 20.10.5, build 55c4c88
 - Nominatim Version: 3.6.0

**Comment by philipkozeny** [comment]
Can reproduce it on my Mac. Will take a look into what's going on.

**Comment by rarspace01** [comment]
From testing with my other computer (which has 32GB instead of 16GB RAM)
- OS & Version: Ubuntu 20.04LTS 
 - Docker Version: Docker version 20.10.6, build 370c289
 - Nominatim Version: 3.6.0
 
It manages to pass the corresponding number of Nodes, without a problem and the import continues. I presume that it's either related to a memory or space problem from the postgresql Database inside of docker.

**Comment by philipkozeny** [comment]
Did the same, running without the `postgres-tuning.conf` parameters everything is running smoothly on a device with 16GB of RAM. So you would need to tune (or downgrade in that respect) the PostgreSQL settings with the env variables (https://github.com/mediagis/nominatim-docker/tree/master/3.6#configuration.)

The PostgreSQL defaults before we apply our settings are:

```
postgres=# select name, setting, unit from pg_settings where name in ('shared_buffers','maintenance_work_mem','autovacuum_work_mem','work_mem','effective_cache_size','synchronous_commit','max_wal_size','checkpoint_timeout','checkpoint_completion_target');
             name             | setting | unit
------------------------------+---------+------
 autovacuum_work_mem          | -1      | kB
 checkpoint_completion_target | 0.5     |
 checkpoint_timeout           | 300     | s
 effective_cache_size         | 524288  | 8kB
 maintenance_work_mem         | 65536   | kB
 max_wal_size                 | 1024    | MB
 shared_buffers               | 16384   | 8kB
 synchronous_commit           | on      |
 work_mem                     | 4096    | kB
```

**Comment by leonardehrenfried** [comment]
That raises the question of what kind of machine we should optimise the default tuning parameters for.

32GB of RAM is fine for a server but we might confuse people who will use this image on their dev laptop.

**Comment by philipkozeny** [comment]
True. I guess we should stick to the defaults Nominatim choose for production, but maybe we should add another env variable to disable Postgres tuning for dev?

**Comment by leonardehrenfried** [comment]
That would be one way. Another one would be to point this out in the docs and choose more conservative mem settings in the quick start example.

Honestly, I don't know what the right way forward is as both can be misunderstood and/or overlooked.

**Comment by gittan443** [comment]
> That would be one way. Another one would be to point this out in the docs and choose more conservative mem settings in the quick start example.
> 
> Honestly, I don't know what the right way forward is as both can be misunderstood and/or overlooked.

Rename postgres_tuning.conf to postgres_tuning32GB.conf and change default shared buffers value to something smaller that would work on a 16 GB machine. Use default in example, include in documentation how to build/set value for larger machine?

**Comment by leonardehrenfried** [comment]
Now that we have another issue report for this (#237) perhaps there is someone who's interested in putting together a PR or improve the documentation.

**Comment by lucascognamiglio1** [comment]
increse the ram in the settings of Docker

**Comment by brad-4k** [comment]
Hello,

I'm encountering the same result.  Crash on import.  I'm trying to import the North America OSM data but it crashes out on the postgresql phase with basically the same message as to the start of this thread.

The AWS instance has 256GB of memory, 128GB of free storage.

I'm not sure what settings to tweak.  The following is the command I'm running:

```
docker run -it --rm --memory="128g" \
  -e PBF_URL=https://download.geofabrik.de/north-america-latest.osm.pbf \
  -e IMPORT_WIKIPEDIA=true \
  -e IMPORT_US_POSTCODES=true \
  -e IMPORT_GB_POSTCODES=true \
  -e IMPORT_TIGER_ADDRESSES=true \
  -p 8088:8088 \
  -v /home/ubuntu/osm-maps/data:/nominatim/data \
  --name nominatim \
  --shm-size 32GB \
  mediagis/nominatim:4.0
```

Any ideas?

Thank you for all your hard work!

**Comment by leonardehrenfried** [comment]
You need to look into the postgres logs to find the root cause of the problem but I would say that 128gb of disk space is not enough.

I'm running an instance for Germany, Switzerland and Austria and the alone takes 80gb of disk.

Check with 'docker system df -v' how larger your containers are.

On top of that: what are you trying to achieve by making /nominatim/data a volume?

**Comment by brad-4k** [comment]
I'm slowly coming to that realization.  More space is needed.

WRT /nominatim/data, I was just using the documentation example.  Not sure why I didn't catch that, thanks.

**Comment by brad-4k** [comment]
Hello again.

Is there something I need to do to increase the disk space available to Postgres in the Docker Image?  I've increased the storage on the system I'm running on to 1TB.  I'm trying to import the North-America OSM data and it crashes with an error stated as: "DB copy thread failed. COPYing data to Postgresql."

I'm unsure how to see the Postgres logs in the image.  My Docker knowledge is a bit limited but willing to learn.

Thank you again for a great project!

**Comment by leonardehrenfried** [comment]
You need to open a shell inside the container and then look at ` /var/log/postgresql`.

Also, once you have the shell you can check with df -h what the available disk space is.

**Comment by brad-4k** [comment]
Ok, wow, I think I figured it out.  I needed to clean out all of the latent Docker storage and start the process fresh.  I was able to get North America to import and work.  Thank you for your help.
