### ISSUE TITLE
Using data for Wikipedia rankings and UK postcodes

### ISSUE THREAD

**Issue by phol56** [mediagis/nominatim-docker#21]
For "regular" nominatim installations these data files can just be dripped into a data folder and get picked up using -

wget --output-document=data/wikipedia_article.sql.bin http://www.nominatim.org/data/wikipedia_article.sql.bin
wget --output-document=data/wikipedia_redirect.sql.bin http://www.nominatim.org/data/wikipedia_redirect.sql.bin
wget --output-document=data/gb_postcode_data.sql.gz http://www.nominatim.org/data/gb_postcode_data.sql.gz

 - is there any way to include these in the docker installation process? currently we're getting warning messages telling us that the data is not being picked up.

Thanks

**Comment by phol56** [comment]
I've attempted to modify the dockerfile to see if i can get the files uploaded during the build process - but still not working:

ENV CONST_Wikipedia_Data_Path "/data"
RUN curl -L http://www.nominatim.org/data/wikipedia_article.sql.bin --create-dirs -o /data/wikipedia_article.sql.bin
RUN curl -L http://www.nominatim.org/data/wikipedia_redirect.sql.bin --create-dirs -o /data/wikipedia_redirect.sql.bin
RUN curl -L http://www.nominatim.org/data/gb_postcode_data.sql.gz --create-dirs -o /data/http://www.nominatim.org/data/gb_postcode_data.sql.gz

**Comment by winsento** [comment]
@phol56 can you show build trace?

**Comment by phol56** [comment]
I think it may be something to do with how the paths are defined in Nominatim but I just can't get it to work... here is the build trace (attached). 
[trace1.txt](https://github.com/mediagis/nominatim-docker/files/1248942/trace1.txt)

**Comment by phol56** [comment]
ok - i finally managed to get those files picked up and working by adding a 
**nominatim-docker/2.5/data** 
folder containing the files and then adding to the Dockerfile:

COPY data/gb_postcode_data.sql.gz ./src/data/gb_postcode_data.sql.gzwikipedia_article.sql.bin
COPY data/wikipedia_article.sql.bin ./src/data/wikipedia_article.sql.binwikipedia_redirect.sql.bin
COPY data/wikipedia_redirect.sql.bin ./src/data/wikipedia_redirect.sql.bin

Hope that helps
Paul

**Comment by Littlericket** [comment]
Hi, i modified the Dockerfile for this:

`
# wikipedia rankings
RUN curl https://www.nominatim.org/data/wikipedia_article.sql.bin > /app/src/data/wikipedia_article.sql.bin
RUN curl https://www.nominatim.org/data/wikipedia_redirect.sql.bin > /app/src/data/wikipedia_redirect.sql.bin
`
