### ISSUE TITLE
Incorrect update database commands (path and permission issues)

### ISSUE THREAD

**Issue by Stefanic** [mediagis/nominatim-docker#223]
**Describe the bug**
Problem when running commands for updating the database. Examples in README.md do not work.
For the init I needed to supply --project-dir /usr/local/lib/nominatim to **not** get the following error:
psycopg2.errors.UndefinedFile: could not access file "/app/module/nominatim.so": No such file or directory

With init resolved, next step is running the replication as stated in the README.md:
docker exec -it nominatim sudo -u nominatim nominatim replication --project-dir /nominatim
But the nominatim user does not have permission for that directory (nor for /usr/local/lib/nominatim).

I'm now running the update process using /home/nominatim as project-dir because it wants to write to a new file 'osmosischange.osc'.

**To Reproduce**
1. Use command 'docker exec -it nominatim sudo -u nominatim nominatim replication --project-dir /nominatim'
2. See error:
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 152, in run
    UpdateReplication._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 113, in _update
    state = replication.update(conn, params)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/replication.py", line 108, in update
    outhandler = WriteHandler(str(options['import_file']))
RuntimeError: Open failed for '/nominatim/osmosischange.osc': Permission denied

**Expected behavior**
The update process is started.

**Desktop / Server (please complete the following information):**
 - OS & Version: Ubuntu 20.04.2
 - Docker Version: 20.10.6
 - Nominatim Version: 3.7

**Comment by Stefanic** [comment]
I just noticed, the import_osmosis_log table stays empty.
Should I open a new bug report for that or is it by design?

**Comment by leonardehrenfried** [comment]
We have a CI step that checks the update and it executed successfully: https://github.com/mediagis/nominatim-docker/runs/2573364117?check_suite_focus=true#step:6:385

Would you be able to [modify the test](https://github.com/mediagis/nominatim-docker/blob/master/.github/workflows/ci.yml#L34-L49) so that it exhibits the behaviour that you're seeing and send a pull request? That would help us a lot in diagnosing.

**Comment by mtmail** [comment]
`import_osmosis_log` has no entries after the initial import, so that's expected. There will be two entries per update/replication if you set that up https://nominatim.org/release-docs/latest/admin/Update/

(The table name is historic, these days [osmium](https://osmcode.org/), not osmosis tool is used to run database updates).

**Comment by Stefanic** [comment]
It does seem this all traces back to the same issue, but I cannot find what is wrong with my docker image/container.
I just pulled the latest 3.7 version (from 4 days ago) but it does not seem to change anything.

The update process using project-dir /home/nominatim does interact with the database but it seems to update increments way smaller than daily (REPLICATION_URL=https://planet.openstreetmap.org/replication/day/). The import and indexing both take a little over a minute to process.

Modifying the test won't help because running the command copied from ci.yml on my container fails with the same issue, no permission in that directory for the nominatim user.

To make it even more strange, when I call check-for-updates the output changes depending on the project-dir:
# docker exec -it nominatim sudo -u nominatim nominatim replication --project-dir /usr/local/lib/nominatim --check-for-updates
2021-05-17 11:29:34: Using project directory: /usr/local/lib/nominatim
2021-05-17 11:29:34: New data available (4525252 => 4545297).
# docker exec -i nominatim sudo -u nominatim nominatim replication --project-dir /nominatim --check-for-updates
2021-05-17 11:29:50: Using project directory: /nominatim
2021-05-17 11:29:50: Database is up to date.
# docker exec -i nominatim sudo -u nominatim nominatim replication --check-for-updates
2021-05-17 11:30:10: Using project directory: /app
2021-05-17 11:30:10: New data available (4525252 => 4545298).

First step is finding out why permissions in my container differ from the permissions in the CI container, but I'm clueless how to achieve that.

**Comment by philipkozeny** [comment]
After pulling the latest update did you re-initialise your data and start from scratch, or try to work on with an existing volume?

**Comment by Stefanic** [comment]
I re-used the postgresql database files and mounted them in /var/lib/postgresql/12/main

I'll try a newly init-ed container for testing using the same commands as in ci.yml

**Comment by leonardehrenfried** [comment]
Your project dir also contains the config file which contains the update interval. That would explain why you're seeing different responses depdening on that.

**Comment by leonardehrenfried** [comment]
Now that I think about it, perhaps this line https://github.com/mediagis/nominatim-docker/blob/master/3.7/init.sh#L43 needs to be moved to take this case into account.

**Comment by leonardehrenfried** [comment]
@Stefanic can you successfully update after running `chown -R nominatim:nominatim /nominatim`

**Comment by Stefanic** [comment]
It simply was the permissions in the end, a newly created Monaco container had these permissions:
```
root@16324eee9f76:/app# ls -lha /nominatim/
total 1.5M
drwxr-xr-x 1 nominatim nominatim   56 May 17 12:03 .
drwxr-xr-x 1 root      root       198 May 17 12:01 ..
-rw-r--r-- 1 nominatim nominatim  257 May 17 12:01 .env
-rw-rw-r-- 1 nominatim nominatim 1.4M May 17 12:03 osmosischange.osc
drwxrwxr-x 1 nominatim nominatim  154 May 17 12:02 website
```

How the chown failed in my container beats me, but after manually running chown the import works as intended.

**Comment by leonardehrenfried** [comment]
Well, you should not have to manually fix permissions so there might still be a bug. Currently adding a test case for the combination of bind-mount, container recreation and updates: https://github.com/stadtnavi/nominatim-docker/commit/fa8b87f9c4094ebd15d0d32b35a9a71eace08588

**Comment by leonardehrenfried** [comment]
@Stefanic I was able to reproduce your issue in CI: https://github.com/stadtnavi/nominatim-docker/runs/2600711274?check_suite_focus=true#step:9:100

Fix is coming.

**Comment by Stefanic** [comment]
Thanks a lot!

**Comment by leonardehrenfried** [comment]
No problem. I'm acting partially out of self-interest as this would have affected me, too.

**Comment by leonardehrenfried** [comment]
@Stefanic Once the newest version of the image is uploaded (when [this](https://github.com/mediagis/nominatim-docker/actions/runs/849896771) is finished, will take 1 hour in total) can you test it again with your existing container?

**Comment by Stefanic** [comment]
@leonardehrenfried Works like a charm

**Comment by Stefanic** [comment]
@mtmail I have created a full new instance over the weekend, but the `import_osmosis_log` table remains empty.
Should I open a new bug report for that?

**Comment by Stefanic** [comment]
@philipkozeny A complete rebuild of the database and then afterwards running the update proces.
It was started this morning but it should already contain a record for the import, the indexing was completed a minute ago but unfortunately no records in the `import_osmosis_log` table.

**Comment by mtmail** [comment]
@Stefanic Not sure either. I checked and see the same. Opened https://github.com/osm-search/Nominatim/discussions/2348

**Comment by Stefanic** [comment]
That link points at a discussion about external postal codes, I'm confused now.
I'll raise a new issue tomorrow about the import table staying empty.

**Comment by mtmail** [comment]
@Stefanic Sorry, wrong URL. I meant https://github.com/osm-search/Nominatim/discussions/2350

**Comment by Stefanic** [comment]
I see the problem was located and fixed, thanks @mtmail !

**Comment by leonardehrenfried** [comment]
@Stefanic If you want to contribute to this repo, you could watch out for the 3.7.2 release and send a PR (probably just bumping the version number) with it.

If you rely on the table being there you might also want to add a test that checks that.

**Comment by Stefanic** [comment]
> @Stefanic If you want to contribute to this repo, you could watch out for the 3.7.2 release and send a PR (probably just bumping the version number) with it.
> 
> If you rely on the table being there you might also want to add a test that checks that.

I've prepared a branch for when the fix is released.
Looking into how to make a test for this specific issue, I think a python script that runs a query should do it but I'm unfamiliar with python and how to run the CI tests.

**Comment by philipkozeny** [comment]
> > @Stefanic If you want to contribute to this repo, you could watch out for the 3.7.2 release and send a PR (probably just bumping the version number) with it.
> 
> > 
> 
> > If you rely on the table being there you might also want to add a test that checks that.
> 
> 
> 
> I've prepared a branch for when the fix is released.
> 
> Looking into how to make a test for this specific issue, I think a python script that runs a query should do it but I'm unfamiliar with python and how to run the CI tests.

Thanks. Looking forward to your PR. Test won't be required. 

Please don't forget to also update the URLs in the Readme with the new version then.

**Comment by leonardehrenfried** [comment]
Yes, after thinking about it, I came to the conclusion that the test would belong into the nominatim repo since it's not something that this repo provides.
