### ISSUE TITLE
Volume not used 

### ISSUE THREAD

**Issue by xenbit-germany** [mediagis/nominatim-docker#228]
**Describe the bug**
Persistent volume is not used after successful startup.

**To Reproduce**
1. Use command

```
sudo docker run -d --restart always --shm-size=10g \
  -e PBF_URL=https://myurl \
  -e REPLICATION_URL=https://download.geofabrik.de/europe/germany-updates/ \
  -e IMPORT_WIKIPEDIA=false \
  -e NOMINATIM_PASSWORD=1234567890 \
  -v nominatim-data:/home/user/nominatim/data \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:3.7
```

2. See error

cd /home/user/nominatim/data
ls

Folder is empty

**Desktop / Server (please complete the following information):**
 - OS & Version: CentOS 8
 - Docker Version: 20.10.5
 - Nominatim Version: 3.7.0

**Comment by leonardehrenfried** [comment]
The folder you want to make a volume is `/var/lib/postgresql/12/main` (as documented) not the folder specified in your command.

You seem to try to make the project directory a volume which is unnecessary, even problematic, as it only contains config files that are regenerated on startup. In case you wonder the project dir is located at `/nominatim`.

If this makes your problem go away, please close the ticket.

**Comment by xenbit-germany** [comment]
I tried it with /var/lib/postgresql/12/main. But ´´/var/lib/postgresql/12/main´´ is also empty...

There are many reasons why users don't want or can't use /var/lib/postgresql/12/main as volume path. It is also no the purpose of an docker volume.

**Comment by leonardehrenfried** [comment]
We run an import with a mount on CI: https://github.com/mediagis/nominatim-docker/blob/master/.github/workflows/ci.yml#L52-L62

You could send a PR with modified CI steps that demonstrates your problem. This would make it easier to reproduce.

**Comment by Stefanic** [comment]
It seems you may have confused the volume syntax, the part after the semicolon is the path **inside** the docker container. That is the only path specified by the docker image developer.

For example, if you want to bind your local filesystem path `/home/user/nominatim/data` as the place where all the containers postgresql files will be stored you use this volume (bind):
`-v /home/user/nominatim/data:/var/lib/postgresql/12/main`

**Comment by leonardehrenfried** [comment]
Ah, good find! Now the conversation makes more sense. I assumed the OP was referring to the folders inside the container being empty.

**Comment by xenbit-germany** [comment]
Thank you for your patience and help.
