### ISSUE TITLE
Turn ENV variables into ARG ones

### ISSUE THREAD

**Issue by er1z** [mediagis/nominatim-docker#23]
If anyone wants to use this image as a sub-part of docker-compose, it's impossible to specify PBF file location because within ``Dockerfile`` ``ENV`` key instead of ``ARG`` is used.

Could you replace to the second one, please?

**Comment by winsento** [comment]
@er1z Done. Can you add documentation how to build with parameters?

**Comment by er1z** [comment]
Ok, "soon" because a bit of work is in front of me.
