### ISSUE TITLE
Postgresql doesn't install itself on small machine ( nominatim 3.7)

### ISSUE THREAD

**Issue by rorosan** [mediagis/nominatim-docker#237]
**Describe the bug**
I have an error regarding the non installation of Postgresql when running a container on a 'small' droplet (vm) on digital ocean (2 vCPUs/ 4GB RAM/ 80GB Disk)

**To Reproduce**
1. Launch a small vm with similar characteristics
2. Build container
3. Run container on 'small' region

**Expected behavior**
Everyting is expected to run smoothly, aka nominatim launched and running on the target region

**Desktop / Server (please complete the following information):**
 - OS & Version: Debian 10
 - Docker Version: 20.10.7
 - Nominatim Version: 3.7

**Comment by rorosan** [comment]
Everything seems to work fine when using these parameters in 3.7/conf.d/postgres-tuning.conf

shared_buffers = 1GB
maintenance_work_mem = 1GB
autovacuum_work_mem = 1GB
work_mem = 50MB
effective_cache_size = 1GB
synchronous_commit = off
max_wal_size = 1GB
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9

I am not a database expert though, but everything seemed to work fine for now i updated this conf and uses it in production now.
Any advice on setup would be vastly appreciated, and thanks for all the hardwork on 3.7 guys !

**Comment by leonardehrenfried** [comment]
This is the result of the default tuning config we chose is one for a server with 32GB of RAM. We discussed this over here: https://github.com/mediagis/nominatim-docker/issues/207

**Comment by leonardehrenfried** [comment]
BTW, all if these postgres tuning params can be set via environment variables. If you create a PR which documents an example for a smaller server, we're happy to merge that.
