### ISSUE TITLE
40+ hours of generating for one Country.

### ISSUE THREAD

**Issue by 8m0** [mediagis/nominatim-docker#246]
Hello,

I use Windows 10 and Docker to run nominatim. I used this command for my purposes `docker run -it --rm -e PBF_URL=https://download.geofabrik.de/europe/germany-latest.osm.pbf -e REPLICATION_URL=https://download.geofabrik.de/europe/germany-updates/ -p 8080:8080 --name nominatim mediagis/nominatim:3.7`.
It has been filtering data already ~48 hours. When it gonna stop? Will it stop eventually? Why it is that long for just one region? The Germany osm file has 3.4g size and docker already has image size of 83.5g size.
[Console window](https://i.imgur.com/YRUiHln.png)

**Comment by Stefanic** [comment]
What are the hardware specifications for the machine you are running this on?
For example, if you put the data on a spinning disk this will take weeks.

**Comment by 8m0** [comment]
Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz   3.30 GHz
16.0 GB (15.9 GB usable)
regular hdd.

So nothing went wrong and it has to do that much work for just one country?

**Comment by Stefanic** [comment]
Looks like it yes.
Each level of detail takes longer, level 30 is the most detailed level (housenumber level).
This is a guess but I think levels 28 and 30 take up almost 80% of the import time.

Running the import on a SSD is highly recommended.

**Comment by 8m0** [comment]
Hm. On the official site it says that whole planet would have 650gb size. How is that if just Germany not fully loaded has 83gb? Just curious.

**Comment by mtmail** [comment]
Germany is exceptionally well mapped in OpenStreetMap, the German community is very active. The raw OSM data has more objects (e.g. buldings, house numbers) in Germany than whole South America.

**Comment by Stefanic** [comment]
I think that number is a bit outdated, my company runs an up-to-date planet OSM/nominatim and this uses 1.3TB disk space.
Might be a bit off because it is an older nominatim version updated for a couple of years with daily updates.

**Comment by leonardehrenfried** [comment]
I just took a look at our server where we import DACH (Germany, Austria, Switzerland) and that takes 93GB for postgres and 71GB for the flatnode storage. Not sure if flatnodes will make it use more less postgres disk space.

But as @Stefanic said, HDD is going to take forever.

**Comment by leonardehrenfried** [comment]
Looking at your screenshot I see that it imports 125 objects/second. On my (admittedly beefy) server with a SSD I see easily 10 times the import speed.

Are you aware that the nominatim default tuning params (which we apply) are optimized for a machine with 32GB RAM?

**Comment by 8m0** [comment]
Yes I have read about that. Al I need is just one region to test everything. Thought maybe there is something off or went wrong and for sure didn't expect it would take that long for one region and that much space. Hope it gonna be done soon, don't want to cancel it at this far step. Thank you for the replies.
