### ISSUE TITLE
feat: be able to import from the local OSM extracts, avoiding downloading from outside

### ISSUE THREAD

**Issue by Bartizan** [mediagis/nominatim-docker#247]
**Is your feature request related to a problem? Please describe.**
My use case is. A customized OSM extracts has to be imported to Nominatim service. But there is no way to specify the path.

**Describe the solution you'd like**
OSM data extracts (.pbf) can be imported with either PBF_URL or PBF_PATH variable. PBF_URL variable specifies the URL, the data is downloaded during initialization and removed from disk afterwards. PBF_PATH variable specifies the path inside the container to the mounted OSM extracts data. No .pbf file is removed after initialization and can used again.

**Describe alternatives you've considered**
To run a 'local' http server to serve OSM data for nominatim import.

**Comment by Bartizan** [comment]
Solved

**Comment by fakhamatia** [comment]
@Bartizan 
According to this issue can you help me with [this discussions](https://github.com/mediagis/nominatim-docker/discussions/236), I have a few questions.
