### ISSUE TITLE
How to change Postgres port

### ISSUE THREAD

**Issue by tadejj** [mediagis/nominatim-docker#250]
I can`t connect to DB with port 5432. Can I change this port manualy?

**Comment by Stefanic** [comment]
Inside the docker container postgres will always run on port 5432.
Using docker port mapping you can specify the port it should use on the host machine.

For example, setting `-p 1234:5432` will allow you to connect to port 1234 on the host machine.

**Comment by tadejj** [comment]
It works! Thanks!
