### ISSUE TITLE
OSM import crash on 3.7

### ISSUE THREAD

**Issue by GhostTalker** [mediagis/nominatim-docker#252]
**Describe the bug**
First start crashs on import OSM

**To Reproduce**
docker run -it --rm --shm-size=2g \
  -e PBF_PATH=/nominatim/data/data.osm.pbf \
  -e REPLICATION_URL=http://download.geofabrik.de/europe/germany-updates/ \
  -e IMPORT_WIKIPEDIA=true \
  -e THREADS=4 \
  -v /srv/Nominatim/osmdata:/nominatim/data \
  -v nominatim-pgdata:/var/lib/postgresql/12/main \
  -p 7070:8080 \
  --name nominatim \
  mediagis/nominatim:3.7

**Expected behavior**
Complete Import and start 

**Screenshots & Logs**
2021-08-09 07:53:23: Done 4383800 in 5144 @ 852.207 per second - rank 30 ETA (seconds): 7113.21
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 129, in run
    indexer.index_full(analyse=not args.index_noanalyse)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 174, in index_full
    self.index_by_rank(26, 30)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 217, in index_by_rank
    self.index(RankRunner(30), 20)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 277, in index
    thread = next(next_thread)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 298, in find_free_thread
    if thread.is_done():
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 129, in is_done
    if self.conn.poll() == psycopg2.extensions.POLL_OK:
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

**Desktop / Server (please complete the following information):**
 - OS & Version: Ubuntu 20.10
 - Docker Version: 20.10.2
 - Nominatim Version: 3.0.7

**Comment by leonardehrenfried** [comment]
The default configuration that nominatim uses expects 32GB of RAM. Do you have that on your machine?

Further reading: https://github.com/mediagis/nominatim-docker/issues/207

**Comment by GhostTalker** [comment]
I have 30GB of memory. how to configure less in the start command?

**Comment by leonardehrenfried** [comment]
You can use the params in the tuning section: https://github.com/mediagis/nominatim-docker/tree/master/3.7#postgresql-tuning

I don't know what the exact combination is for smaller machines so after you've found out, you could update the documentation to help others.

**Comment by GhostTalker** [comment]
After adjusting the parameters:

docker run -it --rm --shm-size=2g \
  -e PBF_PATH=/nominatim/data/data.osm.pbf \
  -e REPLICATION_URL=http://download.geofabrik.de/europe/germany-updates/ \
  -e IMPORT_WIKIPEDIA=true \
  -e THREADS=4 \
  -e POSTGRES_SHARED_BUFFERS=1GB \
  -e POSTGRES_MAINTENANCE_WORK_MEM=2GB \
  -e POSTGRES_AUTOVACUUM_WORK_MEM=1GB \
  -e POSTGRES_EFFECTIVE_CACHE_SIZE=6GB \
  -v /srv/Nominatim/osmdata:/nominatim/data \
  -v nominatim-pgdata:/var/lib/postgresql/12/main \
  -p 7070:8080 \
  --name nominatim \
  mediagis/nominatim:3.7

 i got the next error

2021-08-09 16:24:21: Done 848136 in 4494 @ 188.698 per second - rank 26 ETA (seconds): 8794.22
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 129, in run
    indexer.index_full(analyse=not args.index_noanalyse)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 174, in index_full
    self.index_by_rank(26, 30)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 212, in index_by_rank
    self.index(RankRunner(rank))
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 277, in index
    thread = next(next_thread)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 298, in find_free_thread
    if thread.is_done():
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 129, in is_done
    if self.conn.poll() == psycopg2.extensions.POLL_OK:
psycopg2.errors.InternalError_: Distance must not be greater than 1.46203e-309
CONTEXT:  PL/pgSQL function place_node_fuzzy_area(geometry,integer) line 15 at RETURN
PL/pgSQL function insert_addresslines(bigint,smallint,smallint,hstore,geometry,text) line 90 at assignment
SQL statement "SELECT * FROM insert_addresslines(NEW.place_id, NEW.partition, max_rank,
                                    NEW.address, geom, NEW.country_code)"
PL/pgSQL function placex_update() line 451 at SQL statement

**Comment by leonardehrenfried** [comment]
I have never seen this problem before during my import of DACH (Germany, Austria, Switzerland). Looks like a geometry is too large to insert. Is this a straight up Germany extract from geofabrik or something custom?

Also, I would raise this issue with the nominatim devs.

**Comment by GhostTalker** [comment]
It is a combined map. NRW + Bavaria + Switzerland + Middle of Italy. But it was running on the old 3.6 version.

**Comment by GhostTalker** [comment]
echo ""
echo "2_8 download data"
curl -L 'https://download.geofabrik.de/europe/germany/bayern-latest.osm.pbf' --create-dirs -o /srv/Nominatim/osmdata/bayern-latest.osm.pbf
curl -L 'https://download.geofabrik.de/europe/switzerland-latest.osm.pbf' --create-dirs -o 	/srv/Nominatim/osmdata/switzerland-latest.osm.pbf
curl -L 'https://download.geofabrik.de/europe/italy/centro-latest.osm.pbf' --create-dirs -o /srv/Nominatim/osmdata/centro-latest.osm.pbf
curl -L 'https://download.geofabrik.de/europe/italy/sud-latest.osm.pbf' --create-dirs -o /srv/Nominatim/osmdata/sud-latest.osm.pbf
curl -L 'https://download.geofabrik.de/europe/germany/nordrhein-westfalen-latest.osm.pbf' --create-dirs -o /srv/Nominatim/osmdata/nordrhein-westfalen-latest.osm.pbf

echo ""
echo "3_8 convert to o5m"
osmconvert /srv/Nominatim/osmdata/bayern-latest.osm.pbf -o=/srv/Nominatim/3.5/osmdata/bayern-latest.o5m
osmconvert /srv/Nominatim/osmdata/centro-latest.osm.pbf -o=/srv/Nominatim/3.5/osmdata/centro-latest.o5m
osmconvert /srv/Nominatim/osmdata/sud-latest.osm.pbf -o=/srv/Nominatim/3.5/osmdata/sud-latest.o5m
osmconvert /srv/Nominatim/osmdata/switzerland-latest.osm.pbf -o=/srv/Nominatim/3.5/osmdata/switzerland-latest.o5m
osmconvert /srv/Nominatim/osmdata/nordrhein-westfalen-latest.osm.pbf -o=/srv/Nominatim/osmdata/nordrhein-westfalen-latest.o5m

echo ""
echo "4_8 combine into one o5m"
osmconvert /srv/Nominatim/osmdata/bayern-latest.o5m /srv/Nominatim/osmdata/centro-latest.o5m /srv/Nominatim/osmdata/sud-latest.o5m /srv/Nominatim/osmdata/switzerland-latest.o5m /srv/Nominatim/osmdata/nordrhein-westfalen-latest.o5m -o=/srv/Nominatim/osmdata/data.o5m

echo ""
echo "5_8 convert to o5m to osm.bpf"
osmconvert /srv/Nominatim/osmdata/data.o5m -o=/srv/Nominatim/osmdata/data.osm.pbf

echo ""
echo "6_8 chmod the fucking file"
chmod +r /srv/Nominatim/osmdata/data.osm.pbf

**Comment by leonardehrenfried** [comment]
Did you manage to solve your problem in the end? Can we close this?

**Comment by GhostTalker** [comment]
Yes can be closed
