### ISSUE TITLE
how download multiple OSM datafiles through docker PBF_URL

### ISSUE THREAD

**Issue by sid-sundrani** [mediagis/nominatim-docker#253]
The -e PBF_URL argument can be passed with docker to download the data from the given link. However, can data be downloaded from multiple links? 

For example, if one was to download the data not just from Europe (https://download.geofabrik.de/europe/monaco-latest.osm.pbf) but from Africa, Central America, Asia, and South America. 

How can this be done? 

Doing docker run -it --rm \
  -e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf .. would just get the data from that one source

**Comment by leonardehrenfried** [comment]
You can combine the files with https://docs.osmcode.org/osmium/latest/osmium-merge.html before importing them. Updates for that will be tricky though.

There is also someone who is working on a way to import and update multiple files: https://github.com/mediagis/nominatim-docker/pull/186

In the end we decided not to merge it into this repo but perhaps @Aximem has finished it in another one.

**Comment by Aximem** [comment]
I created a repo for my own purpose: https://github.com/Aximem/nominatim-docker-multiple-regions
Which enable to init / add / update multiple regions nominatim docker instance. You can take a look and use it or adapt it to your use case.

**Comment by sid-sundrani** [comment]
@leonardehrenfried  @Aximem Thanks for sharing this. Will take it look

@leonardehrenfried  Have one question related to using the `PBF_PATH`. If I download the files from the various continents and merge them into a single PBF file, how would I pass this path during `docker run -it`? If I have a local path, how would I use `PBF_PATH`? It says that it should point to a path within the container rather than a local directory

**Comment by leonardehrenfried** [comment]
The Readme describes this: you need to create a so-called volume to make the file available inside the docker container.
