### ISSUE TITLE
Unable to resolve host when starting postgresql

### ISSUE THREAD

**Issue by tadejj** [mediagis/nominatim-docker#266]
When I tried to run the container I get crash while postgresql is starting 

1. Use command:
docker run -it --rm --shm-sizze 20g -e PBF_URL=https://download.geofabrik.de/europe/ukraine-latest.osm.pbf -e REPLICATION_URL=https://download.geofabrik.de/europe/ukraine-updates/ -p 8089:8080 -p 8099:5432 --name nominatim mediagis/nominatim:3.7
2. See error: 
   sudo: unable to resolve host a4170b8573b8: Temporary failure in name resolution

![image](https://user-images.githubusercontent.com/6958302/138248467-03e26a49-9d88-4eef-aa0e-6157ec796ba5.png)

 Server
 - Windows Server 2019 Standart
 - Docker Version: 17.10.0-ee-preview-3
 - Nominatim Version:  3.7

Can you help me? What I need to do?
Thnks

**Comment by leonardehrenfried** [comment]
Also docker on windows limits the memory available to the VM quite dramatically.

#254

**Comment by tadejj** [comment]
@leonardehrenfried thank you for answer! 
I think I have enough memory
![image](https://user-images.githubusercontent.com/6958302/138264157-f35e33e3-528b-48f4-93a2-bbccf1093af5.png)

I decrese shm-size and add postgres tuning, but issue still exist

![image](https://user-images.githubusercontent.com/6958302/138264518-efb09f48-a040-4d29-9ebc-ad0871a3635e.png)

**Comment by leonardehrenfried** [comment]
Can this be closed?
