### ISSUE TITLE
Sudden performance degradation

### ISSUE THREAD

**Issue by Stefanic** [mediagis/nominatim-docker#267]
**Describe the bug**
After running the container for about one month (reverse geocoding) queries suddenly cause high CPU load.
I have 3 machines running with the same specs, they run a complete planet on 3.7.2 with flatnode storage and run updates daily.
My preliminary guess is that a specific update or the amount of applied updates may be causing something in postgresql to fail?
This has happened before and running a vacuum full analyze on the database changed nothing.

**To Reproduce**
1. Run container for several weeks
2. See reverse geocoding use much more CPU all of a sudden

**Expected behavior**
Performance of the container stays the same, very fast reverse geocoding with very low CPU usage.

**Screenshots & Logs**
Please let me know what I can provide or do.

**Desktop / Server (please complete the following information):**
 - OS & Version: Ubuntu 20.04
 - Docker Version: 20.10.9, build c2ea9bc
 - Nominatim Version: 3.7.2

**Additional context**
Server specs:
8 cores 16 threads CPU
64GB RAM
NVMe SSD storage

**Comment by philipkozeny** [comment]
Thanks for the report, I have not observed that in my long running containers but will check it. Did you try to restart the container and see if this still happens after the restart with the same database?

**Comment by Stefanic** [comment]
I have, also just now for good measure.
Previous time this occurred the only fix I found was to start over by deleting the database from disk.

It seems like something within postgresql changes (maybe an index goes corrupt, or maybe the flatfile is not used anymore) and this change is persisted.

Any pointer for where to start investigating this are very welcome, I have no idea where to start..

**Comment by philipkozeny** [comment]
Tbh, I also don't really know where to start looking. But it's reproducible for you? Do you see anything specific going on or just more cpu cycles for the same amount of queries, filling up RAM etc.? Anything strange going on in the update logs?

**Comment by Stefanic** [comment]
Unfortunately only more CPU cycles (by postgres) without any pointer why. Disks are almost idle and no IO wait on the server.

Plan is to try and find out if this is caused by the docker container in any way by building one server by hand with the nominatim guide amd rebuild one with the docker image and see of they again both develop this issue.

Will keep you posted.

**Comment by Stefanic** [comment]
Some findings over the past month:

- Directly installing on server (and also running updates) ends up in the same performance degradation in about 2 weeks
- Planet import within the docker container (fresh install) now results directly into degraded performance

**Comment by philipkozeny** [comment]
> Some findings over the past month:
> 
> * Directly installing on server (and also running updates) ends up in the same performance degradation in about 2 weeks
> * Planet import within the docker container (fresh install) now results directly into degraded performance

Thanks for the update @Stefanic, can you please open an issue at Nominatim (https://github.com/osm-search/Nominatim)?

**Comment by leonardehrenfried** [comment]
I'd check the slow query log: https://blog.crunchydata.com/blog/logging-tips-for-postgres-featuring-your-slow-queries

**Comment by Stefanic** [comment]
> > Some findings over the past month:
> > 
> > * Directly installing on server (and also running updates) ends up in the same performance degradation in about 2 weeks
> > * Planet import within the docker container (fresh install) now results directly into degraded performance
> 
> Thanks for the update @Stefanic, can you please open an issue at Nominatim (https://github.com/osm-search/Nominatim)?

https://github.com/osm-search/Nominatim/issues/2557

**Comment by philipkozeny** [comment]
@Stefanic I have seen the comments at the Nominatim repository. Does it make sense to add 

```
max_parallel_workers_per_gather = 0
jit = off
```

to our `postgres-tuning.conf` by default, or just add this in the documentation for planet-sized imports?

**Comment by leonardehrenfried** [comment]
Do we have an idea why these config changes improve performance? They sound like they are meant to increase performance.

**Comment by leonardehrenfried** [comment]
One thing we could investigate if performance is better with more recent postgres versions.

**Comment by Stefanic** [comment]
@philipkozeny, hard to say. For reverse geocoding this seems like a sensible choice, but if this (negatively) impacts other use cases I cannot say.
Came across this discussion: https://github.com/osm-search/Nominatim/issues/1677 that indicates JIT was also an issue for the indexing process.

**Comment by Stefanic** [comment]
> Do we have an idea why these config changes improve performance? They sound like enabling them is good for performance.

Disabling JIT is because of the incorrect assumption of postgresql that using it will speed up the query while in practice this slows it down significantly because of the extra CPU usage.
What max_parallel_workers_per_gather exactly disables is unclear to me.
