### ISSUE TITLE
curl: no URL specified!

### ISSUE THREAD

**Issue by suelm** [mediagis/nominatim-docker#28]
I get the following error during build. 

Step 16/22 : ARG PBF_DATA=http://download.geofabrik.de/europe/germany-latest.osm.pbf
 ---> Running in 2b34de1ef3ba
 ---> d7c650986a24
Removing intermediate container 2b34de1ef3ba
Step 17/22 : RUN curl -L -f $PBF_DATA --create-dirs -o /app/src/data.osm.pbf
 ---> Running in 406d41420d22
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
The command '/bin/sh -c curl -L -f $PBF_DATA --create-dirs -o /app/src/data.osm.pbf' returned a non-zero code: 2

**Comment by philipkozeny** [comment]
Closing the issue for now, please try the latest version (3.6 at the moment), there have been a lot of changes / fixes, thanks!
