### ISSUE TITLE
Missing ARM support / documentation

### ISSUE THREAD

**Issue by Trymzet** [mediagis/nominatim-docker#285]
**Describe the bug**
It seems like only some Docker images of Nominatim support ARM: https://hub.docker.com/r/mediagis/nominatim/tags

This means that your "how to use" guide does not work for Macbook M1 owners (since eg. the 4.0 branch will pull the 4.0-tagged image, which does not support ARM).

**Expected behavior**
I would expect all images to support ARM, and if hey don't, it should be clearly documented in the "how to use" section.

**Comment by philipkozeny** [comment]
Thanks for reporting, we had to pull the ARM support for now since there was an issue in upstream: https://github.com/mediagis/nominatim-docker/pull/275

Will check if we can reactivate it again.

**Comment by Trymzet** [comment]
Thanks you :)

**Comment by philipkozeny** [comment]
Still not fixed in upstream unfortunately.

**Comment by leonardehrenfried** [comment]
Debian appears to have the fix in version 11, so moving the base image to that might be a solution. But that would probably involve changing of the postgres paths, because their version is different from Ubuntu.

**Comment by philipkozeny** [comment]
They have also included postgresql 13, which would mean that we need to support an upgrade path of the existing database from 12 to 13, which is a PITA to be honest.

**Comment by Stefanic** [comment]
Officially the only upgrade path is dump and restore..
Maybe the nominatim 4.x branch can be based on a higher postgresql version?

**Comment by philipkozeny** [comment]
`pg_upgrade` would be another option, but we would need both binaries in the image or use another docker container to migrate the data like https://github.com/tianon/docker-postgres-upgrade etc.

I would aim to switch to Ubuntu LTS 22.04 or Debian 11, or Alpine Linux (or whatever we decide) when there is a new 4.x Nominatim release, but not in between if we can't support a full migration.

**Comment by leonardehrenfried** [comment]
I see it the same way. Upgrading postgres versions should be part of 4.1 at the earliest.

**Comment by sergioisidoro** [comment]
It says: "We can reactivate until there is a fix for those two issues"
https://github.com/mediagis/nominatim-docker/pull/275

Both of them seemed to have been fixes:

> It looks like that fix was landed in OpenSSL 1.1.1i so upgrading to 1.1.1i or newer should fix it.
```
Changed in openssl (Ubuntu):
--
status: | Confirmed → Fix Released
```
(2022-02-19)

**Comment by leonardehrenfried** [comment]
Has the fixed made it to the Ubuntu 20.04 docker image yet?

If you have an ARM Mac you could test by simply executing `curl https://www.nominatim.org` from the latest Ubuntu image.

**Comment by sergioisidoro** [comment]
I just checked, and tried to build it locally. It seem it's not on Focal yet :/

**Comment by leonardehrenfried** [comment]
:/

Does it make a difference if you execute `apt-get update && apt-get upgrade openssl` right at the beginning?

**Comment by philipkozeny** [comment]
Great news, thanks! I'll prepare a PR to enable ARM support again.
