### ISSUE TITLE
IMPORT_STYLE - FULL - Can we import the nodes only needed?

### ISSUE THREAD

**Issue by bujji1** [mediagis/nominatim-docker#298]
Thanks for this wonderful docker component. 

I am looking for an option to import only places, schools, colleges, and the rest of the educational institutes. Is there any way I can do with the current design?

I mean Is there any way we can pass or modify code to support something similar to the below? 
> ./osmosis --read-pbf planet-latest.osm.pbf --tf accept-nodes place=city,town,village 

that means with IMPORT_STYLE - FULL - can we pass any additional parameters that will import only the nodes needed? ( if I want to load only places, schools, colleges, and the rest of the educational institutes ). Thanks for your help.

**Comment by mtmail** [comment]
You can create your own style file, e.g. use the full style as basis and remove what you don't need. Explained at https://nominatim.org/release-docs/latest/customize/Import-Styles/ Question about the format are best posted to https://github.com/osm-search/Nominatim/discussions

**Comment by bujji1** [comment]
Thank You @mtmail for your quick response. I am going to try by adding  `-e NOMINATIM_IMPORT_STYLE=/var/myfile.style` to docker run then. Please correct me if I am wrong. Thanks again.

docker run -it --rm \
  -e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf \
  -e REPLICATION_URL=https://download.geofabrik.de/europe/monaco-updates/ \
  -e NOMINATIM_IMPORT_STYLE=/var/myfile.style
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.0

**Comment by leonardehrenfried** [comment]
You can try, I don't think it will work. You need to put the file at `/usr/local/etc/nominatim/your.style` inside the container and then add `-e NOMINATIM_IMPORT_STYLE=your`.

**Comment by bujji1** [comment]
@leonardehrenfried  you are right. It didn't work. If you don't mind can I know how to put the file in a container? Because the below docker command is creating the container and importing the data in one step.  Do we have to follow a different approach for this?  

```
docker run -it --rm
-e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf
-e REPLICATION_URL=https://download.geofabrik.de/europe/monaco-updates/
-e NOMINATIM_IMPORT_STYLE=/var/myfile.style
-p 8080:8080
--name nominatim
mediagis/nominatim:4.0
```

**Comment by bujji1** [comment]
> The setting name is `IMPORT_STYLE` not `NOMINATIM_IMPORT_STYLE` https://github.com/mediagis/nominatim-docker/tree/master/4.0#import-style

Even this didn't work. I think we have to copy the file to the container before loading the data. But I am not sure how to split the steps for it since our direct docker run command is creating and loading the data.

**Comment by leonardehrenfried** [comment]
You can use volumes to make files available inside the docker container.

Also note that IMPORT_STYLE doesn't refer to a file path but the file inside `/usr/local/etc/nominatim/`.

**Comment by bujji1** [comment]
thank you @leonardehrenfried - Sorry I am confused. The volumes will be available only after running the docker run right? :(

**Comment by philipkozeny** [comment]
> thank you @leonardehrenfried - Sorry I am confused. The volumes will be available only after running the docker run right? :(

The volumes / files you mount are available at runtime, so in the moment the docker container starts. An example would be:

```
docker run -it --rm
-e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf
-e REPLICATION_URL=https://download.geofabrik.de/europe/monaco-updates/
-e NOMINATIM_IMPORT_STYLE=/var/myfile.style
-v /my/local/file:/usr/local/etc/nominatim/
-p 8080:8080
--name nominatim
mediagis/nominatim:4.0
```

This would mount `/my/local/file` on your host into `/usr/local/etc/nominatim/` in the docker container.  Read here for more info how volumes work: https://docs.docker.com/storage/volumes/

**Comment by bujji1** [comment]
Thank You @philipkozeny . It is now copying the myfile.style, but getting some other error :( . It says country_settings.yaml not found.

> 2022-02-22 18:49:00: Using project directory: /nominatim
> 2022-02-22 18:49:00: Configuration file 'country_settings.yaml' not found.
> Directories searched: [PosixPath('/nominatim'), PosixPath('/usr/local/etc/nominatim')]
> 2022-02-22 18:49:00: FATAL: Config file not found.

**Comment by bujji1** [comment]
Thank You @philipkozeny . Now it says again my style not found :(  Sorry, I forgot to tell you that I am running this command from PowerShell windows.  /mnt/d/nomdocker/myfile.style location is d:\nomdocker\myfile.style


` docker run -it --rm -e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf  -e NOMINATIM_IMPORT_STYLE=myfile -v /mnt/d/nomdocker/myfile.style:/usr/local/etc/nominatim/myfile.style -e NOMINATIM_PASSWORD=test123  -p 8080:8080 -p 5432:5432 --name nominatim mediagis/nominatim:4.0`

**Comment by mtmail** [comment]
The setting name is IMPORT_STYLE not NOMINATIM_IMPORT_STYLE https://github.com/mediagis/nominatim-docker/tree/master/4.0#import-style

**Comment by bujji1** [comment]
> IMPORT_STYLE

Thank You @mtmail . I tried this command also

`docker run -it --rm -e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf  -e IMPORT_STYLE=myfile -v /mnt/d/nomdocker/myfile.style:/usr/local/etc/nominatim/myfile.style -e NOMINATIM_PASSWORD=test123  -p 8080:8080 -p 5432:5432 --name nominatim mediagis/nominatim:4.0`

**Comment by bujji1** [comment]
> > Thank You @philipkozeny . It is now copying the myfile.style, but getting some other error :( . It says country_settings.yaml not found.
> > > 2022-02-22 18:49:00: Using project directory: /nominatim
> > 
> > 
> > > 2022-02-22 18:49:00: Configuration file 'country_settings.yaml' not found.
> > 
> > 
> > > Directories searched: [PosixPath('/nominatim'), PosixPath('/usr/local/etc/nominatim')]
> > 
> > 
> > > 2022-02-22 18:49:00: FATAL: Config file not found.
> 
> My bad. Change it to
> 
> `-v /my/local/myfile.style:/usr/local/etc/nominatim/myfile.style`

I think the problem with -v option is - it always creates directory for the mounted 

> If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v creates the endpoint for you. It is always created as a directory.

**Comment by bujji1** [comment]
The below approach is working for now :) 
1) Copied all settings files to my local windows D:\nomdocker directory and mapped that directory with container directory. 
2) Made changes to the local import-full. style file to take only nodes needed.
3) SO now it is running in full style mode but taking the files config file from the local directory

docker run -it --rm -e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf   -v D:\nomdocker\:/usr/local/etc/nominatim/ -e NOMINATIM_PASSWORD=test123  -p 8080:8080 -p 5432:5432 --name nominatim mediagis/nominatim:4.0

**Comment by leonardehrenfried** [comment]
Ok, so I think this can be closed, isn't it?
