### ISSUE TITLE
Lost the build on server restart

### ISSUE THREAD

**Issue by tk120404** [mediagis/nominatim-docker#304]
After successful installation of nominatim, we restarted over server to downgrade aws ec2 instance. We lost all the tables and index. How do we preserve the table and index

 - OS & Version: Ubuntu 20.04
 - Docker Version: 20.10.7
 - Nominatim Version: 4.0

**Comment by philipkozeny** [comment]
https://github.com/mediagis/nominatim-docker/tree/master/4.0#persistent-container-data
