### ISSUE TITLE
psycopg2.errors.DiskFull: could not extend file "base/16386/916148.2": No space left on device HINT:  Check free disk space. 

### ISSUE THREAD

**Issue by rkakade2021** [mediagis/nominatim-docker#310]
**Describe the bug**
Trying to install nominatim on a Windows machine via the Docker image. Command used,

docker run -it --rm --shm-size=100g -e threads=32 -e PBF_URL=http://download.geofabrik.de/north-america-latest.osm.pbf -e REPLICATION_URL=http://download.geofabrik.de/north-america-updates/ -e IMPORT_WIKIPEDIA=false -e NOMINATIM_PASSWORD=very_secure_password -v nominatim-data:/var/lib/postgresql/12/main  -p 8080:8080 --name nominatim mediagis/nominatim:4.0

Installation was successful using smaller pbf files eg. Greenland. But, fails for larger pbf files eg. North America. The machine seems to be sufficiently configured (see below). Additionally, all data seems to be getting loaded into RAM AND HDD while getting set up. Using about 200GB each in both. See attached image for errors thrown at the end.

OS: Windows 10 Enterprise
Version	21H2
OS build	19044.1526

Hardware Config:
Processor	Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz   2.39 GHz  (2 processors)
Installed RAM	384 GB (383 GB usable)
System type	64-bit operating system, x64-based processor
HDD: Solid State with 130GB free space

Docker Desktop Version: Docker Desktop 4.6.0 (75818)
Docker Image Version: 4.0

![image](https://user-images.githubusercontent.com/92768021/159492382-09cdca51-0fa1-442c-b94c-c502dcac775d.png)

**Comment by leonardehrenfried** [comment]
Docker on Windows uses a proper VM, not a container. This VM has some resource limits configured by default: https://github.com/mediagis/nominatim-docker/issues/254#issuecomment-917016826

Is this perhaps your problem?

**Comment by rkakade2021** [comment]
Thank you @leonardehrenfried for the prompt help. Let me review #254 and get back to you if I have questions.
