### ISSUE TITLE
About the speed of planet OSM data import.

### ISSUE THREAD

**Issue by yikakabu** [mediagis/nominatim-docker#330]
Hi, I'm here again.
I ran the docker in k8s, and importing the  planet data.
The only way I can see the ouput is log api of k8s, and the process of the importing is very slow.

The latest output is ```Processing: Node(7672928k 2080.5k/s) Way(6255k 0.02k/s) Relation(0 0.0/s)```
![F9B6608F-DEF0-F228-4FD9-795B56FC96AF](https://user-images.githubusercontent.com/38148405/169944036-35e5c465-2ce2-411b-a366-546069c75a05.png)

And 24 hours ago, the output is ```Processing: Node(7672928k 2080.5k/s) Way(4926 0.02k/s) Relation(0 0.0/s)```
![8A50AB9E-BBA3-403D-7DBF-B3B85E574ED3](https://user-images.githubusercontent.com/38148405/169944251-7144ee7a-dfd5-4211-ace6-562a6cabbbb0.png)
You can notice the processing speed is only 0.02k/s.

And the k8s pod cpu and memory usage is low as the picture shows.
![image](https://user-images.githubusercontent.com/38148405/169945316-82acb55c-7bf0-4a38-9b95-42d38e14209c.png)
![image](https://user-images.githubusercontent.com/38148405/169945236-e90567c2-ae38-4b47-a278-99263e3d566f.png)

Is that normal? What should I do if not.

**Comment by leonardehrenfried** [comment]
What sort of disk do you use? A HDD will be significantly slower than a SSD.

**Comment by yikakabu** [comment]
I am using a AWS EFS. And I downloaded the planet osm.pbf data to the EFS also. 
The read throughput is extremely higher than write throughput when the way processing and the total throughput usage is around 100%, so I am going to download the osm.pbf data to anothor EFS in order to read-write separation.
