### ISSUE TITLE
Cache PBF files after downloaded / resume download

### ISSUE THREAD

**Issue by mbrethes** [mediagis/nominatim-docker#332]
**Describe the bug**
If the Docker container instance is shut down during the processing of the PBF file previously downloaded from PBF_URL, and then restarted again, the container will re-download the whole file in PBF_URL regardless of whether the previous download was successful, or incomplete.

Same thing happens if the instance is shut down while the PBF file is being downloaded.

This becomes a problem if the PBF is very large (e.g. country, continent, or world), because a new download may take a lot of time, specially on home connections.

**To Reproduce**
1. create an instance with a large PBF file
2. stop the instance while downloading or before the end of processing of the PBF data
3. restart the instance

**Expected behavior**
The download should continue where it has stopped instead of restarting at 0 / the PBF file should not be redownloaded if it has been downloaded in full previously.

**Desktop / Server (please complete the following information):**
 - OS & Version: Debian 11
 - Docker Version: 20.10.5
 - Nominatim Version: 4.0

**Comment by Stefanic** [comment]
Not really a bug, more a missing feature I guess.
Should be as easy as adding -C - to the curl command line for the PBF download.

**Comment by leonardehrenfried** [comment]
Another way to solve this would be to download the pbf to the host and to use `PBF_PATH`: https://github.com/mediagis/nominatim-docker/tree/master/4.0#configuration

**Comment by Stefanic** [comment]
I opened https://github.com/mediagis/nominatim-docker/pull/336 for this

**Comment by leonardehrenfried** [comment]
Closing since #336 has been merged.
