### ISSUE TITLE
FATAL: Failed to reach replication service

### ISSUE THREAD

**Issue by oldwired** [mediagis/nominatim-docker#333]
**Describe the bug**
I downloaded and started via docker run, initially everything got imported, but in the end it terminated with the error message 

> FATAL: Failed to reach replication service

**To Reproduce**
1. Use command '...'
```
docker run -it --rm --shm-size=2g \
  -e PBF_URL=https://download.geofabrik.de/europe/dach-latest.osm.pbf \
  -e REPLICATION_URL=https://download.geofabrik.de/europe/dach-updates/ \
  -e IMPORT_WIKIPEDIA=false \
  -e NOMINATIM_PASSWORD=*redacted* \
  -v nominatim-data:/var/lib/postgresql/12/main \
  -p 8088:8080 \
  --name nominatim \
  mediagis/nominatim:4.0
```
2. See error
```
Checking TIGER external data table. ... not applicable
+ '[' https://download.geofabrik.de/europe/dach-updates/ '!=' '' ']'
+ sudo -E -u nominatim nominatim replication --init
2022-06-26 15:51:29: Using project directory: /nominatim
2022-06-26 15:51:32: Initialising replication updates
2022-06-26 15:56:07: Cannot reach the configured replication service 'https://download.geofabrik.de/europe/dach-updates/'.
Does the URL point to a directory containing OSM update data?
2022-06-26 15:56:07: FATAL: Failed to reach replication service
```
**Expected behavior**
The import succeeds and nominatim works.

**Desktop / Server (please complete the following information):**
 - OS & Version: Ubuntu 22.04 LTS (Jammy Jellyfish)
 - Docker Version: 20.10.12
 - Nominatim Version: 4.0

**Comment by leonardehrenfried** [comment]
It appears that the URL https://download.geofabrik.de/europe/dach-updates/ wasn't available during the import. Every now and then Geofabrik is overloaded and doesn't respond anymore.

Since this is non-critical for the import perhaps the it worked anyway. Can you check by starting your container?

If not, I'm afraid you have to run the import again.

**Comment by oldwired** [comment]
> It appears that the URL https://download.geofabrik.de/europe/dach-updates/ wasn't available during the import. Every now and then Geofabrik is overloaded and doesn't respond anymore.

I didn't think of that. In hindsight I should have started a discussion instead of an issue. Sorry.

I already restarted using the same command, it looks like it restarted the import as well. It ran through, finished and seems to work now.
