### ISSUE TITLE
Full planet import - Could not resize shared memory segment

### ISSUE THREAD

**Issue by leandroacostag** [mediagis/nominatim-docker#344]
Hello, I'm trying to setup a nominatim docker container on a AWS EC2 instance, specifically a r6g.4xlarge (16 vCPU, 128GB RAM, 1000GB io1 SSD).

I'm running the process with the following settings:
`docker run -d -it --rm\
  -e PBF_URL=https://ftpmirror.your.org/pub/openstreetmap/pbf/planet-latest.osm.pbf \
  -e REPLICATION_URL=https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/replication/day/ \
  -e NOMINATIM_PASSWORD=XXXXXXXX \
  -e IMPORT_WIKIPEDIA=true \
  -e IMPORT_US_POSTCODES=true \
  -e IMPORT_GB_POSTCODES=true \
  -e IMPORT_TIGER_ADDRESSES=true \
  -e shm-size=64G \
  -e NOMINATIM_FLATNODE_FILE="/nominatim/flatnode.file" \
  -e POSTGRES_SHARED_BUFFERS=4GB \
  -e POSTGRES_MAINTENANCE_WORK_MEM=20GB \
  -e POSTGRES_AUTOVACUUM_WORK_MEM=4GB \
  -e POSTGRES_WORK_MEM=100MB \
  -e POSTGRES_EFFECTIVE_CACHE_SIZE=48GB \
  -e POSTGRES_MAX_WAL_SIZE=2GB \
  -e THREADS=16 \
  -v nominatim-data:/var/lib/postgresql/12/main \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.0`

I'm using Ubuntu 20.04 (arm64) and nominatim 4.0.

I get the following error after indexing rank 18 (it took 9 hours to get here):

> 2022-07-21 00:37:01: Done 94796/94796 in 165 @ 571.892 per second - FINISHED boundaries rank 18
> 2022-07-21 00:37:01: Starting boundaries rank 19 (using batch size 1)
> Traceback (most recent call last):
>   File "/usr/local/bin/nominatim", line 11, in <module>
>     exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
>   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 235, in nominatim
>     return parser.run(**kwargs)
>   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 96, in run
>     return args.command.run(args)
>   File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 115, in run
>     indexer.index_full(analyse=not args.index_noanalyse)
>   File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 122, in index_full
>     self.index_boundaries(0, 30)
>   File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 143, in index_boundaries
>     self._index(runners.BoundaryRunner(rank, analyzer))
>   File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 195, in _index
>     total_tuples = cur.scalar(runner.sql_count_objects())
>   File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 43, in scalar
>     self.execute(sql, args)
>   File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 27, in execute
>     super().execute(query, args)
>   File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 142, in execute
>     return super(DictCursor, self).execute(query, vars)
> psycopg2.errors.DiskFull: could not resize shared memory segment "/PostgreSQL.2005656122" to 50438144 bytes: No space left on device

Storage usage is 50%, so I don't think this is the issue.

Is it possible to resume the indexing process? Do you think I can improve my environment parameters?

Thanks

**Comment by leonardehrenfried** [comment]
Googling the error leads me to this stackoverflow: https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device

So, you need to add `--shm-size=1g` to the docker command, which is documented in the readme.

On a related note, since we are getting more help requests for importing an entire planet, would you be interested in contributing some documentation on how to do it?

I can include things like:

- hardware type
- required disk size
- required RAM
- config params
- docker params

**Comment by leandroacostag** [comment]
> Googling the error leads me to this stackoverflow: https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device
> 
> So, you need to add `--shm-size=1g` to the docker command, which is documented in the readme.
> 
> On a related note, since we are getting more help requests for importing an entire planet, would you be interested in contributing some documentation on how to do it?
> 
> I can include things like:
> 
> * hardware type
> * required disk size
> * required RAM
> * config params
> * docker params

Hi Leonard. As you've said, i was entering shm-size as a nominatim environment parameter instead of entering as a docker container parameter. 

Now it's running fine. I've configured my AWS EC2 instance with some overkill specs I think, I've used a r6g.4xlarge instance, which has 128GB of RAM, 16 vCPUs and also chose a io1 1tb with 32000 IOPS volume for the import. It took about two days to finish.

These is are the docker/config params I've used:
`docker run -d -it --shm-size=64G --rm \
  -e PBF_URL=https://ftpmirror.your.org/pub/openstreetmap/pbf/planet-latest.osm.pbf \
  -e REPLICATION_URL=https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/replication/day/ \
  -e NOMINATIM_PASSWORD=XXXX \
  -e IMPORT_WIKIPEDIA=true \
  -e IMPORT_US_POSTCODES=true \
  -e IMPORT_GB_POSTCODES=true \
  -e IMPORT_TIGER_ADDRESSES=true \
  -e NOMINATIM_FLATNODE_FILE="/nominatim/flatnode.file" \
  -e POSTGRES_SHARED_BUFFERS=4GB \
  -e POSTGRES_MAINTENANCE_WORK_MEM=20GB \
  -e POSTGRES_AUTOVACUUM_WORK_MEM=4GB \
  -e POSTGRES_WORK_MEM=100MB \
  -e POSTGRES_EFFECTIVE_CACHE_SIZE=48GB \
  -e POSTGRES_MAX_WAL_SIZE=2GB \
  -e THREADS=16 \
  -v nominatim-data:/var/lib/postgresql/12/main \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.0`
