### ISSUE TITLE
Docker build fails with PBF format error message

### ISSUE THREAD

**Issue by braaannigan** [mediagis/nominatim-docker#35]
Hi

I'm trying to build the image on a mac (details below).  When I try to build with:
```
docker build -t nominatim .
```
I get the following error:
```
Reading in file: /app/src/data.osm.pbf
Using PBF parser.
node cache: stored: 0(-nan%), storage efficiency: -nan% (dense blocks: 0, sparse nodes: 0), hit rate: -nan%
Osm2pgsql failed due to ERROR: PBF error: PBF format error
Error executing external command: /app/src/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 1313 -P 5432 -d nominatim /app/src/data.osm.pbf
```
I'm running on mac os sierra (10.12.6) and Docker version 18.03.1-ce, build 9ee9f40

Any ideas what's happening?

Thanks for any advice

Liam

**Comment by jarbaugh5** [comment]
I'm seeing this as well - building the image with the north-america-latest file is where I have trouble (things worked fine with Monaco). I'm no expert, but I have a feeling it's related to Docker for Mac having trouble with very large image/file sizes. There are two different issues that could be part of it:

https://github.com/docker/for-mac/issues/2530
https://github.com/docker/for-mac/issues/2415

Again - I'm no expert, so I could easily be wrong! I'm attempting to build the image on an Ubuntu server to see if I can confirm/replicate it being a Mac issue. I'll keep you posted.

**Comment by jarbaugh5** [comment]
Okay the build is taking a while, but I can confirm that I didn't get the `PBF format error` on Ubuntu. Makes me more confident it's an issue with Docker for Mac. Downgrading to a working version as mentioned in the linked docker issues or switching to Ubuntu seems like the solution for now.

**Comment by HodorTheCoder** [comment]
Can confirm also-- tried on Mac OS and got the error, currently building docker image with north america on ubuntu and it's chugging along.

@jarbaugh5 : how long is yours taking?  Mine is going on 19 hours and it's currently doing an update on Rank 26 with an ETA of 8 hours to go-- maybe shoulda updated the thread count.  I'm on a pretty beefy machine.

**Comment by jarbaugh5** [comment]
Mine's been going ~38 hours I think. I think if you kill the docker build all you will lose is your progress on the current layer, but for this image that could be a fair amount of time. I also should have bumped the thread count up...

**Comment by philipkozeny** [comment]
Closing for now, if this still happens with the latest Docker version (20.10.5 as of now) please reopen the issue, thanks!
