### ISSUE TITLE
nominatim-docker 3.0

### ISSUE THREAD

**Issue by fberdejo** [mediagis/nominatim-docker#37]
Dear mediagis,

I have a question regarding updating the nominatim data on docker. but unfortunately, I encounter this message.. Updates not set up. Please run ./utils/update.php --init-updates

When I run this command
docker exec -it nominatim sudo -u nominatim ./src/utils/update.php --init-updates :

Functions
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
NOTICE: drop cascades to function get_addressdata(bigint,integer)
DROP TYPE
CREATE TYPE
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
NOTICE: drop cascades to function get_wikipedia_match(hstore,character varying)

Instruction that I follow. This is working for a 3 months
https://hub.docker.com/r/mediagis/nominatim/

Hope you can help about this issue.. thank you in advance

**Comment by philipkozeny** [comment]
Closing the issue for now, please try the latest version (3.6 at the moment), there have been a lot of changes / fixes, thanks!
