### ISSUE TITLE
Add basic authentication

### ISSUE THREAD

**Issue by damianobarbati** [mediagis/nominatim-docker#389]
In order to have the service exposed on the internet but with a minimum protection, could a basic auth be provided?
`NOMINATIM_AUTH_USERNAME` and `NOMINATIM_AUTH_PASSWORD` could be provided at first run to setup the apache conf.

Doing so would prevent a lot of implementers to have another layer to manage the communication with the nominatim server.

**Comment by leonardehrenfried** [comment]
Whilst I personally would not use this feature, I'm happy to accept pull requests.

**Comment by philipkozeny** [comment]
As soon as you expose this service outside your network I would always recommend running a reverse proxy in front of the docker service (just for the sake to setup a secure SSL connection). In my opinion, authentication should be done by the reverse proxy and not the service.
