### ISSUE TITLE
FATAL: Creating new database failed.

### ISSUE THREAD

**Issue by ZeroE04** [mediagis/nominatim-docker#404]
**Describe the bug**

**To Reproduce**
1. Use command：
`sudo docker run --net=host -it --shm-size=1g \
  -e PBF_PATH=/nominatim/data/us-latest.osm.pbf \
  -e REPLICATION_URL=https://download.geofabrik.de/north-america/us-updates/ \
  -e IMPORT_WIKIPEDIA=false \
  -e IMPORT_US_POSTCODES=/data0/wakui/projects/gis_server/map_data/us_postcodes.csv.gz \
  -e IMPORT_TIGER_ADDRESSES=/data0/wakui/projects/gis_server/map_data/tiger-nominatim-preprocessed-latest.csv.tar.gz \
  -v /data0/wakui/projects/gis_server/map_data:/nominatim/data \
  -v nominatim-data:/var/lib/postgresql/14/main \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.2`

3. See error

**Expected behavior**

2022-12-11 08:03:27: Using project directory: /nominatim
2022-12-11 08:03:29: Creating database
**createdb: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?**
2022-12-11 08:03:30: FATAL: Creating new database failed.

**Screenshots & Logs**
If applicable, add screenshots & logs to help explain your problem.

**Desktop / Server (please complete the following information):**
 - OS & Version: [ubuntu]
 - Docker Version: 
 - Nominatim Version: [4.2]

**Additional context**

I have not change any line in dockerfile, why?

**Comment by ZeroE04** [comment]
3.7 is ok，4+ version failed

**Comment by ZeroE04** [comment]
done

**Comment by sebheitzmann** [comment]
I have the same error. Why do you close this issue ? What was the problem ?

**Comment by githubjeka** [comment]
@sebheitzmann

Same on 4.2
To fix it see your log to more details

For example 

There error `Error: Data directory /var/lib/postgresql/14/main must not be owned by root` 

 before `createdb: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory` error.
