### ISSUE TITLE
Query left-to-right and right-to-left parsing on direct geocoding 

### ISSUE THREAD

**Issue by Afler** [mediagis/nominatim-docker#409]
Hi.
If I'll do this:
![image](https://user-images.githubusercontent.com/49097219/208066435-343de72a-33f1-45b8-b7cb-c0483b7d5504.png)
I'll get the result and it's ok.

But if I'll change the order of the city name which is "moskva" and the street name and the building number which is "ryabinovaya 40a" in the query then I'll get nothing:
![image](https://user-images.githubusercontent.com/49097219/208067028-29bdb42d-379c-4799-81b5-4a3b2e87bc4e.png)

The Nominatim doc says: "q=\<query\> is free-form query string to search for. Free-form queries are processed first left-to-right and then right-to-left if that fails."
Do i do something wrong?
Thanks

**Comment by Afler** [comment]
UPD: The OSM Nominatim API provides the result for both cases:
![image](https://user-images.githubusercontent.com/49097219/208069841-37d2d78d-0463-46a7-b7bb-0dbb0be6d40b.png)
![image](https://user-images.githubusercontent.com/49097219/208069926-2ebb984a-831a-4cd1-a223-f232daed6963.png)

**Comment by mtmail** [comment]
The openstreetmap.org website is also sending the &viewbox URL parameter (the coordinates the user is currently looking at) and the browser language (&accept-language). You can experiment more at https://nominatim.openstreetmap.org/ui/search.html You can install that debugging interface to run against your own installation, too https://github.com/osm-search/nominatim-ui

**Comment by mtmail** [comment]
If after further testing you think it's a bug in Nominatim you can open an issue at https://github.com/osm-search/Nominatim/issues It's unrelated to docker
