### ISSUE TITLE
Configuring update fails due to unknown user: nominatim 

### ISSUE THREAD

**Issue by hbruch** [mediagis/nominatim-docker#41]
Using mediagis/nominatim:3.1 configuring nominatim for updates via 

`docker exec -it nominatim sudo -u nominatim ./src/build/utils/update.php --import-osmosis-all`

fails with sudo: unknown user: nominatim

Seems to me, that user nominatim is added in init.sh by the importing container, but not in the container executing start.sh afterwards.

**Comment by philipkozeny** [comment]
Closing the issue for now, please try the latest version (3.6 at the moment), there have been a lot of changes / fixes, thanks!
