### ISSUE TITLE
Inconsistent results after container recovery.

### ISSUE THREAD

**Issue by ZeroE04** [mediagis/nominatim-docker#411]
**I save a dir（/var/lib/postgresql/14/main） from  a container, and i run a next container mount this dir，but I got two different results. The new's results seems have not imported various external files？ I need to import wiki, gbcode and postcode again after i mount /var/lib/postgresql/14/main?**

1. Use command '...'
sudo docker run --net host -it --shm-size=300g \
  -v /data0/wakui/projects/gis_server/nominatim-docker/4.2.2/main:/var/lib/postgresql/14/main \
  -p 8080:8080 \
  --name nominatim_mount \
  mediagis/nominatim:4.2

**Comment by ZeroE04** [comment]
I manually re import all external files, but the result is still wrong. Why?

**Comment by mtmail** [comment]
> the result is [...] wrong.

You need to be more specific and provide examples.
