### ISSUE TITLE
Use custom UserAgent with curl requests to https://nominatim.org

### ISSUE THREAD

**Issue by lonvia** [mediagis/nominatim-docker#413]
Please be advised that I had to ban the curl user agent from https://nominatim.org/data. For details see https://github.com/osm-search/Nominatim/issues/2929. This affects your docker scripts as far as I can see. Please change your scripts to provide a custom user agent that points back to this repo. This gets you around the block and I can get in touch with you should there ever be an issue.

**Comment by philipkozeny** [comment]
Thanks for the info @lonvia, we have set the custom user agent to `mediagis/nominatim-docker`.
