### ISSUE TITLE
Doesn't install - invalid reference format

### ISSUE THREAD

**Issue by sparra1000** [mediagis/nominatim-docker#42]
From the docker quickstart terminal I following the instructions to install.  I run the command, 

    docker run http://wiki.openstreetmap.org/wiki/nominatim 

and I get this error:

    c:\program files\docker toolbox\docker.exe: invald reference format.

**Comment by Maannniii** [comment]
The author didn't properly document on how to run the image. By the way the question is answered in [Stackoverflow](https://stackoverflow.com/questions/52350248/install-docker-container-docker-run-invalid-reference-format/52350633#52350633).

**Comment by Maannniii** [comment]
Refer [running section](https://github.com/mediagis/nominatim-docker/tree/master/2.5#running) for details on running the image.
