### ISSUE TITLE
disable debug mode in nominatim docker

### ISSUE THREAD

**Issue by mvbelik** [mediagis/nominatim-docker#425]
Greetings, I have a question about how to disable debug mode in nominatim docker. So that it is always turned off, since it is possible to execute any js script
search.php?q=stestme</script><script>alert(1)</script>&debug=zwrtxqvax1uzk79kt8&sji6hyez40=1

**Comment by lonvia** [comment]
There are now patch releases available for Nominatim 3.7, 4.0, 4.1 and 4.2 fixing the problem.

Next time please follow the [proper procedures](https://github.com/osm-search/Nominatim/blob/master/SECURITY.md) for responsible disclosure. Thank you.

**Comment by philipkozeny** [comment]
We've updated the repo with the new version and pushed the update to Docker Hub.
