### ISSUE TITLE
postgres won't start (nominatim-docker 4.2)

### ISSUE THREAD

**Issue by ashley-mort** [mediagis/nominatim-docker#438]
I am having a problem where postgres won't start.  Any ideas on how to investigate what might be going on?  Thanks!

**Desktop / Server:**
 - OS & Version: Red Hat Enterprise Linux Server 7.9 (Maipo)
 - Docker Version: 19.03.12(client) 19.03.8(server)
 - Nominatim Version: 4.2
 

_docker run -it -e PBF_PATH=/nominatim/data/monaco-latest.osm.pbf -p 8080:8080 -v /local/amort/nominatim2:/nominatim/data --name nominatim myArtifactory:8443/docker/nominatim:4.2_
 
+ tailpid=0
+ replicationpid=0
+ trap stopServices SIGTERM TERM INT
+ /app/config.sh
+ id nominatim
+ useradd -m -p qaIACxO6wMR3 nominatim
+ IMPORT_FINISHED=/var/lib/postgresql/14/main/import-finished
+ '[' '!' -f /var/lib/postgresql/14/main/import-finished ']'
+ /app/init.sh
+ OSMFILE=/nominatim/data.osm.pbf
+ CURL='curl -L -A "mediagis/nominatim-docker:4.2.1" --fail-with-body'
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional Wikipedia importance import'
Skipping optional Wikipedia importance import
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional GB postcode import'
Skipping optional GB postcode import
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional US postcode import'
Skipping optional US postcode import
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional Tiger addresses import'
Skipping optional Tiger addresses import
+ '[' '' '!=' '' ']'
+ '[' /nominatim/data/california-latest.osm.pbf '!=' '' ']'
+ echo Reading OSM extract from /nominatim/data/california-latest.osm.pbf
Reading OSM extract from /nominatim/data/california-latest.osm.pbf
+ OSMFILE=/nominatim/data/california-latest.osm.pbf
+ '[' '!' -f /var/lib/postgresql/14/main/PG_VERSION ']'
+ cp /etc/postgresql/14/main/conf.d/postgres-import.conf.disabled /etc/postgresql/14/main/conf.d/postgres-import.conf
+ sudo service postgresql start
postgresql: unrecognized service
+ sudo -E -u postgres createuser -s nominatim
createuser: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
+ sudo -E -u postgres createuser -SDR www-data
createuser: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
+ chown -R nominatim:nominatim /nominatim
+ cd /nominatim
+ '[' '' = true ']'
+ sudo -E -u nominatim nominatim import --osm-file /nominatim/data/california-latest.osm.pbf --threads 16
2023-03-22 22:28:29: Using project directory: /nominatim
2023-03-22 22:28:30: Creating database
createdb: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
2023-03-22 22:28:31: FATAL: Creating new database failed.

**Comment by ashley-mort** [comment]
I get the same problem on nominatim-docker 4.1.  4.0 doesn't have this issue meaning the postgres db starts.

**Comment by ashley-mort** [comment]
_docker run --name nominatimTest -it mediagis/nominatim:4.2 bash
service --status-all_
no services are shown

_docker run --name nominatimTest -it mediagis/nominatim:4.0 bash
service --status-all_
apache-htcacheclean
apache2
binfmt-support
hwclock.sh
postgresql
procps

**Comment by wang0916** [comment]
How is this problem, has it been resolved?

**Comment by okimiko** [comment]
I had the same problem (centos7sp9 with docker 20.10.1) and added _privileged_ parameter (https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) and it worked.
Because I wanted to use this in our swarm cluster I failed again (no _privileged_  support and capabilities did not work).

Finally a docker update (I tried 20.10.9) got it running again :)

**Comment by ashley-mort** [comment]
I think the solution from @okimiko is a good idea but we can't run privileged docker in our production environment.

Currently I've moved on to trying to run this (nominatim-docker:4.2) in kubernetes with helm and there I don't have any of the problems mentioned above.

**Comment by CoWayger** [comment]
same problem... funny is the 3.7, 4.0 version it works just fine. Looks like it is problem with mounting folders into volumes. I tried many combinations of permission (even 777 and root:root), nothing works.

**Comment by CoWayger** [comment]
I found out reason. Be aware that this command:

chown -R nominatim:nominatim /nominatim

will affect all folders mounted into /nominatim/data

So when you have structure like me:
/mnt/NVME/europe.pbf
/mnt/NVME/nominatim-db

then with this settings:
    volumes:
      - /mnt/NVME/nominatim-db:/var/lib/postgresql/14/main
      - /mnt/NVME:/nominatim/data

Nominatim will shortly after start shoot itself in the leg and DB files will have bad user. Solution is simple: create data dir like:

/mnt/NVME/data/europe.pbf
/mnt/NVME/nominatim-db
then with this settings:
    volumes:
      - /mnt/NVME/nominatim-db:/var/lib/postgresql/14/main
      - /mnt/NVME/data:/nominatim/data

Everything works.

**Comment by aliaz0** [comment]
Same problem on 4.1, 4.2, 4.3, 4.4
4.0 is ok
