### ISSUE TITLE
Unable to Update Nominatim 3.0

### ISSUE THREAD

**Issue by fberdejo** [mediagis/nominatim-docker#44]
Currently, Nominatim Docker (Nominatim version 3.0) by mediagis/nominatim. My issue is I cannot update contentiously. I already setup the updates in local.php

I encounter this message.. Updates not set up. Please run ./utils/update.php --init-updates

<?php
 // Paths
 @define('CONST_Postgresql_Version', '9.5');
 @define('CONST_Postgis_Version', '2.2');
 // Website settings
 @define('CONST_Website_BaseURL', '/');
 @define('CONST_Replication_Url', 'http://download.geofabrik.de/asia/philippines-updates');
 @define('CONST_Replication_MaxInterval', '86400');     // Process each update separately, osmosis cannot merge multiple updates
 @define('CONST_Replication_Update_Interval', '86400');  // How often upstream publishes diffs
 @define('CONST_Replication_Recheck_Interval', '900');   // How long to sleep if no update found yet
 @define('CONST_Pyosmium_Binary', '/usr/local/bin/pyosmium-get-changes');

Instruction that I follow. This is working for 8 months
https://hub.docker.com/r/mediagis/nominatim/

Please help me. thank you in advance

**Comment by xi** [comment]
I think the error message is pretty clear. This is missing in the documentation though.
