### ISSUE TITLE
Issue with importing a item 

### ISSUE THREAD

**Issue by MrFiestaxxl** [mediagis/nominatim-docker#443]
We run into the issue that our both containers cannot import anything after April the 2nd. We narrowed it down to this issue 

https://github.com/osm-search/Nominatim/issues/3022
that is fixed with
https://github.com/osm-search/Nominatim/pull/3030

**Comment by philipkozeny** [comment]
Should be fixed with the release of 4.2.3 that we also support since yesterday. Please report back if the problem still occurs or we can close the issue, thanks.

**Comment by MrFiestaxxl** [comment]
Hi, thanks that fixed that issue.
