### ISSUE TITLE
Nomination osm 

### ISSUE THREAD

**Issue by 5212BABA** [mediagis/nominatim-docker#453]
{"place_id":363035109,"parent_place_id":297986933,"osm_type":"N","osm_id":10821302816,"category":"place","type":"town","admin_level":8,"localname":"Tomba kanssa","names":{"name":"Tomba kanssa"},"addresstags":[],"housenumber":null,"calculated_postcode":null,"country_code":"gn","indexed_date":"2023-06-01T15:44:16+00:00","importance":0.30000999999999994,"calculated_importance":0.30000999999999994,"extratags":{"wikidata":"Q116464161","wikipedia":"en:Tomba Kanssa"},"calculated_wikipedia":null,"icon":"https://nominatim.openstreetmap.org/ui/mapicons/poi_place_town.p.20.png","rank_address":16,"rank_search":18,"isarea":false,"centroid":{"type":"Point","coordinates":[-10.1890993,11.7285422]},"geometry":{"type":"Point","coordinates":[-10.1890993,11.7285422]},"address":[{"localname":"Tomba kanssa","place_id":363035109,"osm_id":10821302816,"osm_type":"N","place_type":null,"class":"place","type":"town","admin_level":8,"rank_address":16,"distance":0,"isaddress":true},{"localname":"Région de Kankan","place_id":297986933,"osm_id":3403911,"osm_type":"R","place_type":"state","class":"boundary","type":"administrative","admin_level":4,"rank_address":8,"distance":1.4063516212399311e-5,"isaddress":true},{"localname":"Guinée","place_id":null,"osm_id":null,"osm_type":null,"place_type":null,"class":"place","type":"country","admin_level":null,"rank_address":4,"distance":0,"isaddress":true},{"localname":"gn","place_id":null,"osm_id":null,"osm_type":null,"place_type":null,"class":"place","type":"country_code","admin_level":null,"rank_address":4,"distance":0,"isaddress":false}]}

**Comment by 5212BABA** [comment]
I would like to add the osm nomination result to the database @mausch @leonardehrenfried @sake

**Comment by mtmail** [comment]
OpenStreetMap data is not in github. Use https://www.openstreetmap.org/fixthemap and read a bit about OpenStreetMap a bit https://welcome.openstreetmap.org/ You might want to connect to other nearby OpenStreetMap mapper https://openstreetmap.community/
