### ISSUE TITLE
curl: (5) getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by MALKARAJ** [mediagis/nominatim-docker#455]
curl: (5) getaddrinfo() thread failed to start

**Desktop / Server (please complete the following information):**
 - OS & Version: [e.g. Debian 10]
 - Docker Version: [4.2]
 - Nominatim Version: [4.2.3]

![curl_issue](https://github.com/mediagis/nominatim-docker/assets/62066377/f03a9ef0-9e58-4f2e-a251-a3e35a4ba013)

**Comment by MALKARAJ** [comment]
getting this error kindly let me know

**Comment by MALKARAJ** [comment]
Hi @mtmail  sorry to ping to directly is this commonly occuring one or rare

**Comment by leonardehrenfried** [comment]
Sounds like something is wrong with your network stack inside the container.

You could try to debug by doing a `curl https://www.google.com` inside the container.

**Comment by MALKARAJ** [comment]
> Sounds like something is wrong with your network stack inside the container.
> 
> You could try to debug by doing a `curl https://www.google.com` inside the container.

both docker image is deployed in same machine
mediagis/nominatim:4.0 works but mediagis/nominatim:4.2 doesnt work getting curl error

**Comment by mtmail** [comment]
> is this commonly occuring one or rare

Rare, I've only seen it once. Try `ping` and `traceroute` against the download.geofabrik.de domain, too. Maybe they block network access from your location or IP address.

**Comment by MALKARAJ** [comment]
> > is this commonly occuring one or rare
> 
> Rare, I've only seen it once. Try `ping` and `traceroute` against the download.geofabrik.de domain, too. Maybe they block network access from your location or IP address.

ping to download.geofabrik.de domain is working outiside the docker container , iniside it is not working
