### ISSUE TITLE
Import in Offline Environment

### ISSUE THREAD

**Issue by devinfra1** [mediagis/nominatim-docker#456]
Good afternoon!

I work with an internal development environment completely offline, without internet connection.

I copied the 'brazil-latest.osm.pbf' file to my offline machine and started the import process.

During the import process, I ended up getting stuck when the import tries to request to the address ` https://www.openstreetmap.org/api/0.6/node/10884626565/1`

Is it possible to be carrying out this import process in a completely offline environment? Performing all the necessary downloads before and just passing the path of these files.

**Comment by leonardehrenfried** [comment]
I don't think that it's possible but if I'm honest I don't know why.

You can start execute the import on a connected machine and then use docker import/export to move it to the offline one.

**Comment by leonardehrenfried** [comment]
Well done for figuring it out.

If you can leave more detailed documentation here, I can link to it from the Readme.
