### ISSUE TITLE
Nominatim Replication Error

### ISSUE THREAD

**Issue by cormanttech** [mediagis/nominatim-docker#466]
Hi All,

We encountered an error every time we do the "nominatim replication" command to update our Nominatim. Below is the error message:

ERROR: DB copy thread failed: database error: server closed the connection unexpectedly this probably means the server terminated abnormally before or while processing the request

![Nominatim](https://github.com/mediagis/nominatim-docker/assets/55179774/9ef29a7b-d3cb-4e7f-a014-e1b3b448241f)

Thank you!

**Comment by stouch** [comment]
You should give more information, about your docker run command, the setup/instance/machine you use, the full logs, etc.

**Comment by cormanttech** [comment]
Hi,

We have established the Nominatim server on an AWS EC2 instance running Ubuntu 20.04. I adhered to the installation steps outlined in the following link: https://nominatim.org/release-docs/latest/admin/Installation/ to configure our instance.

Initially, our OpenStreetMap (OSM) setup was functioning smoothly, and we successfully used the 'Nominatim Replication' method for updates. However, we have recently encountered an unexpected error.

The PostgreSQL logs reveal the following:

![image](https://github.com/mediagis/nominatim-docker/assets/55179774/15776b4d-20f8-457f-8385-39970b65475b)

**Comment by mtmail** [comment]
The "invalid record length" can be ignored https://dba.stackexchange.com/questions/256740/invalid-record-length-at-1a2-8f240298-wanted-24-got-0 The "redo starts ... redo done" looks good.

Why the postgresql server stopped (crashed?) might be further up the postgresql logfile or other system logfiles. That's all unrelated to Nominatim, a postgresql forum might be better answering those.
