### ISSUE TITLE
Clear cache ? Some updates don't appear after `nominatim replication --catch-up`

### ISSUE THREAD

**Issue by stouch** [mediagis/nominatim-docker#469]
A recent update has been made on this entry : 
[R7411](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=7411&class=boundary) (about the `name:el` value)

So I ran a nominatim replication today on my nominatim-docker instance. 
It's completed. But now, if I query `details.php?osmid=7411&osmtype=R&format=json&addressdetails=1&keywords=1` I still got the old values.

Is there some cache ? What should I do to clear it ?

**Comment by mtmail** [comment]
Is the replication set to daily (the default)? Then the change (11 hours ago) isn’t part of today‘s change file yet. Wait until after midnight UTC timezone at least.
