### ISSUE TITLE
Setup Finished | ERROR:  relation "public.planet_osm_ways" does not exist 

### ISSUE THREAD

**Issue by sachincredible** [mediagis/nominatim-docker#48]
Getting below error after setup finished.  

Summary of warnings:

  * resetting threads to 2
  * external UK postcode table not found.
  * wikipedia article dump file not found - places will have default importance
  * wikipedia redirect dump file not found - some place importance values may be missing

2018-11-12 23:45:57 == Setup finished.
ERROR:  relation "public.planet_osm_ways" does not exist
STATEMENT:  CREATE INDEX nodes_index ON public.planet_osm_ways USING gin (nodes);
ERROR:  relation "public.planet_osm_ways" does not exist
LOG:  received fast shutdown request
LOG:  aborting any active transactions
FATAL:  terminating autovacuum process due to administrator command
LOG:  autovacuum launcher shutting down
waiting for server to shut down....LOG:  shutting down
...LOG:  database system is shut down
.. done
server stopped

**Comment by sachincredible** [comment]
It was finished successfully and i am able to use search api.

**Comment by HoracioEspinosa** [comment]
same issue here how do you solve this? please
