### ISSUE TITLE
Could not resize shared memory segment

### ISSUE THREAD

**Issue by DDETS-PROJET** [mediagis/nominatim-docker#484]
**Describe the bug**
Hello, I can't install your application on docker. whether it's on a VM or on a machine, it's exactly the same problem that emerges. I have no information regarding this issue and cannot resolve the issue on my own
I have tried at least 3 times with no results.

**To Reproduce**
docker run -it \
  -e PBF_URL=https://download.geofabrik.de/europe/france-latest.osm.pbf \
  -e REPLICATION_URL=https://download.geofabrik.de/europe/france-updates/ \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.3

# here is the error
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 12, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 225, in nominatim
    return get_set_parser().run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 121, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 134, in run
    indexer.index_full(analyse=not args.index_noanalyse)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 140, in index_full
    if self.index_by_rank(26, 30) > 1000:
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 174, in index_by_rank
    total += self._index(runners.RankRunner(rank, analyzer), 20 if rank == 30 else 1)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 210, in _index
    total_tuples = cur.scalar(runner.sql_count_objects())
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 53, in scalar
    self.execute(sql, args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 36, in execute
    super().execute(query, args)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.DiskFull: could not resize shared memory segment "/PostgreSQL.2013621802" to 50438144 bytes: No space left on device

![screen](https://github.com/mediagis/nominatim-docker/assets/72910714/4d4a5d57-136c-47bd-8007-f1346778014b)

Ubuntu 22.04.1
Docker version 24.0.5,  
Nominatim Version: 4.3

Hardware : CPU 4 Core intel 2400 + 4Go RAM + SSD 500 Go with 128 Go swap
VM Hardware : CPU intel 13700K + 32Go RAM + 1 To SSD Nvme + 128Go Swap (same probleme)

**Comment by leonardehrenfried** [comment]
This means you have no space on disk.

Looks like Windows so change your Docker settings so that the VM has more disk.

**Comment by DDETS-PROJET** [comment]
So I have 300 GB of free space on the physical machine and I'm running full Linux and not Windows.
I have no disk overrun, I suggest that the problem comes from postgresSQL during processing

**Comment by leonardehrenfried** [comment]
Sorry to be a bit cranky but we get this error a lot and it's always the disk.

**Comment by DDETS-PROJET** [comment]
I can understand your frustration.

It should be documented and explained, if I had seen it in your documentation, I would not have reported it as a bug and what's more, I haven't seen a similar subject on this subject.

But thank you anyway for your feedback, hoping that this is the right direction

**Comment by leonardehrenfried** [comment]
You're welcome. 

I should probably get away from the computer a bit. :) 

Have a nice evening!

**Comment by DDETS-PROJET** [comment]
Thank you very much for your help, and I totally understand your frustration, I looked badly on my side. Thanks for your help.

**Comment by nikoma** [comment]
When this happens, is there a way to resume? Mine ended at 26th rank with exactly the same error. I had still more than 1TB left on the device.
