### ISSUE TITLE
How to get incremental osm updates within this container?

### ISSUE THREAD

**Issue by jnsone11** [mediagis/nominatim-docker#5]
I'd like to know what I will need to do to get regular updates when osm data changes without recreating the whole container. Cheers Jens

**Comment by winsento** [comment]
@jnsone11 now you can update yours data, see here https://github.com/mediagis/nominatim-docker#update

**Comment by jnsone11** [comment]
awesome!

**Comment by winsento** [comment]
@jnsone11 do not foget configure valid `CONST_Replication_Url` in local.php

**Comment by jnsone11** [comment]
Thanks for the information.
Is there a way to update my existing container without recreating it? It took 2 days + lots of ressources.

**Comment by winsento** [comment]
I think the best way to re-build it and see if everything is ok.
