### ISSUE TITLE
 * Error: Config owner (postgres:106) and data owner (root:0) do not match, and config owner is not root

### ISSUE THREAD

**Issue by actongorton** [mediagis/nominatim-docker#51]
When running the command: 
`docker run --restart=always -p 6432:5432 -p 7070:8080 -d -v /Users/agorton/nominatimdata:/var/lib/postgresql/9.5/main nominatim bash /app/start.sh`
The following error occurs:
```
* Starting PostgreSQL 9.5 database server
 * Error: Config owner (postgres:106) and data owner (root:0) do not match, and config owner is not root
   ...fail!
 * Starting Apache httpd web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using xxx.xxx.xxx.xxx. Set the 'ServerName' directive globally to suppress this message
```

**Comment by AshtonIzmev** [comment]
I had the same issue but solved with the right path.
Can you check /Users/agorton/nominatimdata content ? Does it contain postgresdata/ folder with the right permissions (700 + messagebus owner) ?

**Comment by winsento** [comment]
Ping @karlvr

**Comment by karlvr** [comment]
Hi! This sounds like it's a different issue to the one I referenced in #50, but probably part of the same discussion... should the container standardise on a single user account to own everything and run everything as?

**Comment by verbeeckjan** [comment]
I have the same issue, how do I fix this @karlvr ?

**Comment by petenickless** [comment]
Any further details about how to resolve this issue? 

I'm trying to run the project in a digital ocean container using a volume (called data) to store data and getting the same error as @actongorton.  

``` * Starting PostgreSQL 11 database server
 * Error: Config owner (postgres:102) and data owner (root:0) do not match, and config owner is not root
   ...fail!```

`docker run --restart=always -p 6432:5432 -p 7070:8080 --name nominatim -v data:/var/lib/postgresql/11/main nominatim bash /app/start.sh` 

The volume appears to be mounted

`docker inspect nominatim`

```        "Mounts": [
            {
                "Type": "volume",
                "Name": "data",
                "Source": "/var/lib/docker/volumes/data/_data",
                "Destination": "/var/lib/postgresql/11/main",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],```

Here's permissions in the mounted volume.  

```drwxr-xr-x  3 root root     4096 Jun 12 16:07 .
drwxr-xr-x  1 root root     4096 Jun 12 15:15 ..
-rw-------  1 root root       24 Jun 12 15:15 .bash_history
-rw-r--r--  1 root root  1518314 Jun 11 23:20 andorra-latest.osm.pbf
drwx------ 19  102  104     4096 Jun 12 16:08 postgresdata
-rw-r--r--  1 root root 70883484 Jun 11 23:32 wales-latest.osm.pbf```

**Comment by petenickless** [comment]
For anyone experiencing the issue with Digital Ocean I resolved it using one of Digital Oceans block storage mounted volume.

**Comment by evicent** [comment]
Any of you installed nominatim docker just after installing docker? if so, probably the fact that you were running docker using sudo could affect the permssion. Remove images, docker, and install docker and DO NOT run with sudo the first time (the hello-world initial test). Add your user to docker group then log off login and proceed to install nominatim. This worked for me!. 

Hope this help!

**Comment by Felix-Tr** [comment]
I had the same problem and in my case it was enough to change the ownership before starting postgresql. 
So changing the start.sh file to should work:

**start.sh:**
<pre>
#!/bin/bash

stopServices() {
        service apache2 stop
        service postgresql stop
}
trap stopServices TERM

# Change Ownership of mounted folder to pstgres user
<b>chown postgres /var/lib/postgresql/12/main</b>

service postgresql start
service apache2 start

# fork a process and wait for it
tail -f /var/log/postgresql/postgresql-12-main.log &
wait
</pre>

I don't exactly understand why this happens in this case, I think on windows it is a known Issue but I never experienced it on linux so far.

I'm using:
Nominatim Docker Version 3.5
Ubuntu 18.04.4 LTS
Docker version 19.03.6

**Comment by philipkozeny** [comment]
We've changed quite a lot with the latest releases (3.6 & 3.7). You can check the latest version out and give us feedback, the problem should be fixed.
