### ISSUE TITLE
VIewbox does not work

### ISSUE THREAD

**Issue by swidersky** [mediagis/nominatim-docker#514]
When i search results in specifix viewbox it does not work
I installed nominatim using following command:

docker run -it \
  -e PBF_URL=https://download.geofabrik.de/europe/poland-latest.osm.pbf \
  -e REPLICATION_URL=https://download.geofabrik.de/europe/poland-updates/ \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.3

When im executing this request:
https://nominatim.openstreetmap.org/search.php?q=przedszkole&viewbox=17.00635%2C51.07597%2C17.10231%2C51.05758&bounded=1&format=jsonv2

im getting results:

but when i do the same for my server
http://localhost:8080/search.php?q=przedszkole&viewbox=17.00635%2C51.07597%2C17.10231%2C51.05758&bounded=1&format=jsonv2

**Comment by mtmail** [comment]
nominatim.openstreetmap.org runs the git master version, not the stabel 4.3.1 version. If the results improved, that's great, then it will likely be part of the next release.

**Comment by ghevge** [comment]
Still doesn't seem to work. If I look for CVS stores in a box overlapping New York, i get nothing back.

https://nominatim.openstreetmap.org/search?q=CVS&addressdetails=1&limit=10000&format=xml&viewbox=74.01%2C39.01%2C72.01%2C41.01&bounded=1

**Comment by mtmail** [comment]
@ghevge  74.01,39.01 isn't even close to New York City, USA. You probably mean -74.
