### ISSUE TITLE
Import Style Customization

### ISSUE THREAD

**Issue by LawrenceWlt** [mediagis/nominatim-docker#535]
I need to import a few extra tags but I don't see any option to customize import styles. It is either you have all the extra tags or none at all.

**Comment by mtmail** [comment]
The `NOMINATIM_IMPORT_STYLE` setting in the `.env` can be a name or a file name. As far as I see the [Docker script](https://github.com/mediagis/nominatim-docker/blob/master/4.3/config.sh) copies the Docker environment variable `IMPORT_STYLE` into `NOMINATIM_IMPORT_STYLE` so it should just work.

You can copy one of the existing styles and add your own rules in a new file. https://nominatim.org/release-docs/4.3/customize/Import-Styles/

**Comment by LawrenceWlt** [comment]
Thanks. Let me try that.

**Comment by LawrenceWlt** [comment]
Passing the file path worked. However, the tag that I desired to be part of the extra tags didn't show up. In my case am trying to add maxspeed as follows: ` extra_keys = {'wikipedia', 'wikipedia:*', 'wikidata', 'capital', 'area', 'maxspeed'}` any help will be highly appreciated. Thanks

**Comment by mtmail** [comment]
Will be answered at https://github.com/osm-search/Nominatim/issues/3359
