### ISSUE TITLE
Parallelize GitHub CI to cut down on overall timing

### ISSUE THREAD

**Issue by carlomion** [mediagis/nominatim-docker#551]
**Is your feature request related to a problem? Please describe.**
The GitHub CI actions require quite a bit of time to be run (20-30 min), since each step tries to first boot up the Nominatim image, then run the intended test against it.

**Describe the solution you'd like**
Execute the docker image tests in parallel, whenever possible, to cut down on the amount of time required for the overall pipeline.

**Additional context**
Given that once the Docker image is built it is reused in subsequent `docker run` invocations, it should be possible to built the image once, then share it in subsequent parallel GitHub jobs, each focusing on a singular test.

**Comment by leonardehrenfried** [comment]
I would absolutely love it if you would contribute this.
