### ISSUE TITLE
Nominatim 4.5 

### ISSUE THREAD

**Issue by zanetdev** [mediagis/nominatim-docker#584]
**Is your feature request related to a problem? Please describe.**
Nominatim 4.5 was released a month ago and seems to be quite a large step toward the v5 goals. 

In 4.5 there is response customization functionality related to the python frontend replacement that I would like to access without having to revert to an installation on the host. Specifically this was suggested by Sarah Hoffman for being able to return building level (18) AND street level (16) data in one request.

**Describe the solution you'd like**
Has a release of mediagis/nominatim-docker 4.5 been considered / perhaps in progress?

**Describe alternatives you've considered**
There are no real 'good' alternatives available. Double calls to the DB would be problematic.

**Additional context**
N/A

**Comment by philipkozeny** [comment]
Yes, we are currently working on supporting the release of version 4.5. Additionally, with the new major Ubuntu LTS release, there’s more involved than simply updating the version number, as we need to ensure compatibility and transition smoothly to the new environment.

**Comment by markdavieswlt** [comment]
Also came here for the same, glad it's in progress 
Thanks
