### ISSUE TITLE
error path osm file

### ISSUE THREAD

**Issue by magavel** [mediagis/nominatim-docker#64]
When running the command:

```
docker run -t -v /Users/avelferonpapel/Downloads/nominatim-docker-master/3.3/data:/data  nominatim  sh /app/init.sh /data/merged.osm.pbf postgresdata 4
```
The following error occurs:
```
server started
NOTICE:  database "nominatim" does not exist, skipping
DROP DATABASE
ERROR: the path supplied to --osm-file does not exist
string(46) "the path supplied to --osm-file does not exist"
```
Someone has a solution?
many thanks
BR

**Comment by dlucia** [comment]
The link `/Users/avelferonpapel/Downloads/nominatim-docker-master/3.3/data:/data` you are doing is not correct.
You should map to any local directory where you the import can write (It will write the postgres content and flatnode file if you enable it).
Also `/data/merged.osm.pbf` is just a placeholder. You need to download a osm.pbf file and provide as input for the extraction
