### ISSUE TITLE
SQLSTATE[HY000]: General error: 7 server closed the connection unexpectedly

### ISSUE THREAD

**Issue by grachevko** [mediagis/nominatim-docker#67]
In config with separate containers for apache and postgres 3 of 7 requests crash with error
`SQLSTATE[HY000]: General error: 7 server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.`

UPDATE:
Sometimes error is:
`SQLSTATE[HY000]: General error: 7 SSL SYSCALL error: EOF detected`

Version 3.3

**Comment by shaphiro** [comment]
Did you solve your problem?

**Comment by philipkozeny** [comment]
We've changed quite a lot with the latest releases (3.6 & 3.7). You can check the latest version out and give us feedback, the problem should be fixed.

**Comment by DarckBlezzer** [comment]
I restart postgres

`sudo service postgresql restart`

And have the 
`SQLSTATE[HY000]: General error: 7 server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.`

and then try the command  in the nominatim project, that contain website folder

 `nominatim reverse --lat 25.44517 --lon -101.1893632`

and worked

Then restart apache

`sudo service apache2 restart`

And didn't get any error
