### ISSUE TITLE
Is it possible to reduce the number of installed packages ?

### ISSUE THREAD

**Issue by fungiboletus** [mediagis/nominatim-docker#7]
Hei, I just compiled the container and I'm guessing a lot of packages are not necessary, especially the Gnome stuff, mysql, or the sound theme.

This is the list of packages that are additionally  installed in the container :

 * `libexpat1`
 * `libssl1.0.0`
 * `libroken18-heimdal`
 * `libasn1-8-heimdal`
 * `libkrb5support0`
 * `libk5crypto3`
 * `libkeyutils1`
 * `libkrb5-3`
 * `libgssapi-krb5-2`
 * `libidn11`
 * `libhcrypto4-heimdal`
 * `libheimbase1-heimdal`
 * `libwind0-heimdal`
 * `libhx509-5-heimdal`
 * `libkrb5-26-heimdal`
 * `libheimntlm0-heimdal`
 * `libgssapi3-heimdal`
 * `libsasl2-modules-db`
 * `libsasl2-2`
 * `libldap-2.4-2`
 * `librtmp0`
 * `libcurl3-gnutls`
 * `libglib2.0-0`
 * `libdbus-glib-1-2`
 * `libedit2`
 * `libelf1`
 * `libsystemd-daemon0`
 * `libapparmor1`
 * `libsystemd-login0`
 * `dbus`
 * `systemd-shim`
 * `libparted0debian1`
 * `libpolkit-gobject-1-0`
 * `libusb-1.0-0`
 * `libxau6`
 * `libxdmcp6`
 * `libxcb1`
 * `libx11-data`
 * `libx11-6`
 * `libxext6`
 * `libxml2`
 * `libxmuu1`
 * `ntfs-3g`
 * `sgml-base`
 * `sgml-base`
 * `autoconf-archive`
 * `libapr1`
 * `libaprutil1`
 * `liblzo2-2`
 * `libnettle4`
 * `libarchive13`
 * `libasan0`
 * `libasound2-data`
 * `libasound2`
 * `libasyncns0`
 * `libatasmart4`
 * `libatk1.0-data`
 * `libatk1.0-0`
 * `libatspi2.0-0`
 * `libatk-bridge2.0-0`
 * `libgtk2.0-common`
 * `fonts-dejavu-core`
 * `fontconfig-config`
 * `libfreetype6`
 * `libfontconfig1`
 * `libpixman-1-0`
 * `libxcb-render0`
 * `libxcb-shm0`
 * `libxrender1`
 * `libcairo2`
 * `libavahi-common-data`
 * `libavahi-common3`
 * `libavahi-client3`
 * `libcups2`
 * `libjpeg-turbo8`
 * `libjpeg8`
 * `libjasper1`
 * `libjbig0`
 * `libtiff5`
 * `libgdk-pixbuf2.0-common`
 * `libgdk-pixbuf2.0-0`
 * `libthai-data`
 * `libdatrie1`
 * `libthai0`
 * `fontconfig`
 * `libpango-1.0-0`
 * `libgraphite2-3`
 * `libharfbuzz0b`
 * `libpangoft2-1.0-0`
 * `libpangocairo-1.0-0`
 * `libxcomposite1`
 * `libxfixes3`
 * `libxcursor1`
 * `libxdamage1`
 * `libxi6`
 * `libxinerama1`
 * `libxrandr2`
 * `shared-mime-info`
 * `libgtk2.0-0`
 * `openssl`
 * `ca-certificates`
 * `libnspr4`
 * `tzdata-java`
 * `java-common`
 * `liblcms2-2`
 * `libpcsclite1`
 * `libogg0`
 * `libflac8`
 * `libvorbis0a`
 * `libvorbisenc2`
 * `libsndfile1`
 * `libwrap0`
 * `libpulse0`
 * `libsctp1`
 * `libgif4`
 * `x11-common`
 * `libglapi-mesa`
 * `libx11-xcb1`
 * `libxcb-dri2-0`
 * `libxcb-dri3-0`
 * `libxcb-glx0`
 * `libxcb-present0`
 * `libxcb-sync1`
 * `libxshmfence1`
 * `libxxf86vm1`
 * `libgl1-mesa-glx`
 * `libatomic1`
 * `libavahi-glib1`
 * `libbonobo2-common`
 * `libgmp10`
 * `libisl10`
 * `libcloog-isl4`
 * `libmpfr4`
 * `libmpc3`
 * `cpp-4.8`
 * `cpp`
 * `libidl-common`
 * `libidl0`
 * `liborbit-2-0`
 * `liborbit2`
 * `libbonobo2-0`
 * `libboost-atomic1.54.0`
 * `libboost-system1.54.0`
 * `libboost-chrono1.54.0`
 * `libboost-date-time1.54.0`
 * `libboost-filesystem1.54.0`
 * `libboost-serialization1.54.0`
 * `libboost-thread1.54.0`
 * `libcairo-gobject2`
 * `libltdl7`
 * `libtdb1`
 * `libvorbisfile3`
 * `sound-theme-freedesktop`
 * `libcanberra0`
 * `libcolord1`
 * `libcurl3`
 * `libdap11`
 * `libdapclient3`
 * `libdconf1`
 * `libpciaccess0`
 * `libdrm-intel1`
 * `libdrm-nouveau2`
 * `libdrm-radeon1`
 * `libepsilon1`
 * `libexif12`
 * `libfontenc1`
 * `gconf2-common`
 * `libgconf-2-4`
 * `libvpx1`
 * `libxpm4`
 * `libgd3`
 * `libquadmath0`
 * `libgfortran3`
 * `libllvm3.4`
 * `libgl1-mesa-dri`
 * `psmisc`
 * `libpython2.7-minimal`
 * `python2.7-minimal`
 * `libpython2.7-stdlib`
 * `python2.7`
 * `python-minimal`
 * `libpython-stdlib`
 * `python`
 * `libgomp1`
 * `libgphoto2-port10`
 * `libgphoto2-6`
 * `libgssrpc4`
 * `dconf-service`
 * `dconf-gsettings-backend`
 * `libgtk-3-common`
 * `libwayland-client0`
 * `libwayland-cursor0`
 * `libxkbcommon0`
 * `libgtk-3-0`
 * `libgudev-1.0-0`
 * `libhdf5-7`
 * `libicu52`
 * `libieee1284-3`
 * `libitm1`
 * `libkadm5clnt-mit9`
 * `libkdb5-7`
 * `libkadm5srv-mit9`
 * `liblua5.1-0`
 * `liblua5.2-0`
 * `mysql-common`
 * `libmysqlclient18`
 * `libodbc1`
 * `libpolkit-agent-1-0`
 * `libpolkit-backend-1-0`
 * `libpoppler44`
 * `acl`
 * `libsane-common`
 * `libv4lconvert0`
 * `libv4l-0`
 * `libsane`
 * `libsecret-common`
 * `libsecret-1-0`
 * `libsigsegv2`
 * `libfreexl1`
 * `libgeos-3.4.2`
 * `libgeos-c1`
 * `proj-data`
 * `libproj0`
 * `libspatialite5`
 * `libtsan0`
 * `libudisks2-0`
 * `libxcb-shape0`
 * `libxerces-c3.1`
 * `libxft2`
 * `libxslt1.1`
 * `libxv1`
 * `libxxf86dga1`
 * `libpq5`
 * `lsof`
 * `libgusb2`
 * `libcolorhug1`
 * `libtxc-dxtn-s2tc0`
 * `libwebp5`
 * `dosfstools`
 * `groff-base`
 * `krb5-locales`
 * `libglib2.0-data`
 * `libsasl2-modules`
 * `manpages`
 * `openssh-client`
 * `parted`
 * `rsync`
 * `xauth`
 * `xml-core`
 * `libxml-commons-resolver1.1-java`
 * `libxml-commons-external-java`
 * `libxerces2-java`
 * `libaprutil1-dbd-sqlite3`
 * `libaprutil1-ldap`
 * `apache2-bin`
 * `apache2-data`
 * `apache2`
 * `libaspectj-java`
 * `m4`
 * `autoconf`
 * `autotools-dev`
 * `automake`
 * `binutils`
 * `libc-dev-bin`
 * `linux-libc-dev`
 * `libc6-dev`
 * `libgcc-4.8-dev`
 * `gcc-4.8`
 * `gcc`
 * `libstdc++-4.8-dev`
 * `g++-4.8`
 * `g++`
 * `make`
 * `libtimedate-perl`
 * `libdpkg-perl`
 * `xz-utils`
 * `patch`
 * `dpkg-dev`
 * `build-essential`
 * `cmake-data`
 * `cmake`
 * `curl`
 * `desktop-file-utils`
 * `libfakeroot`
 * `fakeroot`
 * `fonts-dejavu-extra`
 * `libjaxp1.3-java`
 * `libxalan2-java`
 * `libapache-pom-java`
 * `libbsf-java`
 * `libavalon-framework-java`
 * `libcommons-io-java`
 * `libcommons-parent-java`
 * `libcommons-logging-java`
 * `unzip`
 * `java-wrappers`
 * `libxmlgraphics-commons-java`
 * `liberror-perl`
 * `git-man`
 * `git`
 * `glassfish-javaee`
 * `gvfs-common`
 * `gvfs-libs`
 * `hicolor-icon-theme`
 * `comerr-dev`
 * `krb5-multidev`
 * `libalgorithm-diff-perl`
 * `libalgorithm-diff-xs-perl`
 * `libalgorithm-merge-perl`
 * `libblas3`
 * `liblapack3`
 * `libarpack2`
 * `libarmadillo4`
 * `libasm3-java`
 * `libatinject-jsr330-api-java`
 * `libboost1.54-dev`
 * `libboost-atomic1.54-dev`
 * `libboost-chrono1.54-dev`
 * `libboost-serialization1.54-dev`
 * `libboost-date-time1.54-dev`
 * `libboost-dev`
 * `libboost-system1.54-dev`
 * `libboost-filesystem1.54-dev`
 * `libboost-filesystem-dev`
 * `libboost-filesystem-dev`
 * `libboost-system-dev`
 * `libboost-thread1.54-dev`
 * `libboost-thread-dev`
 * `libbz2-dev`
 * `libc3p0-java`
 * `libcglib-java`
 * `libcommons-codec-java`
 * `libcommons-collections3-java`
 * `libxz-java`
 * `libcommons-compress-java`
 * `libcommons-pool-java`
 * `libcommons-dbcp-java`
 * `libecj-java`
 * `libexpat1-dev`
 * `libfile-fcntllock-perl`
 * `libhdf4-0-alt`
 * `liburiparser1`
 * `libkml0`
 * `libnetcdfc7`
 * `libogdi3.2`
 * `libgeos-dev`
 * `libgeos++-dev`
 * `libosgi-core-java`
 * `libosgi-foundation-ee-java`
 * `libservlet2.5-java`
 * `libgeronimo-jta-1.1-spec-java`
 * `libgphoto2-l10n`
 * `libgtk-3-bin`
 * `libgtk2.0-bin`
 * `libjline-java`
 * `libltdl-dev`
 * `libtinfo-dev`
 * `libreadline6-dev`
 * `libreadline-dev`
 * `liblua5.1-0-dev`
 * `liblua5.2-dev`
 * `libluabind0.9.1`
 * `libluabind-dev`
 * `liblwgeom-2.1.2`
 * `libmysql-java`
 * `libossp-uuid16`
 * `libplexus-classworlds-java`
 * `libpostgresql-jdbc-java`
 * `libpostgis-java`
 * `zlib1g-dev`
 * `libssl-dev`
 * `libpq-dev`
 * `librhino-java`
 * `libsaxon-java`
 * `libssl-doc`
 * `libtomcat6-java`
 * `libtool`
 * `libxml2-dev`
 * `lksctp-tools`
 * `lua5.1`
 * `manpages-dev`
 * `libjpf-java`
 * `libspring-core-java`
 * `libspring-beans-java`
 * `libaopalliance-java`
 * `libspring-aop-java`
 * `libspring-expression-java`
 * `libspring-context-java`
 * `libspring-transaction-java`
 * `libspring-jdbc-java`
 * `libprotobuf-java`
 * `libosmpbf-java`
 * `pkg-config`
 * `postgresql-client-common`
 * `postgresql-client-9.3`
 * `ssl-cert`
 * `postgresql-common`
 * `postgresql-9.3-postgis-scripts`
 * `tcpd`
 * `gdisk`
 * `libproj-dev`
 * `libspring-instrument-java`
 * `proj-bin`
 * `libxtst6`
 * `dbus-x11`
 * `libice6`
 * `libsm6`
 * `libxt6`
 * `libxmu6`
 * `libxaw7`
 * `at-spi2-core`
 * `x11-utils`
 * `udisks2`
 * `gvfs-daemons`
 * `gvfs`
 * `postgresql-9.3`
 * `postgresql`
 * `postgresql-contrib-9.3`
 * `postgresql-contrib`
 * `postgresql-server-dev-9.3`
 * `systemd-services`
 * `libpam-systemd`
 * `policykit-1`
 * `colord`
 * `policykit-1-gnome`
 * `default-jre-headless`
 * `default-jre`
 * `gconf-service`
 * `libgnome2-bin`
 * `odbcinst`
 * `odbcinst1debian2`
 * `php5-json`
 * `php5-cli`
 * `php5-readline`
 * `ant`
 * `ant-optional`
 * `aspectj`
 * `libbatik-java`
 * `libfop-java`
 * `fop`
 * `libapache2-mod-php5`
 * `libgconf2-4`
 * `libgdal1h`
 * `libgeronimo-ejb-3.0-spec-java`
 * `libgeronimo-jms-1.1-spec-java`
 * `libosgi-compendium-java`
 * `libgeronimo-osgi-support-java`
 * `libgeronimo-validation-1.0-spec-java`
 * `osmosis`
 * `php-pear`
 * `php-db`
 * `php5`
 * `postgis`
 * `postgresql-9.3-postgis-2.1`
 * `rhino`
 * `libnss3-nssdb`
 * `libnss3`
 * `ca-certificates-java`
 * `openjdk-7-jre-headless`
 * `libatk-wrapper-java`
 * `libatk-wrapper-java-jni`
 * `openjdk-7-jre`
 * `gconf-service-backend`
 * `gconf2`
 * `libgnomevfs2-common`
 * `libgnomevfs2-0`
 * `libgnome2-common`
 * `libgnome2-0`
 * `libgeronimo-jpa-2.0-spec-java`

**Comment by philipkozeny** [comment]
This was done with the release of 3.5
