### ISSUE TITLE
Wrong CONST_Database_DSN in local.php

### ISSUE THREAD

**Issue by binakot** [mediagis/nominatim-docker#78]
Hello! I have a question about version 3.3.

There is [row](https://github.com/mediagis/nominatim-docker/blob/master/3.3/local.php#L13) with

```php
@define('CONST_Database_DSN', 'pgsql:host=192.168.1.128;port=6432;user=nominatim;password=password1234;dbname=nominatim'); <driver>:host=<host>;port=<port>;user=<username>;password=<password>;dbname=<database>
```

But in [readme](https://github.com/mediagis/nominatim-docker/tree/master/3.3) it says to uncomment the line

```php
@define('CONST_Database_DSN', 'pgsql://nominatim:password1234@192.168.1.128:6432/nominatim'); // <driver>://<username>:<password>@<host>:<port>/<database>
```

What is correct?

```
pgsql://nominatim:password1234@192.168.1.128:6432/nominatim
```

VS 

```
pgsql:host=192.168.1.128;port=6432;user=nominatim;password=password1234;dbname=nominatim
```

**Comment by mtmail** [comment]
Starting Nominatim 3.3. the syntax changed, the format with the `key=valus` pairs is required.

**Comment by binakot** [comment]
> Starting Nominatim 3.3. the syntax changed, the format with the `key=valus` pairs is required.

You mean this one: `pgsql:host=192.168.1.128;port=6432;user=nominatim;password=password1234;dbname=nominatim`

**Comment by mtmail** [comment]
Yes, Nominatim uses PHP PDO for connection management https://www.php.net/manual/en/ref.pdo-pgsql.connection.php

**Comment by philipkozeny** [comment]
Fixed with https://github.com/mediagis/nominatim-docker/commit/05532d6493deb3cad66fc41a4715162c3f6858e9.
