### ISSUE TITLE
POI search does not work

### ISSUE THREAD

**Issue by aerotypebharat** [mediagis/nominatim-docker#79]
I installed as described and everything works except for POI search it don't work. eg.
http://localhost:7070/search?format=json&q=[Hotel]&limit=50&bounded=1&viewbox=82.077664395592,28.43665715,82.877664395592,27.63665715. It return empty array as response but same query works in https://nominatim.openstreetmap.org/

**Comment by mtmail** [comment]
See “If you want to be able to search for places by their type through special key phrases you also need to enable these key phrases like this:“ on https://nominatim.org/release-docs/latest/admin/Import-and-Update/

**Comment by aerotypebharat** [comment]
Thanks,  will follow through the instruction.

**Comment by aerotypebharat** [comment]
Thanks @mtmail  I got it working now. Exec into the container, inside build dir `./utils/specialphrases.php --wiki-import > specialphrases.sql` and as user postgres  `psql -d nominatim -f specialphrases.sql`.  But I  think these script can be part of init.sh while creating the docker imagae.
