### ISSUE TITLE
Can not import EU latest

### ISSUE THREAD

**Issue by ichionid** [mediagis/nominatim-docker#8]
The whole process works flawlessly for Monaco. 
However when it comes to changing to EU's latest:
ENV PBF_DATA http://download.geofabrik.de/europe-latest.osm.pbf

The build is failing with the following error:

**Reading in file: /app/src/data.osm.pbf
Using PBF parser.
node cache: stored: 0(-nan%), storage efficiency: -nan% (dense blocks: 0, sparse nodes: 0), hit rate: -nan%
Osm2pgsql failed due to ERROR: PBF error: invalid BlobHeader size (> max_blob_header_size)**

ERROR: Error executing external command: /app/src/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 1207 -P 5432 -d nominatim /app/src/data.osm.pbf
Error executing external command: /app/src/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 1207 -P 5432 -d nominatim /app/src/data.osm.pbf
The command '/bin/sh -c service postgresql start &&     sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='nominatim'" | grep -q 1 || sudo -u postgres createuser -s nominatim &&     sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='www-data'" | grep -q 1 || sudo -u postgres createuser -SDR www-data &&     sudo -u postgres psql postgres -c "DROP DATABASE IF EXISTS nominatim" &&     useradd -m -p password1234 nominatim &&     chown -R nominatim:nominatim ./src &&     sudo -u nominatim ./src/utils/setup.php --osm-file /app/src/data.osm.pbf --all --threads 2 &&     service postgresql stop' returned a non-zero code: 255

In the beginning I though it was a RAM issue so I pumped it up to 120 GB!

But it seems that it is more of a postegres params issue. Any idea?

**Comment by ImreSamu** [comment]
>But it seems that it is more of a postegres params issue. Any idea?
>Osm2pgsql failed due to ERROR: PBF error: invalid BlobHeader size (> max_blob_header_size)

imho : probably a download error  ( and problem with reading the input osm file )

Maybe an `md5sum` check will be helpful detecting this type of errors. The md5sum info can be downloaded from http://download.geofabrik.de/europe.html website:
  *  http://download.geofabrik.de/europe-latest.osm.pbf.md5

**Comment by maxze** [comment]
I ran into the same issue. It's not the pbf-file itself as I've tried using it in helvalius' docker container for nominatim and it seems to work just fine. Must be something else.

**Comment by giantamoeba** [comment]
I had exactly the same problem with germany-latest, it turned out to be a download error. The original http://download.geofabrik.de/europe/germany-latest.osm.pbf had moved to http://ftp5.gwdg.de/pub/misc/openstreetmap/download.geofabrik.de/germany-latest.osm.pbf

Using the new correct file works now but I am facing the next problem described in #10

**Comment by thomasnordquist** [comment]
This should fix your issue https://github.com/helvalius/nominatim-docker/pull/18

@giantamoeba also got it right

Curl does not follow redirect by default
If you try to open http://download.geofabrik.de/europe/germany-latest.osm.pbf you will be redirected (via HTTP 302) to http://ftp5.gwdg.de/pub/misc/openstreetmap/download.geofabrik.de/germany-latest.osm.pbf
Avoiding this redirect will solve the issue.

**Comment by Bakaniko** [comment]
Hi,
Actually, I had the same problem today with Europe dataset.

I checked past issues so I found this specific one and change the url from https://download.geofabrik.de/europe-latest.osm.pbf to https://ftp5.gwdg.de/pub/misc/openstreetmap/download.geofabrik.de/europe-latest.osm.pbf

I think it is worth it to document that for large datasets, there is a redirection and that curl don't accept redirections.
Especially with latest version of nominatim-docker who specifically download the data (maybe we can have use a local uri, but I'm not sure).

**Comment by leonardehrenfried** [comment]
curl _does_ follow redirects if you pass the `-L` flag which we do: https://github.com/mediagis/nominatim-docker/blob/master/3.6/init.sh#L28

Can you double-check your issue?

**Comment by philipkozeny** [comment]
I also ran the 3.6 image with the European dataset at least 10 times now without a problem. Do you have a more specific error log?

**Comment by Bakaniko** [comment]
Hi, 

I tried to reproduce this morning and I didn't get the error this time.
But Friday I had this one:

```bash
Fri Apr 23 11:30:25 UTC 2021
Error response from daemon: No such container: nominatim
0b98f53a84a1f798bff77d7759cf1e792126e9e6
+ trap stopServices TERM
+ /app/config.sh
+ id nominatim
+ useradd -m -p very_secure_password nominatim
+ IMPORT_FINISHED=/var/lib/postgresql/12/main/import-finished
+ '[' '!' -f /var/lib/postgresql/12/main/import-finished ']'
+ /app/init.sh
+ DATA_DIR=/app/src/data
+ OSMFILE=/app/src/data/data.osm.pbf
+ '[' false = true ']'
+ echo 'Skipping optional Wikipedia importance import'
Skipping optional Wikipedia importance import
+ '[' true = true ']'
+ curl https://www.nominatim.org/data/gb_postcode_data.sql.gz -o /app/src/data/gb_postcode_data.sql.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 35.0M  100 35.0M    0     0  55.9M      0 --:--:-- --:--:-- --:--:-- 55.8M
+ '[' '' = true ']'
+ echo 'Skipping optional US postcode import'
Skipping optional US postcode import
+ echo Downloading OSM extract from https://download.geofabrik.de/europe-latest.osm.pbf
Downloading OSM extract from https://download.geofabrik.de/europe-latest.osm.pbf
+ curl -L https://download.geofabrik.de/europe-latest.osm.pbf --create-dirs -o /app/src/data/data.osm.pbf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   270  100   270    0     0   2700      0 --:--:-- --:--:-- --:--:--  2700
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
Fri Apr 23 11:30:27 UTC 2021
```
