### ISSUE TITLE
Building Nominatim db and running the container at the same time

### ISSUE THREAD

**Issue by mbrucher** [mediagis/nominatim-docker#80]
I haven't found any information on this on Nominatim website or here.

Is it possible to use the container with Nominatim, while I'm building the databse on a local folder? The reason is that I started the process on the full data, but it takes weeks to run, but Id like to start using the image because I don't want to test my apps against an official or free registry (ToU and other reasons like these).

**Comment by ganeshkrishnan1** [comment]
You will run into issues with postgress and rolling back data. Avoid if possible. Else you can start using it while the indexes are being built
