### ISSUE TITLE
Initializing docker database - --osm-file does not exist

### ISSUE THREAD

**Issue by macieg** [mediagis/nominatim-docker#81]
Or I'm doing something wrong or there is a bug in version 3.3 on mac os (10.14.5).

I've downloaded _poland-latest.osm.pbf_ and put it into a folder with path 
/Users/me/repos/geocoding/data/poland

And then I've build the image and then I've run the following command:

_me $ docker run -t -v /Users/me/repos/geocoding/data/poland:/data nominatim  sh /app/init.sh /data/merged.osm.pbf postgresdata 4
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /data/postgresdata ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/11/bin/pg_ctl -D /data/postgresdata -l logfile start

waiting for server to start....2019-07-09 06:39:53.426 UTC [27] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-07-09 06:39:53.427 UTC [27] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2019-07-09 06:39:53.427 UTC [27] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2019-07-09 06:39:53.430 UTC [27] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-07-09 06:39:53.491 UTC [28] LOG:  database system was shut down at 2019-07-09 06:39:50 UTC
2019-07-09 06:39:53.514 UTC [27] LOG:  database system is ready to accept connections
 done
server started
NOTICE:  database "nominatim" does not exist, skipping
DROP DATABASE
**ERROR: the path supplied to --osm-file does not exist
string(46) "the path supplied to --osm-file does not exis**t"_

**Comment by mbrucher** [comment]
/data/merged.osm.pbf -> /data/poland-latest.osm.pbf
Except if you merged the file before?

**Comment by abandin-stratio** [comment]
Same here. Guide is not very clear at this point. I place my pbf file from spain, in ~/nominatim-data/spain-latest.osm.pbf and i get the same error after the first initialization.
BR!

**Comment by abandin-stratio** [comment]
Ok, got it. The you should change the file to run inside the container:

docker run -t -v ~/nominatim-data:/data nominatim  sh /app/init.sh /data/spain-latest.osm.pbf postgresdata 2

**Comment by mbrucher** [comment]
Yes, the pbf name is not the destination file name, but the data you want to read.

**Comment by macieg** [comment]
Perfect! Works now. Thanks @abandin-stratio and @mbrucher .

 I'll create a pull request to make the guide clearer.

**Comment by ArmyGuy62** [comment]
So I have read the thread down to this point but I am still having the same problem as macieg was originally. This is my print out....what am I missing??
john@ubuntu:/data/dump/nominatim$ docker run -t -v ~/nominatimdata:/data mediagis/nominatim sh /app/init.sh /data/dump/nominatim/on.osm.pbf postgresdata 2
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /data/postgresdata ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/11/bin/pg_ctl -D /data/postgresdata -l logfile start

waiting for server to start....2020-04-15 17:05:41.263 UTC [29] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-04-15 17:05:41.263 UTC [29] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2020-04-15 17:05:41.263 UTC [29] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2020-04-15 17:05:41.281 UTC [29] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-04-15 17:05:41.312 UTC [30] LOG:  database system was shut down at 2020-04-15 17:05:41 UTC
2020-04-15 17:05:41.331 UTC [29] LOG:  database system is ready to accept connections
 done
server started
NOTICE:  database "nominatim" does not exist, skipping
DROP DATABASE
ERROR: the path supplied to --osm-file does not exist
string(46) "the path supplied to --osm-file does not exist"

**Comment by gsi-luis** [comment]
Solved defined other volumen binding file *.pbf into container before execute sh /app/init.sh, example:

docker run -t -v ~/nominatimdata:/data mediagis/nominatim **-v ~/pbf/on.osm.pbf:/home/nominatim/on.osm.pbf** sh /app/init.sh **/home/nominatim/on.osm.pbf** postgresdata 2
