### ISSUE TITLE
LOG:  checkpoints are occurring too frequently (15 seconds apart)

### ISSUE THREAD

**Issue by davidmegginson** [mediagis/nominatim-docker#82]
Frequent warning during initial import from planet-latest.osm.pbf:

```
20:42:24.644 UTC [28] LOG:  checkpoints are occurring too frequently (17 seconds apart)
2019-07-19 20:42:24.644 UTC [28] HINT:  Consider increasing the configuration parameter "max_wal_size".
```

Any suggestions?

**Comment by pratapvivek007** [comment]
@davidmegginson  I am also facing the same issue .
I would like to know did you fix the issue ..?
if yes ,Please share here

any help from anyone will be much appreciated..!

**Comment by mtmail** [comment]
Those lines can be ignored. During initial import the database is put under a lot of stress, ideally all CPU cores and disk IO are at (almost) maximum usage. The installation will finish and not be slowed down by the infrequent checkpoints.

The Nominatim project has a rough guide on Postgresql setting http://nominatim.org/release-docs/latest/admin/Installation/#postgresql-tuning Those are from Postgresql 9.3 times and work alright. They're heavy dependent on what hardware is used so with a docker setup there won't be single perfect setting.

**Comment by brad-4k** [comment]
I've just run into this problem as well.  How long should I wait before giving up?  It appears to have started about 12 hours ago.

> 2022-07-25 02:03:43.550 UTC [31871] LOG:  checkpoints are occurring too frequently (27 seconds apart)
> 2022-07-25 02:03:43.550 UTC [31871] HINT:  Consider increasing the configuration parameter "max_wal_size".
>

**Comment by Stefanic** [comment]
As mtmail already indicated, this is expected during import.
So you should wait as long as the import is running.

**Comment by brad-4k** [comment]
Thank you @Stefanic for the quick response.

I'm concerned, simply because there doesn't appear to be a lot of activity right now.  The CPU's (all 32) are pretty quiet.  Wondering if there is a way to make sure that the process is not hanging?

**Comment by Stefanic** [comment]
You should see progress in the 'Done 1140 in 2 @ 556.124 per second - rank 30 ETA (seconds): 1.88' lines

**Comment by brad-4k** [comment]
I believe it locked up.  There has been no updates on the screen for over 24 hours.

**Comment by brad-4k** [comment]
...  Never mind!  It's running!  Thank you for all that answered my questions and everyone for all your hard work.
