### ISSUE TITLE
Can I re use my existing openStreet map's tile server imported data ? 

### ISSUE THREAD

**Issue by iksheth** [mediagis/nominatim-docker#83]

**Comment by mtmail** [comment]
Nominatim and tile server use different table schema so that's not possible. You will need two databases.

**Comment by src-r-r** [comment]
For anyone hoping for an easy(ish) solution, there is one.

This looks complicated but what this does is pretty straightforward. **The tl;dr version:** Just assign a static IP address to the tileserver, then change the nominatim instance to point to the local tileserver.

Now for the not-so-short walkthrough.

Use this docker tile server: https://github.com/Overv/openstreetmap-tile-server, using the same obf data you used for nominatim-docker.

Next ensure the nominatim-docker is running. run the following commands (replace `3.5` with whatever version you want):

```bash
# This will basically copy `settings.php` and `defaults.php` from the server to a local copy.
docker exec -d nominatim cat /app/src/build/settings/settings.php 2&>./nominatim-docker/3.5/config-local.php
docker exec nominatim cat /app/src/settings/defaults.php 2&> nominatim-docker/3.5/config-defaults.php
```

Create a docker network for both `nominatim-docker` and `openstreetmap-tile-server`

```bash
docker network create --subnet=172.18.0.0/16 osm_net
```
Note the 172.18.0.0 subnet. Choose 2 distinct IP addresses to assign to each docker container. In my
case I chose **172.18.0.2** for the **tile server** and **172.18.0.3** for the **nominatim server**.

Within the files `config-local.php` *and* `config-defaults.php` Look for the PHP const `CONST_Map_Tile_URL` (around line 99). ***IMPORTANT:*** **remember to replace 172.18.0.2 with whatever you used for the IP address above**.

```php.diff
@define('CONST_Default_Zoom', 2);
-@define('CONST_Map_Tile_URL', 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');
+@define('CONST_Map_Tile_URL', 'http://172.18.0.2/tile/{z}/{x}/{y}.png');
@define('CONST_Map_Tile_Attribution', ''); // Set if tile source isn't osm.org
```
Now modify the Dockerfile in the version of nominatim you want.

```Dockerfile.diff
...
# Nominatim install
...
RUN cd ./src && git checkout tags/$NOMINATIM_VERSION && git submodule update --recursive --init && \
    mkdir build && cd build && cmake .. && make -j`nproc`
- # Don't include the '+' at the beginning...it's only for highlighting
+COPY config-defaults.php /app/src/settings/defaults.php
+COPY config-local.php /app/src/build/settings/settings.php

# Apache configure
COPY local.php /app/src/build/settings/local.php
COPY nominatim.conf /etc/apache2/sites-enabled/000-default.conf
...
```
Finally, follow the rest of the directions for set up as normal, except when you get to the `docker run` step. Modify the command to look like this:

```bash
# Start the tile server
docker run \
    -p 8080:80 \
    --ip 172.18.0.2 \
    --net osm_net \
    --name tileserver \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    -d overv/openstreetmap-tile-server \
    run
# Start the nominatim instance
docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim \
  -v ${OSM_DESTINATION_DIR}/postgresdata:/var/lib/postgresql/12/main \
  --net osm_net \
  --ip 172.18.0.3 \
  nominatim bash /app/start.sh
```

To see if it's correctly calling the right server, open nominatim in the browser, open the *network* section in the developer tools (e.g. `F12`) and look for a location within the obf set you downloaded. Any network request of a number is most likely a request for a tile. If the request is for the server `172.18.0.3`, you're golden!

If not, then double-check the commands, the IP address you assigned for the network, the network name in the `docker run` command, the replacement IP address in the PHP files, and the `COPY` lines in the `Dockerfile`.

**Comment by mtmail** [comment]
It's a good description, just need to point out it doesn't solve the issue/question reported. This solution shares the same postgresql server, possibly the same input file (*.pbf) but the data will still be imported twice, into two separate databases requiring two update processes to keep them uptodate. Imported data isn't reused.
