### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by timwaters** [mediagis/nominatim-docker#85]
Hello,

I'm wondering what open source license do you intend for this repo? And can a license file be added to the repo? ( openstreetmap/nominatim is GPLv2 )

Many thanks!

**Comment by Soty89** [comment]
I have the same question. thanks in advance for the help.

**Comment by knowname** [comment]
me too.. any progress?

**Comment by philipkozeny** [comment]
License is now available: https://github.com/mediagis/nominatim-docker/commit/1f892dc9b3c695bf799f6f34780b349f46a18320
