### ISSUE TITLE
Add more maps

### ISSUE THREAD

**Issue by GoNzCiD** [mediagis/nominatim-docker#86]
I have initialized nominatim with one region and works fine..., but I want to add more regions, How I can do it?

**Comment by gmalenko** [comment]
An answer here would be nice.  The only thing I can think of is to combine regions

**Comment by mtmail** [comment]
The Nominatim setup scripts don't have the feature to add more regions after an initial import. See https://github.com/openstreetmap/Nominatim/issues/224 for hints how to combine input files, https://github.com/openstreetmap/Nominatim/issues/60 on how to setup the update scripts for multiple regions.

**Comment by gmalenko** [comment]
After more searching, you would have to combine the files you want then do the import.  This is what I did for USA

`osmium merge us-midwest-latest.osm.pbf us-northeast-latest.osm.pbf us-pacific-latest.osm.pbf us-south-latest.osm.pbf us-west-latest.osm.pbf -o usa.osm.pbf
`

**Comment by GoNzCiD** [comment]
Finally, I can import more regions without doing an initial merge of several regions:

* Download other regions in osm.bz2 extension. (maybe is posibble to convert pbf to bz2)
* import with `update.php --import-file other_region.osm.bz2` (repeat with each region, I don't try if it's possible to add more regions in same update.php call)
* make and index: `update.php --index`

I don't know if this is the best method to add regions but it works for me.

**Comment by kenseii** [comment]
https://help.openstreetmap.org/questions/72889/utilsupdatephp-import-file-gives-error

**Comment by mtmail** [comment]
Having the information split between the docker repository and and help.osm.org isn't optimal. Ideally it would be a page on http://nominatim.org/release-docs/latest/ We created an issue to combine it https://github.com/openstreetmap/Nominatim/issues/1683 a couple of days ago.
