### ISSUE TITLE
Importing Tiger into 3.3

### ISSUE THREAD

**Issue by ktomari** [mediagis/nominatim-docker#89]
I've successfully set up Nominatim on Docker and imported OSM data, but I'm having trouble importing the TIGER data. I'm not strongly familiar with Docker or Postgresql, so perhaps I'm missing something. I would greatly appreciate any help!

At the core of my issue seems to occur once the `--import-tiger-data` line is called and the CLI repeatedly prints "... LOG: incomplete startup packet". It seems, based on the size of my postgres db that it does not in fact include the TIGER data. Moreover, when I submit a query, I typically don't receive a housenumber. (Note, in the sample code below I use Washington DC, whose OSM data is replete with house numbers, but even so the TIGER data doesn't appear to show up.)

I'm utilizing a combination of data/code from:

- https://github.com/openstreetmap/Nominatim/blob/master/docs/admin/Import-and-Update.md#installing-tiger-housenumber-data-for-the-us
- https://github.com/openstreetmap/Nominatim/issues/1199

**This is what I did:**

1. Cloned the git and modified "3.3". Specifically, I modified the 'init.sh', and the 'local.php' files. (See links below.) Primarily, I added these lines to 'init.sh':

`sudo -u nominatim ./src/build/utils/setup.php --import-tiger-data && \
sudo -u nominatim ./src/build/utils/setup.php --create-functions --enable-diff-updates --create-partition-functions && \`

and I added this line to 'local.php': `@define('CONST_Use_US_Tiger_Data', true);`

init.sh: https://pastebin.com/ukQfNaFz
local.php: https://pastebin.com/uWLgdc3F

2. Then I build the image:

`sudo docker image build "3.3"`

(The CLI states that it was "Successfully built 77059ff55dae", which I then tag with a new name, `sudo docker tag 77059ff55dae mediagis3.3_tiger`)

3. Downloaded the preprocessed TIGER data here: https://nominatim.org/data/tiger2019-nominatim-preprocessed.tar.gz

4. Downloaded the OSM pbf data from Geofabrik (Washington DC as an example: http://download.geofabrik.de/north-america/us/district-of-columbia-latest.osm.pbf)

5. I placed both the OSM pbf and uncompressed 'tiger' folder in a directory named "spatial_dbs"

6. Then I initialize the db in the CLI:
`sudo docker run -t -v ~/Documents/parking_tickets/spatial_dbs:/data mediagis3.3_tiger sh /app/init.sh /data/district-of-columbia-latest.osm.pbf dc/postgresdata 8`

7. Finally, I run the container:

`docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim_dc -v ~/Documents/parking_tickets/spatial_dbs/dc/postgresdata:/var/lib/postgresql/11/main mediagis3.3_tiger bash /app/start.sh`

(8. I go to localhost:7070 and query an address.)

Perhaps I'm missing a step? I was thinking perhaps the path to the TIGER db is incorrect?

Thanks again!

Update 1:

Here is the (hopefully relevant) output from the CLI during step 6 (initialization).

> 2019-10-29 18:50:44 == Setup finished.
2019-10-29 18:50:44 == module path: /app/src/build/module
2019-10-29 18:50:44 == Import Tiger data
2019-10-29 18:50:44.506 UTC [615] LOG:  incomplete startup packet
2019-10-29 18:50:44.511 UTC [617] LOG:  incomplete startup packet
2019-10-29 18:50:44.515 UTC [619] LOG:  incomplete startup packet
2019-10-29 18:50:44.519 UTC [621] LOG:  incomplete startup packet
2019-10-29 18:50:44.524 UTC [623] LOG:  incomplete startup packet
2019-10-29 18:50:44.529 UTC [625] LOG:  incomplete startup packet
2019-10-29 18:50:44.533 UTC [627] LOG:  incomplete startup packet
2019-10-29 18:50:44 == Creating indexes on Tiger data
Summary of warnings:

> 2019-10-29 18:50:44 == Setup finished.
2019-10-29 18:50:44 == module path: /app/src/build/module
2019-10-29 18:50:44 == Create Functions
2019-10-29 18:50:44 == Create Partition Functions
Summary of warnings:

> 2019-10-29 18:50:44 == Setup finished.
waiting for server to shut down....2019-10-29 18:50:45.007 UTC [28] LOG:  received fast shutdown request
2019-10-29 18:50:45.009 UTC [28] LOG:  aborting any active transactions
2019-10-29 18:50:45.010 UTC [28] LOG:  background worker "logical replication launcher" (PID 35) exited with exit code 1
2019-10-29 18:50:45.534 UTC [30] LOG:  shutting down
2019-10-29 18:50:45.733 UTC [28] LOG:  database system is shut down
 done
server stopped

**Comment by mtmail** [comment]
The `setup.php --import-tiger-data` looks for files `CONST_Tiger_Data_Path.'/*.sql'`, the default is the `data/tiger/` subdirectory below the `Nominatim` directory. Look for the `us_postcode_table.sql` file, that's the `data` directory.
https://github.com/openstreetmap/Nominatim/blob/master/lib/setup/SetupClass.php#L495

From your description it's not clear if you uncompressed the preprocessed .tar.gz file and in which directory the `*.sql` files were put.

`LOG: incomplete startup packet` comes from the postresql server and not the Nominatim server. I think you can ignore the message. What you will see during a successful import is lines like `12345.sql.....` for each file (about 3000 files). It will take at least an hour to import the files.

**Comment by ktomari** [comment]
Thanks for your fast reply! (And sorry for my late one.) I did uncompress the tiger2019-nominatim-preprocessed.tar.gz.

Now in my Documents/parking_tickets/spatial_dbs:

- tiger/ (with thousands of *.sql)

- district-of-columbia-latest.osm.pbf

In [Nominatim issues 1199](https://github.com/openstreetmap/Nominatim/issues/1199), the author downloads the TIGER data. However, I wanted to avoid that step so I wouldn't be downloading multiple copies of TIGER. So my intention was--following the approach to load the osm.pbf data from outside docker--to load the TIGER data externally. This is where I'm stuck, evidently. By my reasoning, due to the code in step #6, `...-v ~/Documents/parking_tickets/spatial_dbs:/data...`, this container should have access to all of the files in .../spatial_dbs in the docker filesystem as /data. In other words, I'm imagining that /data/tiger should lead to Documents/parking_tickets/spatial_dbs/tiger, no? So the fact that it can't find *.sql files is perplexing.

**Comment by rmakkar79** [comment]
Here is how successfully did it in case if it helps :

1. using docker image for nominatim 3.3
2. wget https://nominatim.org/data/tiger2019-nominatim-preprocessed.tar.gz 
3. data directory in docker image is under /app/src/data ( out of the box )
4. tar xf tiger2019-nominatim-preprocessed.tar.gz - on this step when i tried from with in container it failed , so i did on VM and then mounted in container.
5. docker exec -it nominatim sudo -u postgres ./src/build/utils/setup.php --import-tiger-data
6. docker exec -it nominatim sudo -u postgres ./src/build/utils/setup.php --create-functions --enable-diff-updates --create-partition-functions
7. Finally change "/app/src/build/settings/settings/local.php" and add @define('CONST_Use_US_Tiger_Data', true); 
I added above line just after "@define('CONST_Pyosmium_Binary', '/usr/local/bin/pyosmium-get-changes');"

That's it

**Comment by rooch84** [comment]
Thanks for the walkthrough. As a final step, I had to also modify `/app/src/build/settings/settings-frontend.php` and set `CONST_Use_US_Tiger_Data` from `false` to `true`.

**Comment by philipkozeny** [comment]
Importing Tiger data is now directly supported in 4.x.

PR: https://github.com/mediagis/nominatim-docker/pull/293
