### ISSUE TITLE
Using a flatnode storage of node locations

### ISSUE THREAD

**Issue by patrikhermansson** [mediagis/nominatim-docker#9]
Hello, I've had success with the project and modified the dockerfile to import wikipedia data but i cannot get it to work with flatnode storage of node locations as described in the Nominatim documentation. 

I only get a very non-descriptive error message:

`Processing: Node(32310k 375.7k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Failed to write out node cache: Success
Error occurred, cleaning up
Error executing external command: /app/src/osm2pgsql/osm2pgsql --flat-nodes /app/src/data/flatnodes -lsc -O gazetteer --hstore --number-processes 1 -C 18090 -P 5432 -d nominatim /app/src/data.osm.pbf
ERROR: Error executing external command: /app/src/osm2pgsql/osm2pgsql --flat-nodes /app/src/data/flatnodes -lsc -O gazetteer --hstore --number-processes 1 -C 18090 -P 5432 -d nominatim /app/src/data.osm.pbf`

Any ideas how to get this to work?

**Comment by cdarken** [comment]
I also tried to import a small pbf to test flatnode storage:
```
docker run -t -v /home/cata/tmp/nominatim-data:/data -v /home/cata/tmp/nominatim-data/local.php:/app/src/settings/local.php nominatim  sh /app/init.sh /data/iceland-latest.osm.pbf postgresdata 2
```
My local.php
```
<?php

@define('CONST_Osm2pgsql_Flatnode_File', '/data/flatnode.file');
```
But I get nothing, not even an error, everything seems to work fine. What am I missing? The official documentation says to just set this in local.php.
