### ISSUE TITLE
How to increase the number of used processes for update-step via "osmosis-all"

### ISSUE THREAD

**Issue by Snickbrack** [mediagis/nominatim-docker#91]
How can I increase the count of used processes for update the nominatim data via the "--import-osmosis-all"?

The update process outputs that it will automatically use only 1 process which will result in long updates. I want to use at least 4 processes to import updated data.

How can I setup the new count of used processes?

**Comment by mtmail** [comment]
There's no option currently. See comments in PR https://github.com/openstreetmap/Nominatim/pull/1408
