### ISSUE TITLE
Slim Mode

### ISSUE THREAD

**Issue by gmalenko** [mediagis/nominatim-docker#92]
Is there any way to run this in slim mode? I'm constantly getting out of memory issues

![image](https://user-images.githubusercontent.com/6521413/68589405-cdd35100-0459-11ea-8572-f1cdd989ad65.png)

**Comment by philipkozeny** [comment]
Closing the issue for now, please try the latest version (3.6 at the moment), there have been a lot of changes / fixes, thanks!

Also see https://nominatim.org/release-docs/latest/admin/Installation/#hardware for hardware requirements.
