### ISSUE TITLE
Only one "earth tile" being loaded

### ISSUE THREAD

**Issue by bulaxy** [mediagis/nominatim-docker#94]
Hi, 
I have installed Docker recently and build/run the nominatim-docker (3.4) container. 
I am able to access the site and most things as expected, however, when I zoom out of the map, only one tile of the map being loaded
That means the map getting cut off in the Pacific Ocean
If I keep moving the map towards one direction, the map will become blank. 

But the mini map display the whole map as normal.
![image](https://user-images.githubusercontent.com/43806377/68918306-b7aef300-07c1-11ea-80c6-3777683c5bc1.png)

**Comment by mtmail** [comment]
I wrote a PR against the Nominatim software https://github.com/openstreetmap/Nominatim/pull/1581

**Comment by bulaxy** [comment]
Thank you. Got it working.
