### ISSUE TITLE
postgresql install is not as it is expected 

### ISSUE THREAD

**Issue by KamyarGhajar** [mediagis/nominatim-docker#96]
Hi,
On building the 3.4 nominatim docker I get the following error
`Step 6/21 : RUN echo "host all  all    0.0.0.0/0  trust" >> /etc/postgresql/11/main/pg_hba.conf &&     echo "listen_addresses='*'" >> /etc/postgresql/11/main/postgresql.conf
 ---> Running in 79415fa12d71
/bin/sh: 1: cannot create /etc/postgresql/11/main/pg_hba.conf: Directory nonexistent`

Seems like a bug.

**Comment by KamyarGhajar** [comment]
This is the error preventing postgresql to install properly:
`Setting up postgresql-11 (11.5-1) ...
Creating new PostgreSQL cluster 11/main ...
/usr/lib/postgresql/11/bin/initdb -D /var/lib/postgresql/11/main --auth-local peer --auth-host md5
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

initdb: invalid locale settings; check LANG and LC_* environment variables
Error: initdb failed
Error: could not create default cluster. Please create it manually with

  pg_createcluster 11 main --start`

And yes. I have tried everything to setup the locale LANG or LC_CTYPE to set system locales.

**Comment by philipkozeny** [comment]
@KamyarGhajar can you provide steps to reproduce it? I have just cloned the repo in a fresh directory, pruned all local docker containers and built it in the 3.4 directory with `docker build -t nominatim .`

Result:

```
Step 6/20 : RUN echo "host all  all    0.0.0.0/0  trust" >> /etc/postgresql/11/main/pg_hba.conf &&     echo "listen_addresses='*'" >> /etc/postgresql/11/main/postgresql.conf
 ---> Running in 478f75f62821
Removing intermediate container 478f75f62821
 ---> c57d9ea5ae1e
Step 7/20 : ENV NOMINATIM_VERSION v3.4.0
```

**Comment by KamyarGhajar** [comment]
Actually, I can build the docker container on my mac properly, but this happens on my server with Ubuntu 16.04, both with latest docker-ce installed with command: 
`docker build -t nominatim-docker:3.4 .  --no-cache`

**Comment by Amrit0991** [comment]
@KamyarGhajar I had this same problem.

Your docker-engine has run out of allotted space for images. On Mac, I fixed this by opening the Docker for Desktop app and giving myself more space.

I'm not sure how to do that on linux, but these commands should at least clear up some space for you:

```
docker container prune
docker image prune
```

The Nominatim images took up about 17GB of space for me.
