### ISSUE TITLE
Incoherency in postgres database directory

### ISSUE THREAD

**Issue by s0m30n3** [mediagis/nominatim-docker#98]
Hi,

It seems there is a script issue in the 3.4 folder.

We use
sudo -u postgres /usr/lib/postgresql/11/bin/pg_ctl -D /data/$PGDIR start
and
sudo -u postgres /usr/lib/postgresql/11/bin/pg_ctl -D /data/$PGDIR stop
in init.sh
but
service postgresql start
and
service postgresql stop
in start.sh

Since we do not start the server using the same database folder, we cannot access the data.

Please fix the scripts.
I recommend using the default directory that is, using pg_ctl without -D but maybe with -w as suggessted in #18.
If someone wants to use a different folder, you can still use a named mount pointing to /var/lib/postgresql/data like it's done in other projects (like openmaptiles).

Thanks

**Comment by s0m30n3** [comment]
I tried modifying the init.sh script and it seems pg_ctl doesn't work without -D so I just used service instead:

The following works for me:
```
service postgresql start && \
sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='nominatim'" | grep -q 1 || sudo -u postgres createuser -s nominatim && \
sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='www-data'" | grep -q 1 || sudo -u postgres createuser -SDR www-data && \
sudo -u postgres psql postgres -c "DROP DATABASE IF EXISTS nominatim" && \
useradd -m -p password1234 nominatim && \
chown -R nominatim:nominatim ./src && \
sudo -u nominatim ./src/build/utils/setup.php --osm-file $OSMFILE --all --threads $THREADS && \
service postgresql stop
```

**Comment by philipkozeny** [comment]
Thanks for your input, with the latest 3.6 update we've switched to ```service``` now on init & start.
